import type { AmbientFrame,ThunderEvent } from './simulation';
export class AmbientAudio {
 private context?:AudioContext;private master?:GainNode;private channels=new Map<string,GainNode>();private sources:AudioScheduledSourceNode[]=[];private buffer?:AudioBuffer;private lastBird=0;private lastUpdate=-1;private volume=0;private transient=new Set<AudioScheduledSourceNode>();
 async setVolume(volume:number){this.volume=Math.max(0,Math.min(1,volume));if(!this.context&&volume>0)this.create();if(!this.context||!this.master)return;this.master.gain.setTargetAtTime(this.volume*.3,this.context.currentTime,.4);if(volume>0&&!document.hidden)await this.context.resume();else await this.context.suspend();}
 private create(){const c=this.context=new AudioContext();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.buffer=c.createBuffer(1,c.sampleRate*3,c.sampleRate);const samples=this.buffer.getChannelData(0);let last=0;for(let i=0;i<samples.length;i++){last=(last+.04*(Math.random()*2-1))/1.04;samples[i]=last*4;}
 for(const [name,type,hz] of [['wind','lowpass',500],['rain','highpass',1800],['roof','bandpass',900],['water','lowpass',1100],['night','bandpass',4600]] as const){const source=c.createBufferSource();source.buffer=this.buffer;source.loop=true;const filter=c.createBiquadFilter();filter.type=type;filter.frequency.value=hz;const gain=c.createGain();gain.gain.value=0;source.connect(filter).connect(gain).connect(this.master);source.start();this.sources.push(source);this.channels.set(name,gain);}document.addEventListener('visibilitychange',this.visibility);}
 private visibility=()=>{if(!this.context)return;if(document.hidden)void this.context.suspend();else if(this.volume>0)void this.context.resume();};
 step(f:AmbientFrame){const c=this.context;if(!c||c.state!=='running'||c.currentTime-this.lastUpdate<.25)return;this.lastUpdate=c.currentTime;const levels:Record<string,number>={wind:.025+f.wind/160,rain:f.rain*.4,roof:f.rain*.17,water:.08+f.runoff*.1,night:(1-f.daylight)*(1-f.rain)*.04};for(const [name,gain] of this.channels)gain.gain.setTargetAtTime(levels[name]??0,c.currentTime,1.5);if(c.currentTime>this.lastBird&&f.birdActivity>.3){this.lastBird=c.currentTime+8+Math.random()*18;const bird=c.createOscillator(),gain=c.createGain();bird.frequency.setValueAtTime(1900+Math.random()*900,c.currentTime);bird.frequency.exponentialRampToValueAtTime(3400,c.currentTime+.12);gain.gain.setValueAtTime(0,c.currentTime);gain.gain.linearRampToValueAtTime(.035*f.birdActivity,c.currentTime+.04);gain.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.28);bird.connect(gain).connect(this.master!);this.track(bird,gain);bird.start();bird.stop(c.currentTime+.3);}}
 thunder(event:ThunderEvent){const c=this.context;if(!c||c.state!=='running'||!this.buffer)return;const source=c.createBufferSource();source.buffer=this.buffer;source.playbackRate.value=.35;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=140+1200/(1+event.distance/500);const gain=c.createGain();gain.gain.setValueAtTime(.001,c.currentTime);gain.gain.exponentialRampToValueAtTime(event.strength/(1+event.distance/3000),c.currentTime+.35);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+4);source.connect(filter).connect(gain).connect(this.master!);this.track(source,gain,filter);source.start();source.stop(c.currentTime+4.1);}
 private track(source:AudioScheduledSourceNode,...nodes:AudioNode[]){this.transient.add(source);source.onended=()=>{source.disconnect();nodes.forEach(n=>n.disconnect());this.transient.delete(source);};}
 dispose(){document.removeEventListener('visibilitychange',this.visibility);for(const s of [...this.sources,...this.transient]){try{s.stop();}catch{}s.disconnect();}this.sources=[];this.transient.clear();this.channels.clear();void this.context?.close();this.context=undefined;this.buffer=undefined;}
}
