import * as THREE from 'three';
import type { AmbientFrame } from './simulation';
// Buffers e instâncias são alocados uma vez; a chuva apenas os reutiliza.
export class WeatherEffects {
 readonly group=new THREE.Group();private count=900;private positions=new Float32Array(this.count*6);private snowData=new Float32Array(200*3);private leafData=new Float32Array(60*3);private ages=new Float32Array(60);private dummy=new THREE.Object3D();
 private rain:THREE.LineSegments;private snow:THREE.Points;private leaves:THREE.Points;private splashes:THREE.InstancedMesh;private puddles:THREE.Mesh[]=[];private time=0;
 constructor(){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(this.positions,3));this.rain=new THREE.LineSegments(geometry,new THREE.LineBasicMaterial({color:'#b9ceda',transparent:true,opacity:0,depthWrite:false}));this.group.add(this.rain);for(let i=0;i<this.count;i++){this.positions[i*6]=(Math.random()-.5)*110;this.positions[i*6+1]=Math.random()*65-7;this.positions[i*6+2]=10-Math.random()*110;}
 const points=(data:Float32Array,color:string,size:number)=>{for(let i=0;i<data.length;i+=3){data[i]=(Math.random()-.5)*100;data[i+1]=Math.random()*55;data[i+2]=-Math.random()*90;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(data,3));const p=new THREE.Points(g,new THREE.PointsMaterial({color,size,transparent:true,depthWrite:false}));this.group.add(p);return p;};this.snow=points(this.snowData,'#e6eced',.2);this.leaves=points(this.leafData,'#947c43',.12);
 this.splashes=new THREE.InstancedMesh(new THREE.RingGeometry(.12,.15,12),new THREE.MeshBasicMaterial({color:'#b7ced3',transparent:true,opacity:.2,side:THREE.DoubleSide,depthWrite:false}),60);this.splashes.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.splashes.frustumCulled=false;this.group.add(this.splashes);for(let i=0;i<60;i++)this.ages[i]=Math.random();
 for(const [x,y,z,size] of [[-2,.44,-17,4],[32,2.44,-46,4],[-25,5.44,-38,3],[7,13.44,-63,2]]){const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{wet:{value:0},rain:{value:0},time:{value:0},day:{value:1}},vertexShader:'varying vec2 p;void main(){p=uv*2.-1.;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 p;uniform float wet;uniform float rain;uniform float time;uniform float day;void main(){float r=length(p);float edge=1.-smoothstep(.65,1.,r+.08*sin(p.x*17.)*sin(p.y*19.));float ripple=pow(max(0.,sin(r*44.-time*5.)),14.)*rain*.3;vec3 reflection=mix(vec3(.08,.13,.18),vec3(.35,.48,.5),day)*(1.-r*.2);gl_FragColor=vec4(reflection+ripple,edge*wet*.7);}'});const p=new THREE.Mesh(new THREE.PlaneGeometry(size*2,size),mat);p.rotation.x=-Math.PI/2;p.position.set(x,y,z);this.puddles.push(p);this.group.add(p);}
 }
 step(f:AmbientFrame,dt:number,motion:number,quality:number){this.time+=dt*motion;const angle=f.direction*Math.PI/180,wx=-Math.sin(angle)*f.wind*.08,wz=-Math.cos(angle)*f.wind*.08;const active=Math.floor(this.count*f.rain*quality);this.rain.geometry.setDrawRange(0,active*2);(this.rain.material as THREE.LineBasicMaterial).opacity=.12+f.rain*.38;
 for(let i=0;i<active;i++){const n=i*6,speed=12+(i%11)+f.rain*12;let x=this.positions[n]+wx*dt*motion,y=this.positions[n+1]-speed*dt*motion,z=this.positions[n+2]+wz*dt*motion;if(y< -7||Math.abs(x)>60||z>15||z< -105){y=55+Math.random()*10;x=(Math.random()-.5)*110;z=10-Math.random()*110;}this.positions[n]=x;this.positions[n+1]=y;this.positions[n+2]=z;const len=.1+f.rain*.65+(i%3)*.1;this.positions[n+3]=x-wx/speed*len;this.positions[n+4]=y+len;this.positions[n+5]=z-wz/speed*len;}this.rain.geometry.attributes.position.needsUpdate=active>0;
 const updatePoints=(p:THREE.Points,data:Float32Array,amount:number,fall:number)=>{p.visible=amount>.01;p.geometry.setDrawRange(0,Math.floor(data.length/3*amount*quality));if(!p.visible)return;for(let i=0;i<data.length;i+=3){data[i]+=(wx+Math.sin(this.time+i)*.3)*dt*motion;data[i+1]-=dt*fall*motion;data[i+2]+=wz*dt*motion;if(data[i+1]< -7||Math.abs(data[i])>55){data[i+1]=50;data[i]=(Math.random()-.5)*100;}}p.geometry.attributes.position.needsUpdate=true;};updatePoints(this.snow,this.snowData,Math.min(1,f.snow+f.hail),f.hail>.1?16:1.1);updatePoints(this.leaves,this.leafData,Math.min(1,f.gust/65),.7);
 this.splashes.count=Math.floor(60*f.rain*quality);for(let i=0;i<this.splashes.count;i++){this.ages[i]+=dt*motion;if(this.ages[i]>1)this.ages[i]=0;const surface=i%3;this.dummy.position.set(surface===0?-2+(i%7-3)*1.4:surface===1?-25+(i%5-2):i%13*6-35,surface===0?.48:surface===1?12:-6.95,surface===0?-17+i%5:surface===1?-38:-25-i%9*5);this.dummy.rotation.x=-Math.PI/2;this.dummy.scale.setScalar(this.ages[i]*2);this.dummy.updateMatrix();this.splashes.setMatrixAt(i,this.dummy.matrix);}this.splashes.instanceMatrix.needsUpdate=true;
 for(const p of this.puddles){const u=(p.material as THREE.ShaderMaterial).uniforms;u.wet.value=f.wetness;u.rain.value=f.rain;u.time.value=this.time;u.day.value=f.daylight;p.visible=f.wetness>.01;p.scale.setScalar(.4+f.wetness*.6);}
 }
}
