import {test,expect,type Page} from '@playwright/test';
const chave='http-bancada-idempotencia-v1';
async function abrir(pagina:Page){await pagina.goto('/#/percurso/redes');await pagina.getByRole('button',{name:'Experimentar tempo, falhas e repetição',exact:true}).click();return pagina.getByRole('region',{name:'Bancada HTTP: tempo e repetição'});}
test('HTTP offline distingue timeout de efeito, repete intenção e retoma o relógio',async({page:pagina,context:contexto})=>{
 const chamadas:string[]=[];pagina.on('request',pedido=>{if(/\/api\/(reservas|executions|execute|run|submissions)/.test(pedido.url()))chamadas.push(pedido.url());});
 await pagina.goto('/');await expect(pagina.locator('#offline-status')).toHaveText('Conteúdo preparado para estudar offline.',{timeout:45000});await pagina.waitForFunction(()=>Boolean(navigator.serviceWorker.controller));await contexto.setOffline(true);
 try{
  const bancada=await abrir(pagina);await bancada.getByRole('button',{name:'Enviar tentativa',exact:true}).click();await bancada.getByRole('button',{name:'Avançar 1.000 ms',exact:true}).click();await expect(bancada.locator('[data-cliente]')).toContainText('timeout; resultado da operação desconhecido');await expect(bancada.locator('[data-servidor]')).toHaveText('Reserva 1 · 2 lugares · pedido-123');
  await bancada.getByLabel('Cenário da próxima tentativa').selectOption('normal');await bancada.getByRole('button',{name:'Enviar tentativa',exact:true}).click();await bancada.getByRole('button',{name:'Próximo evento',exact:true}).click();await expect(bancada.locator('[data-cliente]')).toContainText('2: aguarda resposta');await bancada.getByRole('button',{name:'Próximo evento',exact:true}).click();await expect(bancada.locator('[data-cliente]')).toContainText('HTTP 201 · reserva 1 · resultado guardado');await expect(bancada.locator('[data-servidor]')).not.toContainText('Reserva 2');
  await bancada.getByLabel('Quantidade de lugares').fill('3');await bancada.getByRole('button',{name:'Enviar tentativa',exact:true}).click();await bancada.getByRole('button',{name:'Avançar 1.000 ms',exact:true}).click();await expect(bancada.locator('[data-cliente]')).toContainText('HTTP 409');
  await pagina.locator('[data-stage="idempotencia"] details summary').click();await pagina.reload({waitUntil:'domcontentloaded'});await pagina.getByRole('button',{name:'Experimentar tempo, falhas e repetição',exact:true}).click();await expect(bancada.locator('[data-cliente]')).toContainText('HTTP 409');await expect(bancada.locator('[data-servidor]')).not.toContainText('Reserva 2');
  const salvo=await pagina.evaluate(chave=>JSON.parse(localStorage.getItem('codelab.progress.v2')!).practiceAnswers[chave],chave);expect(salvo.assisted).toBe(true);expect(salvo.passed).toBe(false);expect(JSON.parse(salvo.value)).toHaveLength(7);

  await pagina.goto('/#/perfil');const pendente=pagina.waitForEvent('download');await pagina.locator('#export-progress').click();const fluxo=await (await pendente).createReadStream(),partes:Buffer[]=[];for await(const parte of fluxo!)partes.push(Buffer.from(parte));const backup=Buffer.concat(partes);expect(JSON.parse(backup.toString()).practiceAnswers[chave].value).toBe(salvo.value);await pagina.locator('#import-progress').setInputFiles({name:'jornada.json',mimeType:'application/json',buffer:backup});await pagina.getByRole('button',{name:'Restaurar jornada',exact:true}).click();await abrir(pagina);await expect(bancada.locator('[data-cliente]')).toContainText('HTTP 409');await expect(bancada.locator('[data-servidor]')).not.toContainText('Reserva 2');
  for(const largura of [220,4000]){await pagina.setViewportSize({width:largura,height:812});await expect.poll(()=>pagina.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await expect(bancada.getByRole('button',{name:'Enviar tentativa',exact:true})).toBeVisible();}expect(chamadas).toEqual([]);
 }finally{await contexto.setOffline(false);}
});
test('HTTP revela Retry-After, servidor lento e 503 sem confundir conhecimento do cliente',async({page:pagina})=>{
 const bancada=await abrir(pagina);await bancada.getByLabel('Cenário da próxima tentativa').selectOption('429');await bancada.getByRole('button',{name:'Enviar tentativa',exact:true}).click();await bancada.getByRole('button',{name:'Avançar 1.000 ms',exact:true}).click();await expect(bancada.locator('[data-cliente]')).toContainText('HTTP 429');await expect(bancada.locator('[data-retentativa]')).toContainText('esperar até 2300 ms');await expect(bancada.locator('[data-servidor]')).toHaveText('Nenhuma reserva efetiva.');
 await bancada.getByLabel('Cenário da próxima tentativa').selectOption('503');await bancada.getByRole('button',{name:'Enviar tentativa',exact:true}).click();await bancada.getByRole('button',{name:'Avançar 1.000 ms',exact:true}).click();await expect(bancada.locator('[data-retentativa]')).toContainText('backoff limitado');
 await bancada.getByRole('button',{name:'Reiniciar só HTTP',exact:true}).click();await bancada.getByLabel('Cenário da próxima tentativa').selectOption('lenta');await bancada.getByRole('button',{name:'Enviar tentativa',exact:true}).click();await bancada.getByRole('button',{name:'Próximo evento',exact:true}).click();await expect(bancada.locator('[data-relogio]')).toContainText('700 ms');await expect(bancada.locator('[data-cliente]')).toContainText('timeout');await expect(bancada.locator('[data-servidor]')).toHaveText('Nenhuma reserva efetiva.');await bancada.getByRole('button',{name:'Próximo evento',exact:true}).click();await expect(bancada.locator('[data-servidor]')).toContainText('Reserva 1');await expect(bancada.locator('[data-cliente]')).toContainText('timeout');await expect(bancada.getByRole('button',{name:'Próximo evento',exact:true})).toBeDisabled();
});

test('HTTP preserva ações incompatíveis para backup sem inventar efeitos',async({page:pagina})=>{
 await pagina.addInitScript(chave=>{localStorage.setItem('codelab.progress.v2',JSON.stringify({version:2,practiceAnswers:{[chave]:{value:'[{"tipo":"efeito-inventado","reservas":999}]',attempts:0,hints:0,assisted:false,passed:false,revision:1,updatedAt:''}}}));},chave);
 const bancada=await abrir(pagina);await expect(bancada.locator('[data-aviso]')).toContainText('incompatível');await expect(bancada.getByRole('button',{name:'Enviar tentativa',exact:true})).toBeDisabled();await expect(bancada.locator('[data-servidor]')).toHaveText('Nenhuma reserva efetiva.');const original=await pagina.evaluate(chave=>JSON.parse(localStorage.getItem('codelab.progress.v2')!).practiceAnswers[chave].value,chave);expect(original).toContain('efeito-inventado');await bancada.getByRole('button',{name:'Reiniciar só HTTP',exact:true}).click();await expect(bancada.getByRole('button',{name:'Enviar tentativa',exact:true})).toBeEnabled();
});
