import {reproduzirExperimentoHttp,restaurarExperimentoHttp,proximoEventoHttp,esperaRepeticaoHttp,type AcaoHttp,type PedidoHttp} from './http';
import {progress,saveProgress} from '../state';
import {emptyPracticeAnswer} from './activity-state';
const chaveRascunho='http-bancada-idempotencia-v1';
export function montarBancadaHttp(alvo:HTMLElement):()=>void{
 const resposta=progress.practiceAnswers[chaveRascunho]??emptyPracticeAnswer(),controle=new AbortController(),opcoes={signal:controle.signal};
 const restaurado=resposta.value===''?reproduzirExperimentoHttp([]):resposta.revision===1?restaurarExperimentoHttp(resposta.value):undefined;
 let modelo=restaurado??reproduzirExperimentoHttp([]),incompativel=!restaurado;
 alvo.innerHTML='<section class="practice-card lesson-check" aria-label="Bancada HTTP: tempo e repetição"><h3>Veja a operação antes da resposta</h3><p>Modelo didático offline de POST /reservas, com relógio manual. Não faz requisições ou reservas reais. O servidor deste modelo registra cada operação de forma indivisível e guarda a chave sem expiração; isso não implementa persistência distribuída nem prova comportamento de uma API real.</p><p>Envie uma reserva com resposta perdida, avance o relógio e compare o cliente com o servidor. Repita usando a mesma chave e conteúdo; depois experimente outra chave ou quantidade. Timeout não comprova que o servidor deixou de agir.</p><label class="field">Cenário da próxima tentativa<select data-cenario><option value="perdida">Resposta perdida depois da reserva</option><option value="normal">Resposta normal</option><option value="lenta">Servidor termina depois do timeout</option><option value="429">429 com Retry-After: 2</option><option value="503">503 sem prazo informado</option></select></label><label class="field">Chave da intenção (vazia: sem deduplicação)<input data-chave maxlength="40" value="pedido-123" spellcheck="false"></label><label class="field">Quantidade de lugares<input data-quantidade type="number" min="1" max="100" value="2"></label><div class="practice-actions"><button class="button primary" data-enviar>Enviar tentativa</button><button class="button subtle" data-avancar="100">Avançar 100 ms</button><button class="button subtle" data-avancar="1000">Avançar 1.000 ms</button><button class="button subtle" data-proximo>Próximo evento</button><button class="button subtle" data-reiniciar>Reiniciar só HTTP</button></div><p data-relogio></p><p data-tempos></p><h4>O que o cliente sabe</h4><pre data-cliente></pre><h4>O que aconteceu no servidor</h4><pre data-servidor></pre><p data-retentativa></p><p role="status" data-aviso></p><p class="small">Até 20 tentativas, 100 ações e dez minutos simulados. Nenhuma repetição automática: compare os resultados e decida. 429 pode informar espera; 503 exige política limitada de backoff e uma intenção segura. Conferir este modelo não produz nota de domínio.</p></section>';
 const bancada=alvo.querySelector<HTMLElement>('section')!,aviso=bancada.querySelector<HTMLElement>('[data-aviso]')!,cenario=bancada.querySelector<HTMLSelectElement>('[data-cenario]')!;
 function exibir(){
  const {estado}=modelo;
  bancada.querySelector('[data-relogio]')!.textContent='Relógio didático: '+estado.agora+' ms';
  bancada.querySelector('[data-cliente]')!.textContent=estado.tentativas.map(t=>t.id+': '+(t.cliente==='aguardando'?'aguarda resposta':t.cliente==='timeout'?'timeout; resultado da operação desconhecido':'HTTP '+t.status+(t.reserva?' · reserva '+t.reserva:'')+(t.repetida?' · resultado guardado':''))).join('\n')||'Nenhuma tentativa enviada.';
  bancada.querySelector('[data-servidor]')!.textContent=estado.reservas.map(r=>'Reserva '+r.id+' · '+r.quantidade+' lugares · '+(r.chave||'sem chave')).join('\n')||'Nenhuma reserva efetiva.';
  const ultima=estado.tentativas.at(-1),espera=ultima?esperaRepeticaoHttp(ultima):null;
  bancada.querySelector('[data-retentativa]')!.textContent=espera!==null?'Retry-After: 2. Cliente recebeu a resposta em '+ultima!.respostaEm+' ms; esperar até '+espera+' ms antes de repetir.':ultima?.cliente==='respondeu'&&ultima.status===503?'503: serviço indisponível neste cenário, sem efeito. Considere backoff limitado e a mesma identidade; uma API real pode ter outro contrato.':'';
  bancada.querySelector('[data-tempos]')!.textContent=ultima?'Tentativa '+ultima.id+': enviada '+ultima.enviadoEm+' ms → servidor '+ultima.servidorEm+' ms → resposta prevista '+ultima.respostaEm+' ms; prazo do cliente '+ultima.limiteEm+' ms. A resposta perdida nunca é entregue.':'Os tempos aparecerão após enviar.';
  for(const campo of bancada.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('input,select,button:not([data-reiniciar])'))campo.disabled=incompativel;
  bancada.querySelector<HTMLButtonElement>('[data-proximo]')!.disabled=incompativel||proximoEventoHttp(estado)===undefined;
 }
 function salvar(){resposta.value=JSON.stringify(modelo.acoes);resposta.updatedAt=new Date().toISOString();resposta.revision=1;resposta.assisted||=Boolean(progress.practiceAnswers['percurso-redes-idempotencia']?.assisted);progress.practiceAnswers[chaveRascunho]=resposta;aviso.textContent=saveProgress()?'Experimento salvo somente neste navegador.':'O navegador não conseguiu salvar. Exporte a jornada no perfil antes de sair; o experimento está em memória.';}
 function aplicar(acao:AcaoHttp){try{modelo=reproduzirExperimentoHttp([...modelo.acoes,acao]);salvar();exibir();}catch(erro){aviso.textContent=erro instanceof Error?erro.message:'Não foi possível avançar.';}}
 bancada.querySelector('[data-enviar]')!.addEventListener('click',()=>{
  const escolha=cenario.value,pedido:PedidoHttp={tipo:'enviar',chave:bancada.querySelector<HTMLInputElement>('[data-chave]')!.value,quantidade:Number(bancada.querySelector<HTMLInputElement>('[data-quantidade]')!.value),ida:100,processamento:escolha==='lenta'?1500:100,volta:100,prazo:700,falha:escolha==='perdida'?'perdida':escolha==='429'?'429':escolha==='503'?'503':'nenhuma'};aplicar(pedido);
 },opcoes);
 for(const botao of bancada.querySelectorAll<HTMLButtonElement>('[data-avancar]'))botao.addEventListener('click',()=>aplicar({tipo:'avancar',milissegundos:Number(botao.dataset.avancar)}),opcoes);
 bancada.querySelector('[data-proximo]')!.addEventListener('click',()=>{const proximo=proximoEventoHttp(modelo.estado);if(proximo!==undefined)aplicar({tipo:'avancar',milissegundos:proximo-modelo.estado.agora});},opcoes);
 bancada.querySelector('[data-reiniciar]')!.addEventListener('click',()=>{modelo=reproduzirExperimentoHttp([]);incompativel=false;salvar();exibir();},opcoes);
 const solucao=alvo.closest('[data-stage]')?.querySelector('details');solucao?.addEventListener('toggle',()=>{if(solucao.open&&!incompativel){resposta.assisted=true;salvar();}},opcoes);
 exibir();aviso.textContent=incompativel?'Rascunho incompatível preservado no backup. Exporte antes de reiniciar só HTTP.':'Experimento local, sem tráfego HTTP real. Avance o relógio para observar cada evento.';
 return()=>controle.abort();
}
