// Preserve concept identities introduced with PR #5. Curriculum order can change
// without invalidating completed sessions or concepts already read in local backups.
export const legacyConceptIds:Record<string,string>={
  "js-conversao-limites": "conceito-0-088-js-conversao-limites",
  "js-semantica": "conceito-0-087-js-semantica",
  "js-colecoes-iteracao": "conceito-2-092-js-colecoes-iteracao",
  "js-funcoes-this": "conceito-1-089-js-funcoes-this",
  "js-objetos-modelos": "conceito-2-091-js-objetos-modelos",
  "html-formularios": "conceito-1-099-html-formularios",
  "html-dados-formulario": "conceito-1-100-html-dados-formulario",
  "html-dialogo-foco": "conceito-2-103-html-dialogo-foco",
  "html-acessibilidade": "conceito-2-102-html-acessibilidade",
  "css-grid-trilhas": "conceito-1-110-css-grid-trilhas",
  "css-flex-grid": "conceito-1-109-css-flex-grid",
  "css-responsivo": "conceito-2-111-css-responsivo",
  "ts-validacao-aninhada": "conceito-1-072-ts-validacao-aninhada",
  "ts-contratos": "conceito-1-071-ts-contratos",
  "ts-inferencia-ausencia": "conceito-0-070-ts-inferencia-ausencia",
  "ts-fundamentos": "conceito-0-069-ts-fundamentos",
  "py-controle-invariantes": "conceito-0-062-py-controle-invariantes",
  "py-fundamentos": "conceito-0-060-py-fundamentos",
  "py-funcoes-contratos": "conceito-1-064-py-funcoes-contratos",
  "py-colecoes-funcoes": "conceito-1-063-py-colecoes-funcoes",
  "cs-decimal-limites": "conceito-0-115-cs-decimal-limites",
  "cs-tipos-controle": "conceito-0-114-cs-tipos-controle",
  "cs-iteradores-descarte": "conceito-2-120-cs-iteradores-descarte",
  "cs-assincrono-recursos": "conceito-2-119-cs-assincrono-recursos",
  "cs-metodos-parametros": "conceito-0-116-cs-metodos-parametros",
  "cpp-funcoes-referencias": "conceito-0-080-cpp-funcoes-referencias",
  "cpp-fundamentos": "conceito-0-078-cpp-fundamentos",
  "cpp-raii-posse-unica": "conceito-1-082-cpp-raii-posse-unica",
  "cpp-classes-raii": "conceito-1-081-cpp-classes-raii",
  "cpp-stl-algoritmos": "conceito-1-083-cpp-stl-algoritmos",
  "cpp-memoria-posse": "conceito-2-085-cpp-memoria-posse",
  "sql-null-logica": "conceito-0-124-sql-null-logica",
  "sql-modelagem-completa": "conceito-0-123-sql-modelagem-completa",
  "sql-joins-cardinalidade": "conceito-1-126-sql-joins-cardinalidade",
  "sql-consultas-joins": "conceito-1-125-sql-consultas-joins",
  "css-cascata-camadas": "conceito-0-106-css-cascata-camadas",
  "css-cascata": "conceito-0-105-css-cascata",
  "ts-fronteiras-qualidade": "conceito-3-077-ts-fronteiras-qualidade",
  "sql-transacoes": "conceito-2-128-sql-transacoes",
  "sql-isolamento-sessoes": "conceito-2-129-sql-isolamento-sessoes"
};
