import type { Mission } from '../types';
export const missions: Mission[] = [
 {id:'primeira-luz', title:'Uma pequena luz', concept:'Seu primeiro programa', summary:'Uma instrução. Uma mudança no mundo.', explanation:'Programar é escrever instruções que o computador pode executar. Uma função é uma ação com um nome. Para chamar uma função, escreva seu nome seguido de parênteses. Aqui, acender() acende a lanterna da sua bancada.', objective:'Chame acender() para iluminar a lanterna.', starter:'// Escreva sua primeira instrução abaixo.\n\n', solution:'acender();', hints:['O computador precisa receber uma ação.','A ação disponível se chama acender.','Uma chamada tem esta forma: nomeDaAcao();','Por exemplo, tocarSino(); chama a ação tocarSino.','acender();'], xp:50, minutes:3, tests:['A lanterna foi acesa.','A ação foi chamada uma única vez.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Functions'},
 {id:'seu-nome', title:'O mundo conhece você', concept:'Strings e saída', summary:'Dê uma voz ao seu código.', explanation:'Uma string é um texto entre aspas. A função dizer(texto) recebe esse texto e o mostra no mundo. O valor dentro dos parênteses é chamado de argumento. Experimente também console.log() para observar valores no console.', objective:'Use dizer() para apresentar seu nome com pelo menos duas letras.', starter:'// Troque as aspas vazias pelo seu nome.\ndizer("");', solution:'dizer("Ada");', hints:['Texto precisa ficar entre aspas.','Escreva seu nome dentro dos parênteses.','dizer("seu texto");','dizer("Olá, mundo!"); apresenta uma mensagem.','dizer("Ada");'], xp:60, minutes:4, tests:['Uma mensagem foi apresentada.','A mensagem tem pelo menos duas letras.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Grammar_and_types'},
 {id:'energia', title:'Energia para explorar', concept:'Variáveis e tipos', summary:'Guarde um valor. Abra uma possibilidade.', explanation:'Uma variável associa um nome a um valor. let permite criar uma variável cujo valor pode mudar. Números não levam aspas: 100 é um número, "100" é um texto. O mundo lê a variável energia depois da execução.', objective:'Crie uma variável chamada energia com o número 100.', starter:'// Dê energia ao seu explorador.\nlet energia = 0;\n\nconsole.log(energia);', solution:'let energia = 100;\nconsole.log(energia);', hints:['Você precisa guardar um número.','Use let para criar uma variável.','let energia = ____;','let temperatura = 25; guarda um número.','let energia = 100;'], xp:80, minutes:5, tests:['A variável energia existe.','O valor é um número.','A energia é igual a 100.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/let'},
 {id:'ponte', title:'Do outro lado', concept:'Condições if / else', summary:'Uma decisão pode abrir novos caminhos.', explanation:'if executa um bloco somente quando uma condição é verdadeira. O operador >= significa maior ou igual. Uma função pode receber valores diferentes: sua decisão precisa funcionar tanto com energia suficiente quanto com energia baixa.', objective:'Complete atravessar(energia): chame abrirPonte() somente quando energia for maior ou igual a 50.', starter:'function atravessar(energia) {\n  // Tome uma decisão aqui.\n\n}\n\natravessar(80);', solution:'function atravessar(energia) {\n  if (energia >= 50) {\n    abrirPonte();\n  }\n}\n\natravessar(80);', hints:['A ponte deve depender da energia recebida.','Uma condição if compara o valor recebido com 50.','if (energia >= ____) { /* ação */ }','if (temperatura >= 30) { ligarVentilador(); }','function atravessar(energia) {\n  if (energia >= 50) abrirPonte();\n}\natravessar(80);'], xp:100, minutes:8, tests:['A ponte abre com energia 80.','A ponte fica fechada com energia 20.','Casos de fronteira e novos valores funcionam.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/if...else'},
 {id:'jardim', title:'Um jardim de possibilidades', concept:'Repetições com for', summary:'Deixe a repetição fazer o trabalho.', explanation:'Um loop repete um bloco de código. Em for (let i = 0; i < quantidade; i++), i começa em zero, o bloco roda enquanto a condição for verdadeira, e i aumenta em um depois de cada volta. plantar() acrescenta uma árvore ao jardim.', objective:'Escreva cultivar(quantidade) usando um loop para chamar plantar() exatamente quantidade vezes.', starter:'function cultivar(quantidade) {\n  // Uma árvore para cada repetição.\n\n}\n\ncultivar(5);', solution:'function cultivar(quantidade) {\n  for (let i = 0; i < quantidade; i++) {\n    plantar();\n  }\n}\n\ncultivar(5);', hints:['A quantidade de repetições deve vir do parâmetro.','Use for, começando em zero.','for (let i = 0; i < quantidade; i++) { ... }','for (let i = 0; i < 3; i++) { console.log(i); }','function cultivar(quantidade) {\n  for (let i = 0; i < quantidade; i++) plantar();\n}\ncultivar(5);'], xp:120, minutes:8, tests:['Cinco árvores nascem para quantidade 5.','Nenhuma árvore nasce para quantidade 0.','Outras quantidades também funcionam.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Loops_and_iteration'},
 {id:'inventario', title:'Tudo no seu lugar', concept:'Arrays', summary:'Organize os achados da sua jornada.', explanation:'Um array guarda uma sequência de valores. Os itens ficam entre colchetes, separados por vírgulas. O índice começa em zero. A propriedade length informa quantos itens existem. Array.filter() cria uma nova lista com os itens que passam por uma condição.', objective:'Crie selecionar(itens) que retorne apenas os números maiores ou iguais a 10. Use mostrar() para visualizar o resultado.', starter:'function selecionar(itens) {\n  return [];\n}\n\nmostrar(selecionar([4, 12, 7, 20]));', solution:'function selecionar(itens) {\n  return itens.filter(item => item >= 10);\n}\n\nmostrar(selecionar([4, 12, 7, 20]));', hints:['Cada item precisa passar pela mesma comparação.','filter() seleciona elementos de um array.','return itens.filter(item => /* condição */);','numeros.filter(n => n > 0) seleciona valores positivos.','function selecionar(itens) {\n  return itens.filter(item => item >= 10);\n}\nmostrar(selecionar([4, 12, 7, 20]));'], xp:130, minutes:10, tests:['A lista de exemplo resulta em [12, 20].','Uma lista vazia continua vazia.','Valores diferentes e o limite 10 são tratados.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filter'},
 {id:'farol', title:'O farol das funções', concept:'Parâmetros e retorno', summary:'Transforme uma ideia em algo reutilizável.', explanation:'Uma função recebe entradas, processa valores e pode devolver um resultado com return. Esse resultado pode alimentar outras funções. Uma função de cálculo não precisa alterar o mundo diretamente: separar cálculo e efeito facilita os testes.', objective:'Implemente somar(a, b) e use iluminar(somar(40, 60)) para alimentar o farol.', starter:'function somar(a, b) {\n  return 0;\n}\n\niluminar(somar(40, 60));', solution:'function somar(a, b) {\n  return a + b;\n}\n\niluminar(somar(40, 60));', hints:['O resultado depende de duas entradas.','Use + para somar e return para devolver.','return a __ b;','function dobro(n) { return n * 2; }','function somar(a, b) { return a + b; }\niluminar(somar(40, 60));'], xp:150, minutes:8, tests:['O farol recebe energia 100.','A soma funciona com outros números.','Zero e números negativos funcionam.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Functions'},
 {id:'debug', title:'O jardim está quebrado', concept:'Debug boss', summary:'Investigue. Corrija. Faça florescer.', explanation:'Um erro de limite acontece quando um loop executa uma vez a mais ou a menos. Antes de editar, acompanhe os valores de i. Com quantidade 3 e i começando em zero, quantas vezes a condição i <= 3 será verdadeira?', objective:'Corrija cultivar() para plantar exatamente a quantidade pedida, inclusive quando ela for zero.', starter:'function cultivar(quantidade) {\n  for (let i = 0; i <= quantidade; i++) {\n    plantar();\n  }\n}\n\ncultivar(3);', solution:'function cultivar(quantidade) {\n  for (let i = 0; i < quantidade; i++) {\n    plantar();\n  }\n}\n\ncultivar(3);', hints:['Observe a última repetição.','Compare < com <=.','Começando em 0, pare antes de chegar a quantidade.','Para três voltas, os índices são 0, 1 e 2.','Troque i <= quantidade por i < quantidade.'], xp:200, minutes:12, tests:['Três árvores para quantidade 3.','Zero árvores para quantidade 0.','O conserto funciona com novos valores.'], reference:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/for'}
];
export const trails = [
 ['Fundamentos','Seu primeiro código, lógica e resolução de problemas.','8 missões disponíveis','sprout'],
 ['JavaScript','Strings, objetos, funções e o navegador.','Conceitos iniciais disponíveis','braces'],
 ['HTML & CSS','Estruture e dê forma às suas ideias.','Laboratório livre disponível','panels-top-left'],
 ['DOM & APIs','Conecte interfaces e dados do mundo real.','Trilha planejada','network'],
 ['C# & .NET','Construa a lógica por trás das aplicações.','Trilha planejada','terminal'],
 ['Banco de dados','Modele, consulte e conecte informações.','Trilha planejada','database'],
 ['Full stack','Una interface, servidor e persistência.','Trilha planejada','layers'],
 ['Projetos reais','Da primeira página ao seu próprio produto.','2 projetos locais disponíveis','hammer']
];
export const articles = [
 {slug:'variaveis',title:'O que é uma variável?',lead:'Uma variável é um nome associado a um valor que o programa pode utilizar depois.',body:'Use let quando o valor precisar mudar. Use const quando a associação não deve ser reatribuída. Valores numéricos ficam sem aspas; textos ficam entre aspas. O nome deve ajudar outra pessoa a entender o papel do valor.',code:'let energia = 80;\nenergia = energia + 20;\nconst nome = "Ada";',error:'Se você escrever "80" + 20, obterá o texto "8020". Confira o tipo do valor antes de somar.',mission:'energia',source:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Grammar_and_types'},
 {slug:'if-else',title:'Como funciona if / else?',lead:'if escolhe executar um bloco quando uma condição é verdadeira. else oferece um caminho alternativo.',body:'Uma condição normalmente compara valores. >= significa maior ou igual; === compara valor e tipo. Teste sempre valores acima, abaixo e exatamente no limite da sua regra.',code:'if (energia >= 50) {\n  abrirPonte();\n} else {\n  console.log("Recarregue primeiro.");\n}',error:'Usar = em vez de === pode alterar um valor quando você queria compará-lo.',mission:'ponte',source:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/if...else'},
 {slug:'loops',title:'Como funciona um loop for?',lead:'Um loop for repete um bloco enquanto sua condição continuar verdadeira.',body:'A inicialização acontece uma vez. A condição é verificada antes de cada volta. O incremento acontece depois de cada volta. Começando em zero e usando i < 3, os valores de i são 0, 1 e 2.',code:'for (let i = 0; i < 3; i++) {\n  console.log(i);\n}',error:'Uma condição que nunca fica falsa pode criar um loop infinito. O CODELAB interrompe execuções que ultrapassam o limite.',mission:'jardim',source:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Loops_and_iteration'},
 {slug:'undefined',title:'Cannot read properties of undefined',lead:'Esse erro aparece quando você tenta acessar uma propriedade de um valor que está undefined.',body:'Confira de onde o valor deveria vir. Um índice fora do array, uma função sem retorno ou uma resposta ainda não recebida podem resultar em undefined. Verifique o dado antes do acesso; use encadeamento opcional quando a ausência for esperada.',code:'const pessoas = [];\nconst primeira = pessoas[0];\nconsole.log(primeira?.nome ?? "Sem pessoa");',error:'Adicionar ?. em todos os lugares pode esconder um problema de origem. Investigue por que o valor está ausente.',mission:'inventario',source:'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Optional_chaining'}
];
