import { readFile, writeFile, mkdir } from 'node:fs/promises';
import ts from 'typescript';
const content = ts.transpileModule(await readFile('src/content/missions.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const { articles, missions } = await import(`data:text/javascript;base64,${Buffer.from(content).toString('base64')}`);
// Resolve apenas módulos de conteúdo; não executa código de aluno.
const moduleUrls=new Map();
async function contentModule(path){
 if(moduleUrls.has(path))return moduleUrls.get(path);
 const {posix}=await import('node:path');
 let output=ts.transpileModule(await readFile(path,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
 const syntax=ts.createSourceFile(path,output,ts.ScriptTarget.ESNext,true,ts.ScriptKind.JS);
 const specifiers=[];
 const visit=node=>{
  if((ts.isImportDeclaration(node)||ts.isExportDeclaration(node))&&node.moduleSpecifier&&ts.isStringLiteral(node.moduleSpecifier))specifiers.push(node.moduleSpecifier);
  if(ts.isCallExpression(node)&&node.expression.kind===ts.SyntaxKind.ImportKeyword&&node.arguments[0]&&ts.isStringLiteral(node.arguments[0]))specifiers.push(node.arguments[0]);
  ts.forEachChild(node,visit);
 };
 visit(syntax);
 const replacements=[];
 for(const specifier of specifiers){
  if(!specifier.text.startsWith('.'))throw new Error('Dependência de conteúdo não relativa: '+specifier.text);
  const dependency=posix.normalize(posix.join(posix.dirname(path),specifier.text)).replace(/\.js$/,'.ts');
  const target=dependency.endsWith('.ts')?dependency:dependency+'.ts';
  if(!target.startsWith('src/content/'))throw new Error('Importação fora do conteúdo: '+target);
  replacements.push({start:specifier.getStart(syntax),end:specifier.getEnd(),value:JSON.stringify(await contentModule(target))});
 }
 for(const replacement of replacements.sort((a,b)=>b.start-a.start))output=output.slice(0,replacement.start)+replacement.value+output.slice(replacement.end);
 const url='data:text/javascript;base64,'+Buffer.from(output).toString('base64');moduleUrls.set(path,url);return url;
}
const {courses,lessons,resolveLesson}=await import(await contentModule('src/content/curriculum.ts'));
await Promise.all(lessons.map(l=>resolveLesson(l.id)));
const {learningPaths,capstoneProjects}=await import(await contentModule('src/content/project-paths.ts'));
const escape = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin=process.env.CODELAB_PUBLIC_URL?.replace(/\/$/,'');
if(origin && !/^https:\/\/[^/?#]+$/.test(origin))throw new Error('CODELAB_PUBLIC_URL deve ser uma origem HTTPS, sem caminho.');
const styles=`:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#111c15;color:#e9ecdf;font:17px/1.8 system-ui}header,main,footer{max-width:850px;padding:25px;margin:auto}header{display:flex;justify-content:space-between;border-bottom:1px solid #a5b79233}header>a{letter-spacing:3px}a{color:#eac17b}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.25}h1{font-size:clamp(32px,6vw,52px)}h2{margin-top:40px}pre{background:#1d3020;border:1px solid #a5b79233;padding:22px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:15px;border-radius:10px}p{color:#c0cbb9}.eyebrow{letter-spacing:3px;font-size:12px;color:#eac17b}.cta{display:inline-block;padding:12px 22px;background:#eac17b;color:#172319;border-radius:8px;text-decoration:none}nav{display:flex;flex-direction:column;gap:12px}footer{font-size:13px;border-top:1px solid #a5b79233}a:focus-visible{outline:2px solid #eac17b;outline-offset:5px}header{flex-wrap:wrap;gap:16px}main,header,footer{min-width:0}h1,h2,p,a{overflow-wrap:anywhere}@media(max-width:340px){header,main,footer{padding:12px}pre{padding:12px;font-size:13px}}`;
const shell=(title,description,path,body,json)=>`<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} — CODELAB</title><meta name="description" content="${escape(description)}">${origin?`<link rel="canonical" href="${origin}${path}">`:'<meta name="robots" content="noindex">'}<meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="article"><link rel="icon" href="/favicon.svg"><style>${styles}</style><script type="application/ld+json">${JSON.stringify(json).replace(/</g,'\\u003c')}</script></head><body><header><a href="/">CODELAB</a><a href="/#/biblioteca">Biblioteca</a></header><main>${body}</main><footer>Conteúdo original do CODELAB · <a href="/metodologia/">Metodologia e fontes</a> · <a href="/#/aprender">Aprender praticando</a></footer></body></html>`;
const urls=[];
for(const a of articles){const path=`/conceitos/${a.slug}/`;await mkdir(`dist${path}`,{recursive:true});await writeFile(`dist${path}index.html`,shell(a.title,a.lead,path,`<p class="eyebrow">JAVASCRIPT · CONCEITO</p><h1>${a.title}</h1><p>${a.lead}</p><h2>Entenda a ideia</h2><p>${a.body}</p><pre><code>${escape(a.code)}</code></pre><h2>Um erro comum</h2><p>${a.error}</p><a class="cta" href="/#/missao/${a.mission}">Experimente em uma missão →</a><h2>Continue explorando</h2><nav>${articles.filter(x=>x.slug!==a.slug).map(x=>`<a href="/conceitos/${x.slug}/">${x.title}</a>`).join('')}</nav><h2>Referência técnica</h2><p><a href="${a.source}" rel="noopener">MDN Web Docs</a>. Explicação e exemplo de autoria do CODELAB.</p>`,{'@context':'https://schema.org','@type':'LearningResource',name:a.title,description:a.lead,inLanguage:'pt-BR',learningResourceType:'Explicação com exemplo',educationalLevel:'Iniciante'}));urls.push(path);}
await mkdir('dist/metodologia',{recursive:true});await writeFile('dist/metodologia/index.html',shell('Como se aprende no CODELAB','Entenda a metodologia, as fontes e a validação dos exercícios do CODELAB.','/metodologia/',`<p class="eyebrow">SOBRE O CODELAB</p><h1>Aprender fazendo o mundo responder.</h1><p>O CODELAB organiza a aprendizagem em missões: entender, escrever, executar, observar e investigar. Os textos e desafios desta edição foram criados para o projeto e precisam de revisão editorial continuada.</p><h2>Como os exercícios são verificados</h2><p>Cada missão combina exemplos visíveis e casos adicionais. Condições são verificadas em limites; loops são exercitados com zero e múltiplas quantidades. A execução JavaScript acontece em um interpretador isolado, com limites de tempo e memória.</p><h2>Ajuda sem punição</h2><p>Pistas começam no conceito e avançam até uma solução. O histórico registra tentativas e uso de ajuda para orientar revisões, sem descontar recompensas.</p><h2>Fontes e limites desta edição</h2><p>A referência técnica de JavaScript é a <a href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript">MDN Web Docs</a>. O currículo possui ${courses.length} trilhas e ${lessons.length} aulas. As trilhas completas cobrem fundamentos, prática e especialização por linguagem. Exemplos práticos avançam de fundamentos a APIs, C#, ASP.NET Core, SQL e projetos. Revisão pedagógica humana e operação pública continuam sendo trabalhos distintos da publicação do conteúdo.</p><a class="cta" href="/#/aprender">Explorar as missões</a>`,{'@context':'https://schema.org','@type':'AboutPage',name:'Metodologia do CODELAB'}));urls.push('/metodologia/');
await mkdir('dist/aprender-programacao',{recursive:true});await writeFile('dist/aprender-programacao/index.html',shell('Aprender programação praticando','Comece programação com instruções, variáveis, condições, loops, arrays e funções.','/aprender-programacao/',`<p class="eyebrow">COMECE DO ZERO</p><h1>Seu primeiro programa começa com uma instrução.</h1><p>Programar é descrever passos que um computador pode executar. Você escreve instruções, fornece entradas e observa saídas. Quando o resultado não é o esperado, investiga e ajusta o programa.</p><h2>Uma descoberta de cada vez</h2><nav>${missions.map(m=>`<a href="/#/missao/${m.id}">${m.concept}: ${m.title}</a>`).join('')}</nav><h2>Consulte os conceitos</h2><nav>${articles.map(a=>`<a href="/conceitos/${a.slug}/">${a.title}</a>`).join('')}</nav>`,{'@context':'https://schema.org','@type':'Course',name:'Fundamentos da programação',description:'Oito missões introdutórias de programação.',provider:{'@type':'Organization',name:'CODELAB'},inLanguage:'pt-BR'}));urls.push('/aprender-programacao/');
for(const lesson of lessons){const path=`/aulas/${lesson.id}/`;await mkdir(`dist${path}`,{recursive:true});const capitulos=lesson.capitulos.map((cap,i)=>`<section id="aula-${escape(cap.id)}"><p class="eyebrow">CAPÍTULO ${String(i+1).padStart(2,'0')} · ${escape(cap.subtitulo)}</p><h2>${escape(cap.titulo)}</h2>${cap.id.startsWith('resolucao-')?'<details><summary>Mostrar a solução deste problema</summary>':''}${cap.paragrafos.map(p=>`<p>${escape(p)}</p>`).join('')}${cap.pontos?.length?`<ol>${cap.pontos.map(p=>`<li>${escape(p)}</li>`).join('')}</ol>`:''}${cap.codigo?`<pre><code>${escape(cap.codigo)}</code></pre>`:''}${cap.id.startsWith('resolucao-')?'</details>':''}</section>`).join('');await writeFile(`dist${path}index.html`,shell(lesson.title,lesson.body.slice(0,155),path,`<p class="eyebrow">${escape(courses.find(c=>c.id===lesson.track).title)} · ESTUDO PROFUNDO</p><h1>${escape(lesson.title)}</h1><p>${escape(lesson.body)}</p>${capitulos}<h2>Verifique sua compreensão</h2><p>${escape(lesson.question)}</p><a class="cta" href="/#/aula/${lesson.id}">Responder, praticar e salvar progresso →</a><p><a href="${lesson.source}">Referência técnica</a></p>`,{'@context':'https://schema.org','@type':'LearningResource',name:lesson.title,description:lesson.body,inLanguage:'pt-BR',learningResourceType:'Aula aprofundada com prática guiada',educationalLevel:'Do iniciante à aplicação'}));urls.push(path);}

for(const path of learningPaths){
 const url='/percursos/'+path.id+'/';await mkdir('dist'+url,{recursive:true});
 const body='<p class="eyebrow">PERCURSO PRÁTICO</p><h1>'+escape(path.title)+'</h1><p>'+escape(path.description)+'</p>'+path.stages.map(stage=>'<section><h2>'+escape(stage.title)+'</h2>'+stage.theory.map(p=>'<p>'+escape(p)+'</p>').join('')+'<pre>'+escape(stage.example)+'</pre><h3>Investigue</h3><p>'+escape(stage.bug)+'</p><h3>Construa</h3><p>'+escape(stage.exercise)+'</p><ul>'+stage.checkpoints.map(c=>'<li>'+escape(c)+'</li>').join('')+'</ul><details><summary>Consultar solução</summary><pre>'+escape(stage.solution)+'</pre><p>'+escape(stage.explanation)+'</p></details></section>').join('')+'<a class="cta" href="/#/percurso/'+path.id+'">Praticar e conferir decisões</a>';
 await writeFile('dist'+url+'index.html',shell(path.title,path.description,url,body,{'@context':'https://schema.org','@type':'LearningResource',name:path.title,inLanguage:'pt-BR'}));urls.push(url);
}
for(const project of capstoneProjects){
 const url='/projetos/'+project.id+'/';await mkdir('dist'+url,{recursive:true});
 const body='<p class="eyebrow">PROJETO DE CONCLUSÃO</p><h1>'+escape(project.title)+'</h1><p>'+escape(project.summary)+'</p><h2>Ambiente e limites</h2><p>'+escape(project.offline)+'</p><ul>'+[...project.scope,...project.constraints].map(s=>'<li>'+escape(s)+'</li>').join('')+'</ul>'+project.milestones.map(m=>'<section><h2>'+escape(m.title)+'</h2><p>'+escape(m.goal)+'</p><h3>Entregáveis</h3><ul>'+m.deliverables.map(s=>'<li>'+escape(s)+'</li>').join('')+'</ul><h3>Critérios de revisão</h3><ul>'+m.criteria.map(c=>'<li>'+escape(c.label)+'</li>').join('')+'</ul><h3>Testes e diagnóstico</h3><ul>'+m.tests.map(s=>'<li>'+escape(s)+'</li>').join('')+'</ul><p>'+escape(m.diagnosis)+'</p><p>'+escape(m.transfer)+'</p></section>').join('')+'<p>O projeto aberto é revisado por rubrica manual; não recebe aprovação automática.</p><a class="cta" href="/#/projeto/'+project.id+'">Criar e salvar meu projeto</a>';
 await writeFile('dist'+url+'index.html',shell(project.title,project.summary,url,body,{'@context':'https://schema.org','@type':'LearningResource',name:project.title,inLanguage:'pt-BR'}));urls.push(url);
}

await writeFile('dist/robots.txt',origin?`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${origin?urls.map(path=>`<url><loc>${origin}${path}</loc></url>`).join(''):''}</urlset>`);
await mkdir('server/Content',{recursive:true});await writeFile('server/Content/curriculum.json',JSON.stringify({missions:missions.map(({solution,...m})=>m),trails:courses,lessons,articles},null,2));
console.log(`Pré-renderização concluída: ${urls.length} páginas educacionais. ${origin?'Indexação configurada.':'Indexação desativada até definir CODELAB_PUBLIC_URL.'}`);
