import type {Course,Lesson} from '../curriculum';
import {materialize,type DeepCourse} from './types';
export const expandedCourses:Course[]=[
  {
    "id": "python-completo",
    "title": "Python · do zero ao avançado",
    "description": "Tipos, coleções, funções, objetos, biblioteca padrão, concorrência e engenharia de projetos.",
    "icon": "file-code-2",
    "lessonIds": [
      "py-fundamentos",
      "py-colecoes-funcoes",
      "py-objetos-protocolos",
      "py-biblioteca-dados",
      "py-concorrencia",
      "py-engenharia"
    ]
  },
  {
    "id": "typescript-completo",
    "title": "TypeScript · do zero ao avançado",
    "description": "JavaScript tipado, narrowing, contratos, genéricos, tipos avançados e integração com dados reais.",
    "icon": "braces",
    "lessonIds": [
      "ts-fundamentos",
      "ts-contratos",
      "ts-genericos",
      "ts-tipos-avancados",
      "ts-modulos-configuracao",
      "ts-fronteiras-qualidade"
    ]
  },
  {
    "id": "cpp-completo",
    "title": "C++ · do zero ao avançado",
    "description": "Compilação, tipos, funções, RAII, STL, templates, memória, concorrência e desempenho.",
    "icon": "file-code-2",
    "lessonIds": [
      "cpp-fundamentos",
      "cpp-classes-raii",
      "cpp-stl-algoritmos",
      "cpp-templates",
      "cpp-memoria-posse",
      "cpp-concorrencia-engenharia"
    ]
  },
  {
    "id": "javascript-completo",
    "title": "JavaScript · fundamentos à especialização",
    "description": "Semântica da linguagem, funções, objetos, coleções, assíncrono, módulos e engenharia.",
    "icon": "braces",
    "lessonIds": [
      "js-semantica",
      "js-funcoes-this",
      "js-objetos-modelos",
      "js-colecoes-iteracao",
      "js-assincrono",
      "js-modulos-engenharia"
    ]
  },
  {
    "id": "html-completo",
    "title": "HTML · do zero à plataforma web",
    "description": "Documentos semânticos, texto, formulários, mídia, acessibilidade e integração com o navegador.",
    "icon": "file-code-2",
    "lessonIds": [
      "html-documentos",
      "html-texto-links",
      "html-formularios",
      "html-midia",
      "html-acessibilidade",
      "html-plataforma"
    ]
  },
  {
    "id": "css-completo",
    "title": "CSS · do zero ao avançado",
    "description": "Cascata, caixas, Flexbox, Grid, responsividade, tipografia, movimento e arquitetura de estilos.",
    "icon": "layers",
    "lessonIds": [
      "css-cascata",
      "css-caixas",
      "css-flex-grid",
      "css-responsivo",
      "css-visual-movimento",
      "css-arquitetura"
    ]
  },
  {
    "id": "csharp-completo",
    "title": "C# · do zero à engenharia",
    "description": "Tipos, coleções, LINQ, orientação a objetos, assíncrono, runtime e projetos .NET.",
    "icon": "braces",
    "lessonIds": [
      "cs-tipos-controle",
      "cs-colecoes-linq",
      "cs-objetos-contratos",
      "cs-assincrono-recursos",
      "cs-runtime-avancado",
      "cs-engenharia"
    ]
  },
  {
    "id": "sql-completo",
    "title": "SQL · do zero ao avançado",
    "description": "Modelagem relacional, consultas, janelas, transações, índices e engenharia com PostgreSQL.",
    "icon": "database",
    "lessonIds": [
      "sql-modelagem-completa",
      "sql-consultas-joins",
      "sql-agregacoes-janelas",
      "sql-transacoes",
      "sql-indices-planos",
      "sql-esquema-avancado"
    ]
  }
];
export const expandedLessons:Lesson[]=[
  {
    "id": "py-fundamentos",
    "track": "python-completo",
    "title": "Python: execução, tipos e controle",
    "body": "Construa seu primeiro programa Python entendendo a execução do arquivo, a indentação e a relação entre nomes e objetos. Estude números, strings, booleanos, conversões, entrada e saída, decisões, repetição e os casos de limite que distinguem um programa previsível de um exemplo que só funciona com uma entrada.",
    "level": "Fundamentos",
    "topics": [
      "interpretador e REPL",
      "indentação",
      "int float bool None",
      "str e Unicode",
      "conversões e entrada",
      "if elif else",
      "for range while",
      "break continue else",
      "comparação e identidade"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-colecoes-funcoes",
    "track": "python-completo",
    "title": "Python: coleções, funções e iteração",
    "body": "Aprenda a escolher list, tuple, dict e set pelo contrato dos dados, escrever funções com parâmetros claros e percorrer coleções sem modificar acidentalmente seus elementos. Conecte fatiamento, comprehensions, desempacotamento, escopo, closures, iteradores e geradores a problemas de transformação e agregação.",
    "level": "Intermediário",
    "topics": [
      "list tuple dict set",
      "mutabilidade e cópia",
      "slicing e desempacotamento",
      "comprehensions",
      "parâmetros posicionais e nomeados",
      "args kwargs",
      "escopo LEGB closures",
      "iteradores e yield",
      "complexidade"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-objetos-protocolos",
    "track": "python-completo",
    "title": "Python: classes, protocolos e metaprogramação",
    "body": "Modele objetos por responsabilidades e contratos, usando classes, dataclasses, propriedades e composição. Entenda o sistema de atributos, métodos especiais, herança, super, protocolos, decoradores e context managers para criar APIs previsíveis, sem recorrer a mecanismos avançados quando uma função simples resolve o problema.",
    "level": "Avançado",
    "topics": [
      "classes instâncias self",
      "dataclasses",
      "herança composição MRO super",
      "property descritores",
      "dunder repr eq hash",
      "duck typing protocolos",
      "decoradores functools.wraps",
      "context managers",
      "slots metaclasses"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-biblioteca-dados",
    "track": "python-completo",
    "title": "Python: arquivos, exceções e biblioteca padrão",
    "body": "Aprenda a trabalhar com recursos reais usando pathlib, arquivos Unicode, JSON, CSV, datas, expressões regulares e coleções especializadas. Estabeleça fronteiras de validação, trate exceções específicas e escreva arquivos com uma estratégia que não deixe resultados parciais silenciosamente.",
    "level": "Intermediário",
    "topics": [
      "pathlib arquivos encoding",
      "with e exceções",
      "JSON CSV validação",
      "datetime zoneinfo",
      "decimal fractions",
      "collections itertools functools",
      "re Unicode",
      "logging argparse",
      "os subprocess segurança"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-concorrencia",
    "track": "python-completo",
    "title": "Python: concorrência, async e paralelismo",
    "body": "Distinga concorrência de paralelismo e escolha entre asyncio, threads e processos pelo tipo de trabalho. Estude corrotinas, tarefas, cancelamento, limites, filas, sincronização, tratamento de falhas e o impacto do runtime, evitando supor que escrever async torna uma operação bloqueante automaticamente assíncrona.",
    "level": "Avançado",
    "topics": [
      "concorrência versus paralelismo",
      "async await corrotinas",
      "TaskGroup cancelamento",
      "timeouts semáforos filas",
      "threads locks",
      "ProcessPoolExecutor",
      "GIL builds free-threaded",
      "backpressure",
      "falhas e recursos"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-engenharia",
    "track": "python-completo",
    "title": "Python: tipagem, testes, pacotes e desempenho",
    "body": "Transforme scripts em projetos reproduzíveis, com ambientes isolados, módulos bem delimitados, anotação de tipos, testes úteis e medição de desempenho. Aprenda a documentar contratos e distribuir pacotes, relacionando ferramentas de engenharia às falhas que elas realmente conseguem detectar.",
    "level": "Especialização",
    "topics": [
      "módulos imports __main__",
      "venv pip pyproject.toml",
      "typing Protocol Generic",
      "testes unittest mocks",
      "propriedades casos de borda",
      "profiling timeit tracemalloc",
      "algoritmos complexidade",
      "distribuição wheels",
      "documentação e evolução"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-fundamentos",
    "track": "typescript-completo",
    "title": "TypeScript: tipos, inferência e execução",
    "body": "Entenda o que TypeScript verifica antes da execução e o que permanece responsabilidade do JavaScript. Aprenda inferência, tipos primitivos, arrays, tuplas, literal types, uniões, null e undefined, distinguindo erros do compilador de validação dos dados que chegam durante a execução.",
    "level": "Fundamentos",
    "topics": [
      "tsc e apagamento de tipos",
      "inferência",
      "string number boolean",
      "arrays readonly tuples",
      "literal types unions",
      "strictNullChecks",
      "unknown versus any",
      "type assertions satisfies"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-contratos",
    "track": "typescript-completo",
    "title": "TypeScript: objetos, narrowing e uniões discriminadas",
    "body": "Descreva modelos com type e interface, compreenda tipagem estrutural e refine valores por controle de fluxo. Use uniões discriminadas para representar estados possíveis e impossíveis, mantendo decisões exaustivas e evitando objetos cheios de propriedades opcionais cuja combinação não tem significado.",
    "level": "Intermediário",
    "topics": [
      "type interface tipagem estrutural",
      "optional readonly",
      "excess property checks",
      "typeof in instanceof",
      "type predicates assertions",
      "discriminated unions",
      "never exhaustiveness",
      "intersections index signatures"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-genericos",
    "track": "typescript-completo",
    "title": "TypeScript: genéricos, coleções e variância",
    "body": "Use genéricos para preservar relações entre tipos de entrada e saída, imponha constraints proporcionais ao que a função realmente usa e componha funções sem apagar informações com any. Explore keyof, indexed access, overloads, parâmetros padrão, callbacks e os cuidados de variância em coleções mutáveis.",
    "level": "Avançado",
    "topics": [
      "generic functions interfaces",
      "constraints extends",
      "keyof indexed access",
      "defaults inference",
      "overloads",
      "callbacks variance",
      "readonly collections",
      "generic classes factories"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-tipos-avancados",
    "track": "typescript-completo",
    "title": "TypeScript: transformação e programação de tipos",
    "body": "Explore mapped types, conditional types, infer e template literal types como ferramentas para derivar contratos de uma fonte comum. Entenda distribuição sobre uniões, utilitários e limites de legibilidade, evitando tornar o sistema de tipos um programa complexo que a equipe não consegue manter.",
    "level": "Avançado",
    "topics": [
      "mapped types modifiers",
      "Pick Omit Partial Required Readonly",
      "Record Exclude Extract",
      "conditional types distribution",
      "infer ReturnType Parameters Awaited",
      "template literal types",
      "key remapping",
      "recursive types limits"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-modulos-configuracao",
    "track": "typescript-completo",
    "title": "TypeScript: módulos, configuração e declarações",
    "body": "Configure TypeScript de acordo com o ambiente onde o JavaScript será executado. Aprenda target, lib, module, moduleResolution, strict, arquivos de declaração e organização de bibliotecas, distinguindo suporte de sintaxe, disponibilidade de APIs e resolução real de arquivos.",
    "level": "Especialização",
    "topics": [
      "tsconfig strict",
      "target lib module",
      "NodeNext bundler resolution",
      "ESM CommonJS",
      "import type verbatimModuleSyntax",
      "declaration d.ts",
      "ambient declarations",
      "project references",
      "source maps packaging"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-fronteiras-qualidade",
    "track": "typescript-completo",
    "title": "TypeScript: validação, assíncrono e qualidade",
    "body": "Conecte contratos estáticos a dados recebidos por JSON, formulários e APIs, usando validação explícita e resultados discriminados. Explore promises, cancelamento, testes de tipos e execução, arquitetura de fronteiras e migração gradual de JavaScript sem esconder problemas com casts e any.",
    "level": "Especialização",
    "topics": [
      "JSON unknown validation",
      "Result discriminated unions",
      "Promise async errors",
      "AbortController",
      "static versus runtime tests",
      "ts-expect-error",
      "gradual migration checkJs JSDoc",
      "domain DTO boundaries",
      "security and serialization"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-fundamentos",
    "track": "cpp-completo",
    "title": "C++: compilação, tipos e controle",
    "body": "Aprenda a transformar arquivos C++ em um programa executável, compreender diagnósticos de compilação e estabelecer contratos de tipos e entrada. Estude inicialização, conversões, expressões, decisões, repetição e funções, reconhecendo desde o início os limites dos números e o perigo de comportamento indefinido.",
    "level": "Fundamentos",
    "topics": [
      "compilação ligação main",
      "headers namespaces",
      "tipos fundamentais auto",
      "inicialização narrowing",
      "signed unsigned overflow",
      "if switch loops",
      "funções parâmetros retorno",
      "const constexpr",
      "entrada e streams"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-classes-raii",
    "track": "cpp-completo",
    "title": "C++: classes, RAII e semântica de valor",
    "body": "Projete classes que estabelecem invariantes na construção e liberam recursos automaticamente. Aprenda encapsulamento, construtores, destrutores, cópia, movimento, rule of zero, composição e polimorfismo, distinguindo objetos que representam valores daqueles que controlam a posse de um recurso.",
    "level": "Intermediário",
    "topics": [
      "struct class encapsulamento",
      "constructors invariants",
      "RAII destructors",
      "rule of zero five",
      "copy move semantics",
      "composition inheritance",
      "virtual destructor slicing",
      "exceptions guarantees",
      "explicit const methods"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-stl-algoritmos",
    "track": "cpp-completo",
    "title": "C++: STL, iteradores, algoritmos e ranges",
    "body": "Escolha contêineres pela forma de acesso, conheça invalidação de iteradores e substitua laços frágeis por algoritmos com contratos claros. Estude vector, array, map, unordered_map, set, lambdas, comparadores, ranges e complexidade para transformar dados preservando segurança e previsibilidade.",
    "level": "Intermediário",
    "topics": [
      "vector array deque list",
      "map set unordered_map",
      "iterator categories invalidation",
      "algorithms sort find accumulate",
      "lambdas captures",
      "comparators strict weak ordering",
      "ranges views lifetime",
      "complexity"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-templates",
    "track": "cpp-completo",
    "title": "C++: templates, concepts e avaliação constante",
    "body": "Crie algoritmos genéricos com requisitos explícitos, entenda instanciação e diagnósticos de templates e use concepts para expressar capacidades. Explore dedução, overloads, constexpr, if constexpr, variádicos e type traits, mantendo a abstração proporcional às necessidades do código.",
    "level": "Avançado",
    "topics": [
      "function class templates",
      "deduction instantiation",
      "concepts requires",
      "constraints overloads",
      "if constexpr type_traits",
      "variadic templates folds",
      "constexpr consteval",
      "specialization ODR headers"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-memoria-posse",
    "track": "cpp-completo",
    "title": "C++: memória, posse e segurança de vida",
    "body": "Entenda duração de armazenamento, vida de objetos, ponteiros, referências e categorias de valor para evitar acessos pendentes. Use unique_ptr, shared_ptr, weak_ptr, span, string_view, optional e variant com contratos explícitos de posse, reconhecendo custos e condições de validade.",
    "level": "Avançado",
    "topics": [
      "storage duration lifetime",
      "pointers references nullptr",
      "unique_ptr shared_ptr weak_ptr",
      "ownership cycles",
      "span string_view dangling",
      "value categories move forwarding",
      "optional variant visit",
      "alignment allocation placement",
      "sanitizers UB"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-concorrencia-engenharia",
    "track": "cpp-completo",
    "title": "C++: concorrência, build e desempenho",
    "body": "Aprenda a organizar trabalho concorrente e medir desempenho sem comprometer correção. Estude threads, jthread, sincronização, atomics, futures e cancelamento, conectando o modelo de memória a testes, sanitizers, sistemas de build, unidades de tradução e escolhas de arquitetura.",
    "level": "Especialização",
    "topics": [
      "thread jthread stop_token",
      "mutex scoped_lock condition_variable",
      "atomics memory ordering",
      "data races deadlocks",
      "future async",
      "build headers CMake modules",
      "profiling benchmarks",
      "cache locality false sharing",
      "coroutines custom awaitables"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-semantica",
    "track": "javascript-completo",
    "title": "JavaScript: valores, coerção e escopo",
    "body": "Consolide o modelo de execução de JavaScript, distinguindo valores primitivos, referências a objetos, coerção e escopo. Estude operadores, números, strings Unicode, comparação, destructuring e closures para prever programas com precisão, inclusive nos casos em que a sintaxe parece simples mas o resultado surpreende.",
    "level": "Fundamentos",
    "topics": [
      "primitives objects typeof",
      "Number BigInt NaN",
      "Unicode strings",
      "coercion equality Object.is",
      "truthiness nullish",
      "let const var TDZ",
      "destructuring rest spread",
      "closures lexical scope"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-funcoes-this",
    "track": "javascript-completo",
    "title": "JavaScript: funções, this e composição",
    "body": "Estude declarações, expressões, arrow functions, callbacks e closures como formas de criar e combinar comportamento. Entenda como this é escolhido por uma chamada, como bind, call e apply alteram esse contexto e como funções puras ajudam a testar regras sem efeitos externos.",
    "level": "Intermediário",
    "topics": [
      "declaration expression arrow",
      "parameters defaults rest",
      "this call apply bind",
      "lexical this",
      "higher-order functions",
      "closures callbacks",
      "pure functions composition",
      "recursion stack tail calls"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-objetos-modelos",
    "track": "javascript-completo",
    "title": "JavaScript: objetos, protótipos e classes",
    "body": "Entenda acesso a propriedades, identidade, descritores e cadeia de protótipos antes de usar classes. Explore encapsulamento com campos privados, composição, herança, getters, symbols, Proxy e Reflect, mantendo validação e políticas de dados distintas dos mecanismos da linguagem.",
    "level": "Avançado",
    "topics": [
      "property keys descriptors",
      "own versus inherited",
      "prototype chain",
      "classes constructors private fields",
      "getters setters",
      "composition inheritance super",
      "symbols",
      "Proxy Reflect",
      "prototype pollution boundaries"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-colecoes-iteracao",
    "track": "javascript-completo",
    "title": "JavaScript: coleções, iteradores e memória",
    "body": "Escolha arrays, Map, Set e coleções fracas segundo o contrato, e use iteradores e geradores para processar sequências com controle de memória. Estude mutabilidade, ordenação, typed arrays, buffers, expressões regulares, internacionalização e gestão de recursos, respeitando as APIs disponíveis em cada runtime.",
    "level": "Avançado",
    "topics": [
      "arrays sparse map filter reduce sort",
      "Map Set identity",
      "WeakMap WeakSet GC",
      "iterators generators yield",
      "typed arrays ArrayBuffer DataView",
      "RegExp Unicode",
      "Intl formatting segmentation",
      "resource lifetime dispose",
      "memory leaks"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-assincrono",
    "track": "javascript-completo",
    "title": "JavaScript: promises, concorrência e cancelamento",
    "body": "Entenda event loop, microtasks, promises e async/await para coordenar trabalho sem perder erros ou atualizar uma interface com resultados antigos. Estude combinações, limites de concorrência, cancelamento, timeouts e idempotência, distinguindo tarefas de JavaScript de APIs oferecidas pelo ambiente.",
    "level": "Avançado",
    "topics": [
      "event loop jobs microtasks",
      "Promise states chaining",
      "async await rejection",
      "all allSettled race any",
      "bounded concurrency",
      "AbortController host APIs",
      "timeouts stale responses",
      "idempotency retry backoff"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-modulos-engenharia",
    "track": "javascript-completo",
    "title": "JavaScript: módulos, testes e arquitetura",
    "body": "Organize programas JavaScript em módulos e fronteiras, usando testes, validação e medição para evoluir com confiança. Estude imports, exports, dependências, ambientes, tratamento de erros, serialização, segurança e observação, relacionando ferramentas à correção dos fluxos completos.",
    "level": "Especialização",
    "topics": [
      "ES modules live bindings",
      "dynamic import top-level await",
      "cycles CommonJS hosts",
      "errors causes boundaries",
      "JSON structured clone",
      "unit integration e2e",
      "dependency injection",
      "performance profiling",
      "security DOM SQL boundaries"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-documentos",
    "track": "html-completo",
    "title": "HTML: documento, árvore e semântica",
    "body": "Aprenda como HTML descreve um documento e como o navegador transforma sua fonte em uma árvore DOM. Estude estrutura, metadados, elementos semânticos, atributos globais e regras de parsing para construir páginas que funcionam sem depender da aparência ou de scripts para transmitir seu significado.",
    "level": "Fundamentos",
    "topics": [
      "doctype html head body",
      "DOM parsing nesting",
      "lang charset viewport",
      "title meta link",
      "main header nav section article aside footer",
      "global attributes id class data",
      "boolean attributes",
      "void elements entities namespaces"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-texto-links",
    "track": "html-completo",
    "title": "HTML: texto, links, listas e tabelas",
    "body": "Estruture informação para leitura e navegação, usando títulos, parágrafos, ênfase, citações, código, listas e tabelas de dados. Aprenda URLs, fragmentos, caminhos e nomes acessíveis de links, preservando relações que continuam claras sem a disposição visual da página.",
    "level": "Fundamentos",
    "topics": [
      "headings paragraphs emphasis",
      "strong em mark small",
      "blockquote cite q",
      "pre code whitespace",
      "ol ul dl",
      "URLs relative absolute fragments",
      "a download target rel",
      "tables caption th scope"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-formularios",
    "track": "html-completo",
    "title": "HTML: formulários, validação e dados enviados",
    "body": "Construa formulários com controles nativos, rótulos, grupos e instruções compreensíveis. Entenda name, value, tipos de input, submissão, validação de restrições, FormData e acessibilidade, sem confundir validação do navegador com confiança nos dados recebidos por um sistema.",
    "level": "Intermediário",
    "topics": [
      "form action method",
      "label name value",
      "input types textarea select",
      "checkbox radio fieldset legend",
      "required min max step pattern",
      "autocomplete inputmode",
      "constraint validation",
      "FormData successful controls",
      "client server validation"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-midia",
    "track": "html-completo",
    "title": "HTML: imagens, mídia e conteúdo incorporado",
    "body": "Inclua imagens, áudio, vídeo, gráficos e documentos externos com alternativas e políticas claras. Estude alt, dimensões, imagens responsivas, captions, controles, SVG, canvas e sandbox, reconhecendo que uma mídia visível não garante informação acessível nem um recurso seguro.",
    "level": "Intermediário",
    "topics": [
      "img alt width height",
      "srcset sizes picture",
      "figure figcaption",
      "audio video source track",
      "captions transcripts autoplay",
      "SVG canvas alternatives",
      "iframe title sandbox permissions",
      "lazy loading performance"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-acessibilidade",
    "track": "html-completo",
    "title": "HTML: acessibilidade e interação nativa",
    "body": "Implemente interações que respeitam teclado, foco e nomes acessíveis, usando elementos nativos antes de criar widgets complexos. Estude botões, links, details, dialog, popover, live regions e ARIA, verificando o comportamento completo em vez de confiar apenas na presença de atributos.",
    "level": "Avançado",
    "topics": [
      "keyboard focus tabindex",
      "button versus link",
      "accessible names descriptions",
      "details summary",
      "dialog modal focus return",
      "popover support",
      "ARIA states relationships",
      "live regions",
      "progressive enhancement"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-plataforma",
    "track": "html-completo",
    "title": "HTML: DOM, componentes e integração da plataforma",
    "body": "Conecte documentos a comportamento usando DOM e eventos, preservando conteúdo seguro e melhoria progressiva. Estude templates, custom elements, Shadow DOM, armazenamento, políticas de origem, workers e APIs do navegador, mantendo clara a diferença entre HTML, JavaScript e capacidades do ambiente.",
    "level": "Especialização",
    "topics": [
      "DOM createElement textContent",
      "events propagation delegation",
      "template document fragments",
      "custom elements lifecycle",
      "Shadow DOM slots",
      "storage origin sandbox",
      "fetch workers host APIs",
      "CSP same-origin permissions",
      "SEO progressive enhancement"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-cascata",
    "track": "css-completo",
    "title": "CSS: seletores, cascata e valores",
    "body": "Aprenda a prever qual declaração CSS vence e por que um valor chega ao elemento. Estude seletores, herança, especificidade, ordem, camadas, custom properties e unidades, usando o painel de estilos como ferramenta de diagnóstico em vez de acumular !important a cada conflito.",
    "level": "Fundamentos",
    "topics": [
      "selectors combinators attributes",
      "pseudo classes elements",
      "cascade origin importance layers",
      "specificity source order",
      "inherit initial unset revert",
      "custom properties var fallback",
      "computed used values",
      "relative absolute units"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-caixas",
    "track": "css-completo",
    "title": "CSS: caixas, fluxo e posicionamento",
    "body": "Entenda como conteúdo, padding, borda e margem formam caixas e como elas participam do fluxo. Estude box-sizing, display, dimensões intrínsecas, overflow, colapso de margens, posicionamento e stacking contexts para diagnosticar cortes e sobreposições sem depender de ajustes aleatórios.",
    "level": "Fundamentos",
    "topics": [
      "box model box-sizing",
      "block inline inline-block",
      "normal flow intrinsic sizing",
      "margin collapse",
      "overflow scroll clipping",
      "position relative absolute fixed sticky",
      "containing blocks",
      "stacking context z-index",
      "logical properties writing modes"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-flex-grid",
    "track": "css-completo",
    "title": "CSS: Flexbox, Grid e alinhamento",
    "body": "Escolha Flexbox ou Grid pela relação entre itens e espaço, compreendendo eixos, tamanhos, distribuição e ordem. Estude tracks, fr, minmax, auto-fit, alinhamento e subgrid, preservando a sequência do documento e tratando o tamanho mínimo do conteúdo para evitar layouts frágeis.",
    "level": "Intermediário",
    "topics": [
      "flex axes wrap basis grow shrink",
      "alignment gap auto margins",
      "flex min-size",
      "grid tracks fr minmax",
      "auto-fit auto-fill",
      "explicit implicit placement",
      "grid areas subgrid",
      "source order accessibility"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-responsivo",
    "track": "css-completo",
    "title": "CSS: responsividade, consultas e dimensões fluidas",
    "body": "Projete componentes que se adaptam ao espaço, texto e preferências do usuário. Aprenda media queries, container queries, clamp, unidades de viewport, imagens responsivas e estratégias de reflow, escolhendo pontos de mudança a partir do conteúdo em vez de uma lista fixa de aparelhos.",
    "level": "Avançado",
    "topics": [
      "media queries content breakpoints",
      "container queries inline-size",
      "clamp min max calc",
      "viewport svh lvh dvh",
      "reflow zoom text",
      "responsive images aspect-ratio",
      "prefers-color-scheme reduced-motion",
      "pointer hover capabilities"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-visual-movimento",
    "track": "css-completo",
    "title": "CSS: tipografia, cor e movimento",
    "body": "Trabalhe com apresentação visual sem perder legibilidade, contraste e controle do usuário. Estude tipografia, fontes, cores, fundos, gradientes, transformações, transições e animações, compreendendo custos de renderização e o uso de preferências para reduzir movimento desnecessário.",
    "level": "Avançado",
    "topics": [
      "font stacks web fonts loading",
      "line-height measure text",
      "color contrast modern color spaces",
      "background gradients borders shadows",
      "transforms transitions",
      "keyframes animation timing",
      "reduced motion",
      "render layout paint composite"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-arquitetura",
    "track": "css-completo",
    "title": "CSS: arquitetura, compatibilidade e depuração",
    "body": "Organize estilos para evoluir um produto sem conflitos crescentes, usando tokens, componentes, camadas e regras claras. Estude suporte de recursos, @supports, escopo, estratégias de fallback e testes de produção, relacionando manutenção, acessibilidade e desempenho à experiência que o usuário realmente percorre.",
    "level": "Especialização",
    "topics": [
      "tokens themes component APIs",
      "layers scope naming",
      "supports progressive enhancement",
      "compatibility fallback",
      "contain content-visibility",
      "logical properties internationalization",
      "DevTools computed layout",
      "visual regression states",
      "dead CSS maintenance"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-tipos-controle",
    "track": "csharp-completo",
    "title": "C#: tipos, valores e controle de fluxo",
    "body": "Compreenda o papel de C# e do runtime .NET, escreva programas com contratos explícitos e diferencie tipos por valor e por referência. Estude números, texto, nullable, conversões, decisões, repetição e tratamento de erros, incluindo limites que a compilação não resolve automaticamente.",
    "level": "Fundamentos",
    "topics": [
      "dotnet project build runtime",
      "value reference types",
      "int long double decimal",
      "checked conversions",
      "string char Unicode",
      "nullable reference value types",
      "if switch pattern matching",
      "loops methods parameters",
      "exceptions contracts"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-colecoes-linq",
    "track": "csharp-completo",
    "title": "C#: genéricos, coleções e LINQ",
    "body": "Escolha coleções e use genéricos para preservar contratos, depois transforme dados com LINQ entendendo avaliação adiada e materialização. Estude IEnumerable, listas, dicionários, conjuntos, agrupamento, ordenação e IQueryable, reconhecendo quando uma expressão vira trabalho local ou uma consulta de outro provedor.",
    "level": "Intermediário",
    "topics": [
      "List Dictionary HashSet",
      "generic constraints variance",
      "IEnumerable IEnumerator",
      "LINQ Where Select OrderBy GroupBy",
      "deferred execution materialization",
      "First Single Any",
      "IQueryable providers",
      "complexity multiple enumeration"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-objetos-contratos",
    "track": "csharp-completo",
    "title": "C#: objetos, interfaces, records e padrões",
    "body": "Modele regras com encapsulamento e interfaces, usando composição, records, herança e pattern matching conforme o contrato. Entenda igualdade, imutabilidade, delegates e eventos para criar componentes testáveis sem hierarquias artificiais ou estado interno exposto.",
    "level": "Avançado",
    "topics": [
      "classes structs records",
      "constructors properties init required",
      "interfaces composition inheritance",
      "virtual override abstract sealed",
      "value equality record copying",
      "pattern matching switch",
      "delegates lambdas events",
      "operator overload contracts"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-assincrono-recursos",
    "track": "csharp-completo",
    "title": "C#: async, cancelamento e recursos",
    "body": "Organize operações assíncronas com Task, await e cancelamento cooperativo, mantendo propagação de falhas e liberação de recursos. Estude composição, limites, IDisposable, IAsyncDisposable, streams assíncronos e o risco de bloquear uma operação assíncrona com Result ou Wait.",
    "level": "Avançado",
    "topics": [
      "Task async await",
      "Task.WhenAll WhenAny",
      "CancellationToken cooperative",
      "timeouts bounded concurrency",
      "IDisposable using",
      "IAsyncDisposable await using",
      "IAsyncEnumerable await foreach",
      "async void contexts",
      "deadlocks Result Wait"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-runtime-avancado",
    "track": "csharp-completo",
    "title": "C#: runtime, memória e recursos avançados",
    "body": "Estude recursos avançados a partir de um problema medido: boxing, structs, spans, memória, delegates, reflection, attributes, source generators e interoperabilidade. Relacione esses mecanismos a custos e contratos de vida, evitando trocar clareza por uma otimização sem evidência.",
    "level": "Avançado",
    "topics": [
      "GC allocations boxing",
      "struct readonly ref struct",
      "Span ReadOnlySpan Memory",
      "stackalloc lifetime",
      "generics constraints",
      "reflection attributes",
      "source generators trimming AOT",
      "unsafe pointers interop",
      "profiling benchmarking"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-engenharia",
    "track": "csharp-completo",
    "title": "C#: testes, pacotes e arquitetura .NET",
    "body": "Evolua exemplos em soluções .NET reproduzíveis, com contratos, testes, dependências e publicação verificadas. Estude organização, injeção de dependências, APIs, persistência e observação, mantendo regras de domínio separadas de frameworks e tratando compatibilidade como parte do produto.",
    "level": "Especialização",
    "topics": [
      "solutions projects references NuGet",
      "unit integration end-to-end tests",
      "dependency injection lifetimes",
      "ASP.NET middleware APIs",
      "EF Core transactions migrations",
      "logging configuration secrets",
      "publish trimming AOT",
      "architecture domain adapters",
      "versioning compatibility"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-modelagem-completa",
    "track": "sql-completo",
    "title": "SQL: modelo relacional, tipos e integridade",
    "body": "Modele dados antes de escrever consultas, distinguindo entidades, relações, chaves e restrições. Aprenda DDL, tipos, NULL e normalização com exemplos PostgreSQL, definindo regras de integridade no banco em vez de depender somente da aplicação para evitar estados inválidos.",
    "level": "Fundamentos",
    "topics": [
      "relations rows columns keys",
      "CREATE ALTER DROP schema",
      "primary foreign unique keys",
      "NOT NULL CHECK DEFAULT",
      "NULL three-valued logic",
      "numeric text boolean dates",
      "normalization dependencies",
      "INSERT UPDATE DELETE RETURNING",
      "PostgreSQL dialect"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-consultas-joins",
    "track": "sql-completo",
    "title": "SQL: consultas, joins e composição",
    "body": "Construa consultas entendendo cardinalidade, filtros e a ordem lógica das operações. Estude joins internos e externos, subconsultas, EXISTS, operações de conjunto, CTEs e paginação, evitando duplicações acidentais e o erro de transformar um LEFT JOIN em INNER JOIN por um filtro mal colocado.",
    "level": "Intermediário",
    "topics": [
      "SELECT FROM WHERE order logic",
      "INNER LEFT RIGHT FULL CROSS JOIN",
      "join cardinality aliases",
      "EXISTS NOT EXISTS correlated",
      "UNION ALL INTERSECT EXCEPT",
      "CTEs composition",
      "ORDER BY LIMIT keyset pagination",
      "LATERAL",
      "parameterized queries"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-agregacoes-janelas",
    "track": "sql-completo",
    "title": "SQL: agregações, janelas e análise",
    "body": "Produza relatórios com agregação e funções de janela sem perder a granularidade necessária. Estude GROUP BY, HAVING, COUNT, FILTER, ranking, acumulados, LAG, LEAD e frames, distinguindo agrupamento de análise por linha e explicando o efeito de empates e valores ausentes.",
    "level": "Avançado",
    "topics": [
      "GROUP BY HAVING",
      "count sum avg NULL",
      "aggregate FILTER distinct",
      "window PARTITION ORDER",
      "row_number rank dense_rank",
      "lag lead",
      "ROWS RANGE frames",
      "running totals",
      "grouping sets rollup"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-transacoes",
    "track": "sql-completo",
    "title": "SQL: transações, MVCC e concorrência",
    "body": "Defina operações atômicas e compreenda o que outras sessões podem observar durante uma transação. Estude commit, rollback, savepoints, MVCC, isolamento, locks, deadlocks e repetição de falhas, evitando tratar uma sequência de consultas independentes como uma operação indivisível.",
    "level": "Avançado",
    "topics": [
      "ACID BEGIN COMMIT ROLLBACK",
      "savepoints",
      "MVCC snapshots",
      "read committed repeatable read serializable",
      "lost updates write skew",
      "SELECT FOR UPDATE",
      "deadlocks ordering",
      "retry idempotency",
      "constraints concurrency"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-indices-planos",
    "track": "sql-completo",
    "title": "SQL: índices, planos e otimização",
    "body": "Aprenda a investigar consultas com EXPLAIN e dados representativos, escolhendo índices pelo padrão de acesso. Estude B-tree, índices compostos, parciais e de expressão, estatísticas, scans, joins físicos e custos de escrita, evitando otimizações que apenas funcionam em uma tabela minúscula.",
    "level": "Especialização",
    "topics": [
      "EXPLAIN ANALYZE BUFFERS",
      "statistics ANALYZE estimates",
      "B-tree composite order",
      "partial expression covering indexes",
      "GIN GiST BRIN",
      "sequential index bitmap scans",
      "join strategies",
      "sargability",
      "write costs maintenance"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-esquema-avancado",
    "track": "sql-completo",
    "title": "SQL: views, recursão, JSON e evolução",
    "body": "Componha estruturas e rotinas avançadas sem perder integridade ou compatibilidade. Estude views, materialização, CTEs recursivas, JSONB, funções, triggers, particionamento, permissões e migrations, definindo fontes de verdade e estratégias de atualização para cada recurso.",
    "level": "Especialização",
    "topics": [
      "views materialized refresh",
      "recursive CTE termination cycles",
      "JSONB operators indexes",
      "functions procedures triggers",
      "generated identity columns",
      "partitioning pruning",
      "roles grants least privilege",
      "schema migrations compatibility",
      "backup restore verification"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  }
];
const loaders:Record<string,()=>Promise<{default:DeepCourse}>>={"python-completo":()=>import('./python'),"typescript-completo":()=>import('./typescript'),"cpp-completo":()=>import('./cpp'),"javascript-completo":()=>import('./javascript'),"html-completo":()=>import('./html'),"css-completo":()=>import('./css'),"csharp-completo":()=>import('./csharp'),"sql-completo":()=>import('./sql')};
const pending=new Map<string,Promise<DeepCourse>>();
export async function resolveExpandedLesson(id:string):Promise<Lesson|undefined>{
 const metadata=expandedLessons.find(l=>l.id===id);if(!metadata)return;
 let promise=pending.get(metadata.track);
 if(!promise){promise=loaders[metadata.track]().then(module=>module.default);pending.set(metadata.track,promise);promise.catch(()=>pending.delete(metadata.track));}
 const course=await promise,entry=course.lessons.find(l=>l.id===id);
 return entry?materialize(course,entry):undefined;
}
