import type {Course,Lesson} from '../curriculum';
import {materialize,type DeepCourse} from './types';
export const expandedCourses:Course[]=[
  {
    "id": "python-completo",
    "title": "Python · do zero ao avançado",
    "description": "Tipos, coleções, funções, objetos, biblioteca padrão, concorrência e engenharia de projetos.",
    "icon": "file-code-2",
    "lessonIds": [
      "py-fundamentos",
      "py-numeros-texto",
      "py-controle-invariantes",
      "py-colecoes-funcoes",
      "py-funcoes-contratos",
      "py-objetos-protocolos",
      "py-iteracao-recursos",
      "py-biblioteca-dados",
      "py-concorrencia",
      "py-engenharia"
    ]
  },
  {
    "id": "typescript-completo",
    "title": "TypeScript · do zero ao avançado",
    "description": "JavaScript tipado, narrowing, contratos, genéricos, tipos avançados e integração com dados reais.",
    "icon": "braces",
    "lessonIds": [
      "ts-fundamentos",
      "ts-inferencia-ausencia",
      "ts-contratos",
      "ts-validacao-aninhada",
      "ts-genericos",
      "ts-genericos-relacoes",
      "ts-variancia-contratos",
      "ts-tipos-avancados",
      "ts-modulos-configuracao",
      "ts-fronteiras-qualidade"
    ]
  },
  {
    "id": "cpp-completo",
    "title": "C++ · do zero ao avançado",
    "description": "Compilação, tipos, funções, RAII, STL, templates, memória, concorrência e desempenho.",
    "icon": "file-code-2",
    "lessonIds": [
      "cpp-fundamentos",
      "cpp-texto-conversao",
      "cpp-funcoes-referencias",
      "cpp-classes-raii",
      "cpp-raii-posse-unica",
      "cpp-stl-algoritmos",
      "cpp-iteradores-invalidacao",
      "cpp-templates",
      "cpp-memoria-posse",
      "cpp-concorrencia-engenharia"
    ]
  },
  {
    "id": "javascript-completo",
    "title": "JavaScript · fundamentos à especialização",
    "description": "Semântica da linguagem, funções, objetos, coleções, assíncrono, módulos e engenharia.",
    "icon": "braces",
    "lessonIds": [
      "js-semantica",
      "js-conversao-limites",
      "js-funcoes-this",
      "js-closures-estado",
      "js-objetos-modelos",
      "js-propriedades-prototipos",
      "js-colecoes-iteracao",
      "js-assincrono",
      "js-promessas-contratos",
      "js-modulos-engenharia"
    ]
  },
  {
    "id": "html-completo",
    "title": "HTML · do zero à plataforma web",
    "description": "Documentos semânticos, texto, formulários, mídia, acessibilidade e integração com o navegador.",
    "icon": "file-code-2",
    "lessonIds": [
      "html-documentos",
      "html-arvore-semantica",
      "html-texto-links",
      "html-formularios",
      "html-dados-formulario",
      "html-midia",
      "html-acessibilidade",
      "html-dialogo-foco",
      "html-plataforma"
    ]
  },
  {
    "id": "css-completo",
    "title": "CSS · do zero ao avançado",
    "description": "Cascata, caixas, Flexbox, Grid, responsividade, tipografia, movimento e arquitetura de estilos.",
    "icon": "layers",
    "lessonIds": [
      "css-cascata",
      "css-cascata-camadas",
      "css-caixas",
      "css-caixas-intrinseco",
      "css-flex-grid",
      "css-grid-trilhas",
      "css-responsivo",
      "css-containers-contexto",
      "css-visual-movimento",
      "css-arquitetura"
    ]
  },
  {
    "id": "csharp-completo",
    "title": "C# · do zero à engenharia",
    "description": "Tipos, coleções, LINQ, orientação a objetos, assíncrono, runtime e projetos .NET.",
    "icon": "braces",
    "lessonIds": [
      "cs-tipos-controle",
      "cs-decimal-limites",
      "cs-metodos-parametros",
      "cs-colecoes-linq",
      "cs-objetos-contratos",
      "cs-assincrono-recursos",
      "cs-iteradores-descarte",
      "cs-runtime-avancado",
      "cs-engenharia"
    ]
  },
  {
    "id": "sql-completo",
    "title": "SQL · do zero ao avançado",
    "description": "Modelagem relacional, consultas, janelas, transações, índices e engenharia com PostgreSQL.",
    "icon": "database",
    "lessonIds": [
      "sql-modelagem-completa",
      "sql-null-logica",
      "sql-consultas-joins",
      "sql-joins-cardinalidade",
      "sql-agregacoes-janelas",
      "sql-transacoes",
      "sql-isolamento-sessoes",
      "sql-indices-planos",
      "sql-esquema-avancado"
    ]
  }
];
export const expandedLessons:Lesson[]=[
  {
    "id": "py-fundamentos",
    "track": "python-completo",
    "title": "Python: execução, tipos e controle",
    "body": "Construa seu primeiro programa Python entendendo a execução do arquivo, a indentação e a relação entre nomes e objetos. Estude números, strings, booleanos, conversões, entrada e saída, decisões, repetição e os casos de limite que distinguem um programa previsível de um exemplo que só funciona com uma entrada.",
    "level": "Fundamentos",
    "topics": [
      "interpretador e REPL",
      "indentação",
      "int float bool None",
      "str e Unicode",
      "conversões e entrada",
      "if elif else",
      "for range while",
      "break continue else",
      "comparação e identidade"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-numeros-texto",
    "track": "python-completo",
    "title": "Python: números exatos, texto e conversão de entrada",
    "body": "Aprenda a escolher uma representação para quantidades, preços e texto antes de escrever cálculos. Esta aula separa o dado recebido, a validação do contrato e o resultado formatado. Você vai investigar divisão, restos, aproximação binária, Unicode e entradas inválidas, com programas completos que não dependem de interação no terminal.",
    "level": "Fundamentos",
    "topics": [
      "int e limites de representação",
      "divisão real e divisão pelo piso",
      "resto e distribuição de unidades",
      "float e erro de representação",
      "Decimal construído de texto",
      "str e pontos de código Unicode",
      "normalização NFC",
      "conversão integral estrita"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/library/stdtypes.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-controle-invariantes",
    "track": "python-completo",
    "title": "Python: decisões, laços e prova de término",
    "body": "Construa decisões e repetições que você consiga explicar antes de executá-las. Esta aula usa intervalos, acumuladores, busca e sentinelas para mostrar como um laço preserva uma regra e como seu estado avança até terminar. As atividades incluem entrada vazia, ausência de resultado e um limite exato, sem depender de um while infinito para ensinar repetição.",
    "level": "Fundamentos",
    "topics": [
      "if elif e ordem das condições",
      "intervalos semiabertos",
      "range com passo",
      "acumulador e invariante",
      "while e variante de término",
      "break continue e else de laço",
      "busca sem resultado",
      "lista vazia e casos de fronteira"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/tutorial/controlflow.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-colecoes-funcoes",
    "track": "python-completo",
    "title": "Python: coleções, funções e iteração",
    "body": "Aprenda a escolher list, tuple, dict e set pelo contrato dos dados, escrever funções com parâmetros claros e percorrer coleções sem modificar acidentalmente seus elementos. Conecte fatiamento, comprehensions, desempacotamento, escopo, closures, iteradores e geradores a problemas de transformação e agregação.",
    "level": "Intermediário",
    "topics": [
      "list tuple dict set",
      "mutabilidade e cópia",
      "slicing e desempacotamento",
      "comprehensions",
      "parâmetros posicionais e nomeados",
      "args kwargs",
      "escopo LEGB closures",
      "iteradores e yield",
      "complexidade"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-funcoes-contratos",
    "track": "python-completo",
    "title": "Python: parâmetros, escopo e funções com contratos",
    "body": "Leia uma função como um acordo entre entrada, resultado e efeitos. Você vai escolher parâmetros posicionais ou nomeados, evitar defaults mutáveis compartilhados, compreender LEGB e produzir uma closure com estado próprio. Os problemas verificam independência entre chamadas e preservação dos dados de entrada, incluindo testes que expõem erros que uma única execução esconderia.",
    "level": "Intermediário",
    "topics": [
      "contrato de entrada e retorno",
      "parâmetros nomeados e keyword-only",
      "default avaliado na definição",
      "sentinela None para default mutável",
      "escopo LEGB",
      "nonlocal e binding externo",
      "closure por chamada",
      "retorno novo sem modificar entrada"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-objetos-protocolos",
    "track": "python-completo",
    "title": "Python: classes, protocolos e metaprogramação",
    "body": "Modele objetos por responsabilidades e contratos, usando classes, dataclasses, propriedades e composição. Entenda o sistema de atributos, métodos especiais, herança, super, protocolos, decoradores e context managers para criar APIs previsíveis, sem recorrer a mecanismos avançados quando uma função simples resolve o problema.",
    "level": "Avançado",
    "topics": [
      "classes instâncias self",
      "dataclasses",
      "herança composição MRO super",
      "property descritores",
      "dunder repr eq hash",
      "duck typing protocolos",
      "decoradores functools.wraps",
      "context managers",
      "slots metaclasses"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-iteracao-recursos",
    "track": "python-completo",
    "title": "Python: iteradores, geradores e consumo com recursos",
    "body": "Diferencie um objeto iterável de um cursor de uso único, acompanhe a suspensão de um gerador e componha processamento em lotes sem carregar a fonte inteira. A aula separa consumo de dados, validação e posse de recursos: os exercícios verificam ausência de leitura antecipada, esgotamento, limpeza após interrupção e propagação de erros. As pausas conceituais funcionam offline; os programas de referência são executados com Python no CI.",
    "level": "Avançado",
    "topics": [
      "iterável e iterador de uso único",
      "protocolo __iter__ e __next__",
      "StopIteration e esgotamento",
      "suspensão e retomada com yield",
      "delegação com yield from",
      "validação antes da iteração",
      "lotes com itertools.islice",
      "consumo sem leitura antecipada",
      "posse e fechamento explícito",
      "finally e interrupção do consumidor"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/library/itertools.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-biblioteca-dados",
    "track": "python-completo",
    "title": "Python: arquivos, exceções e biblioteca padrão",
    "body": "Aprenda a trabalhar com recursos reais usando pathlib, arquivos Unicode, JSON, CSV, datas, expressões regulares e coleções especializadas. Estabeleça fronteiras de validação, trate exceções específicas e escreva arquivos com uma estratégia que não deixe resultados parciais silenciosamente.",
    "level": "Intermediário",
    "topics": [
      "pathlib arquivos encoding",
      "with e exceções",
      "JSON CSV validação",
      "datetime zoneinfo",
      "decimal fractions",
      "collections itertools functools",
      "re Unicode",
      "logging argparse",
      "os subprocess segurança"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-concorrencia",
    "track": "python-completo",
    "title": "Python: concorrência, async e paralelismo",
    "body": "Distinga concorrência de paralelismo e escolha entre asyncio, threads e processos pelo tipo de trabalho. Estude corrotinas, tarefas, cancelamento, limites, filas, sincronização, tratamento de falhas e o impacto do runtime, evitando supor que escrever async torna uma operação bloqueante automaticamente assíncrona.",
    "level": "Avançado",
    "topics": [
      "concorrência versus paralelismo",
      "async await corrotinas",
      "TaskGroup cancelamento",
      "timeouts semáforos filas",
      "threads locks",
      "ProcessPoolExecutor",
      "GIL builds free-threaded",
      "backpressure",
      "falhas e recursos"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-engenharia",
    "track": "python-completo",
    "title": "Python: tipagem, testes, pacotes e desempenho",
    "body": "Transforme scripts em projetos reproduzíveis, com ambientes isolados, módulos bem delimitados, anotação de tipos, testes úteis e medição de desempenho. Aprenda a documentar contratos e distribuir pacotes, relacionando ferramentas de engenharia às falhas que elas realmente conseguem detectar.",
    "level": "Especialização",
    "topics": [
      "módulos imports __main__",
      "venv pip pyproject.toml",
      "typing Protocol Generic",
      "testes unittest mocks",
      "propriedades casos de borda",
      "profiling timeit tracemalloc",
      "algoritmos complexidade",
      "distribuição wheels",
      "documentação e evolução"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-fundamentos",
    "track": "typescript-completo",
    "title": "TypeScript: tipos, inferência e execução",
    "body": "Entenda o que TypeScript verifica antes da execução e o que permanece responsabilidade do JavaScript. Aprenda inferência, tipos primitivos, arrays, tuplas, literal types, uniões, null e undefined, distinguindo erros do compilador de validação dos dados que chegam durante a execução.",
    "level": "Fundamentos",
    "topics": [
      "tsc e apagamento de tipos",
      "inferência",
      "string number boolean",
      "arrays readonly tuples",
      "literal types unions",
      "strictNullChecks",
      "unknown versus any",
      "type assertions satisfies"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-inferencia-ausencia",
    "track": "typescript-completo",
    "title": "TypeScript: inferência, ausência e contratos sem coerção",
    "body": "Entenda o que o compilador consegue provar sobre uma variável e o que continua dependendo dos dados recebidos. Você vai modelar quantidade opcional, preservar zero, usar narrowing em vez de assertions e distinguir ausência de erro. Os problemas incluem catálogo por identificador e limite configurável, com testes positivos, negativos e resultados reais depois do apagamento dos tipos.",
    "level": "Fundamentos",
    "topics": [
      "inferência e widening",
      "union com undefined",
      "strictNullChecks",
      "narrowing por typeof",
      "operador nullish",
      "assertion sem validação",
      "readonly e mutação",
      "contrato de retorno discriminado"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-contratos",
    "track": "typescript-completo",
    "title": "TypeScript: objetos, narrowing e uniões discriminadas",
    "body": "Descreva modelos com type e interface, compreenda tipagem estrutural e refine valores por controle de fluxo. Use uniões discriminadas para representar estados possíveis e impossíveis, mantendo decisões exaustivas e evitando objetos cheios de propriedades opcionais cuja combinação não tem significado.",
    "level": "Intermediário",
    "topics": [
      "type interface tipagem estrutural",
      "optional readonly",
      "excess property checks",
      "typeof in instanceof",
      "type predicates assertions",
      "discriminated unions",
      "never exhaustiveness",
      "intersections index signatures"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-validacao-aninhada",
    "track": "typescript-completo",
    "title": "TypeScript: validar JSON aninhado e produzir dados de domínio",
    "body": "Atravesse uma fronteira de JSON sem fingir que uma anotação de tipo valida a resposta. Esta aula constrói um adaptador de unknown para um pedido com itens, confere cada nível, copia os campos aceitos e relata uma falha com caminho. Os exercícios aprofundam campos opcionais e testes de tipos, preservando a diferença entre o formato externo e o modelo usado no cálculo.",
    "level": "Intermediário",
    "topics": [
      "JSON.parse como fronteira unknown",
      "objeto não nulo e não array",
      "validação de campos aninhados",
      "validação de todos os itens",
      "mensagem com caminho de erro",
      "cópia dos campos aceitos",
      "campo opcional versus inválido",
      "testes com ts-expect-error"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/handbook/2/objects.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-genericos",
    "track": "typescript-completo",
    "title": "TypeScript: genéricos, coleções e variância",
    "body": "Use genéricos para preservar relações entre tipos de entrada e saída, imponha constraints proporcionais ao que a função realmente usa e componha funções sem apagar informações com any. Explore keyof, indexed access, overloads, parâmetros padrão, callbacks e os cuidados de variância em coleções mutáveis.",
    "level": "Avançado",
    "topics": [
      "generic functions interfaces",
      "constraints extends",
      "keyof indexed access",
      "defaults inference",
      "overloads",
      "callbacks variance",
      "readonly collections",
      "generic classes factories"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-genericos-relacoes",
    "track": "typescript-completo",
    "title": "TypeScript: genéricos que preservam relações entre dados",
    "body": "Use parâmetros de tipo para manter uma relação que se perderia com any ou unions desconectadas. Esta aula constrói seleção de propriedade e transformação de coleções, compara constraints com assertions e mostra por que uma função genérica não pode inventar qualquer T. Os problemas incluem keyof, indexed access, inferência e casos negativos conferidos pelo compilador.",
    "level": "Avançado",
    "topics": [
      "parâmetro de tipo como relação",
      "inferência do tipo de retorno",
      "constraint extends",
      "keyof e chave válida",
      "indexed access T K",
      "readonly na entrada genérica",
      "tipo específico não inventado",
      "teste negativo de propriedade"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/handbook/2/generics.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-variancia-contratos",
    "track": "typescript-completo",
    "title": "TypeScript: variância, callbacks e contratos de leitura e escrita",
    "body": "Raciocine sobre substituição a partir das operações que uma API oferece. Compare produtores, consumidores e células de leitura e escrita; examine por que um callback que exige mais dados não pode atender a todos os valores de um contrato amplo. Os exemplos distinguem aceitação pelo compilador, comportamento real e limite das assinaturas de método. Há testes positivos e negativos em strict, exercícios de borda e duas práticas independentes.",
    "level": "Avançado",
    "topics": [
      "compatibilidade estrutural",
      "covariância de resultados",
      "contravariância de parâmetros",
      "invariância de leitura e escrita",
      "strictFunctionTypes",
      "método versus propriedade de função",
      "readonly e mutação por alias",
      "contrato de callback",
      "testes negativos com ts-expect-error",
      "limites de anotações in e out"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/tsconfig/strictFunctionTypes.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-tipos-avancados",
    "track": "typescript-completo",
    "title": "TypeScript: transformação e programação de tipos",
    "body": "Explore mapped types, conditional types, infer e template literal types como ferramentas para derivar contratos de uma fonte comum. Entenda distribuição sobre uniões, utilitários e limites de legibilidade, evitando tornar o sistema de tipos um programa complexo que a equipe não consegue manter.",
    "level": "Avançado",
    "topics": [
      "mapped types modifiers",
      "Pick Omit Partial Required Readonly",
      "Record Exclude Extract",
      "conditional types distribution",
      "infer ReturnType Parameters Awaited",
      "template literal types",
      "key remapping",
      "recursive types limits"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-modulos-configuracao",
    "track": "typescript-completo",
    "title": "TypeScript: módulos, configuração e declarações",
    "body": "Configure TypeScript de acordo com o ambiente onde o JavaScript será executado. Aprenda target, lib, module, moduleResolution, strict, arquivos de declaração e organização de bibliotecas, distinguindo suporte de sintaxe, disponibilidade de APIs e resolução real de arquivos.",
    "level": "Especialização",
    "topics": [
      "tsconfig strict",
      "target lib module",
      "NodeNext bundler resolution",
      "ESM CommonJS",
      "import type verbatimModuleSyntax",
      "declaration d.ts",
      "ambient declarations",
      "project references",
      "source maps packaging"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-fronteiras-qualidade",
    "track": "typescript-completo",
    "title": "TypeScript: validação, assíncrono e qualidade",
    "body": "Conecte contratos estáticos a dados recebidos por JSON, formulários e APIs, usando validação explícita e resultados discriminados. Explore promises, cancelamento, testes de tipos e execução, arquitetura de fronteiras e migração gradual de JavaScript sem esconder problemas com casts e any.",
    "level": "Especialização",
    "topics": [
      "JSON unknown validation",
      "Result discriminated unions",
      "Promise async errors",
      "AbortController",
      "static versus runtime tests",
      "ts-expect-error",
      "gradual migration checkJs JSDoc",
      "domain DTO boundaries",
      "security and serialization"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-fundamentos",
    "track": "cpp-completo",
    "title": "C++: compilação, tipos e controle",
    "body": "Aprenda a transformar arquivos C++ em um programa executável, compreender diagnósticos de compilação e estabelecer contratos de tipos e entrada. Estude inicialização, conversões, expressões, decisões, repetição e funções, reconhecendo desde o início os limites dos números e o perigo de comportamento indefinido.",
    "level": "Fundamentos",
    "topics": [
      "compilação ligação main",
      "headers namespaces",
      "tipos fundamentais auto",
      "inicialização narrowing",
      "signed unsigned overflow",
      "if switch loops",
      "funções parâmetros retorno",
      "const constexpr",
      "entrada e streams"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-texto-conversao",
    "track": "cpp-completo",
    "title": "C++: entrada textual, conversão completa e estados de erro",
    "body": "Leia texto sem perder partes da entrada e transforme uma quantidade somente quando o campo inteiro atende ao contrato. Você vai distinguir falha de conversão, texto residual e valor fora da faixa. A aula usa C++20, std::string, getline e from_chars, com programas pequenos que tornam visíveis os estados de erro sem acessar memória inválida.",
    "level": "Fundamentos",
    "topics": [
      "string como sequência de unidades char",
      "getline e leitura de linha",
      "extração formatada e texto residual",
      "from_chars e errc",
      "consumo completo da entrada",
      "limites de int",
      "optional para conversão",
      "gramática ASCII e faixa de domínio"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/charconv.from.chars",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-funcoes-referencias",
    "track": "cpp-completo",
    "title": "C++: funções, cópia, referência e tempo de vida",
    "body": "Escolha uma assinatura de função que explique quem pode alterar um objeto e por quanto tempo uma referência é válida. Você vai comparar passagem por valor, referência mutável e referência const, proteger um saldo com pré-condições e retornar objetos por valor. Os exercícios mostram cópia de coleções e empréstimo de dados sem devolver referências a variáveis destruídas.",
    "level": "Fundamentos",
    "topics": [
      "parâmetro por valor",
      "referência mutável",
      "referência const",
      "pré-condição e pós-condição",
      "retorno por valor",
      "referência para objeto local",
      "const não significa posse",
      "cópia de vector e dados originais"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/dcl.ref",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-classes-raii",
    "track": "cpp-completo",
    "title": "C++: classes, RAII e semântica de valor",
    "body": "Projete classes que estabelecem invariantes na construção e liberam recursos automaticamente. Aprenda encapsulamento, construtores, destrutores, cópia, movimento, rule of zero, composição e polimorfismo, distinguindo objetos que representam valores daqueles que controlam a posse de um recurso.",
    "level": "Intermediário",
    "topics": [
      "struct class encapsulamento",
      "constructors invariants",
      "RAII destructors",
      "rule of zero five",
      "copy move semantics",
      "composition inheritance",
      "virtual destructor slicing",
      "exceptions guarantees",
      "explicit const methods"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-raii-posse-unica",
    "track": "cpp-completo",
    "title": "C++: RAII, posse exclusiva e transferência de recursos",
    "body": "Associe a duração de um recurso a um objeto e acompanhe o que acontece na saída normal ou por exceção. Esta aula usa RAII e unique_ptr para mostrar aquisição, destruição e transferência de posse, distinguindo mover o ponteiro de copiar o objeto. Os problemas verificam a quantidade de objetos vivos e a preservação de invariantes durante falhas.",
    "level": "Intermediário",
    "topics": [
      "RAII e duração do recurso",
      "destrutor na saída de escopo",
      "desenrolamento por exceção",
      "unique_ptr não copiável",
      "move transfere a posse",
      "ponteiro movido e estado vazio",
      "rule of zero na composição",
      "observador sem propriedade"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/unique.ptr",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-stl-algoritmos",
    "track": "cpp-completo",
    "title": "C++: STL, iteradores, algoritmos e ranges",
    "body": "Escolha contêineres pela forma de acesso, conheça invalidação de iteradores e substitua laços frágeis por algoritmos com contratos claros. Estude vector, array, map, unordered_map, set, lambdas, comparadores, ranges e complexidade para transformar dados preservando segurança e previsibilidade.",
    "level": "Intermediário",
    "topics": [
      "vector array deque list",
      "map set unordered_map",
      "iterator categories invalidation",
      "algorithms sort find accumulate",
      "lambdas captures",
      "comparators strict weak ordering",
      "ranges views lifetime",
      "complexity"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-iteradores-invalidacao",
    "track": "cpp-completo",
    "title": "C++: iteradores de vector, invalidação e remoção segura",
    "body": "Percorra vector sem acessar o fim, reconheça quando uma alteração invalida posições e remova elementos consecutivos sem saltar candidatos. Separe capacidade de tamanho, compare erase repetido com compactação e reconstrua acessos após reserve. Os programas usam C++20 e casos de borda verificáveis; views e identidade estável são introduzidas para próximos aprofundamentos.",
    "level": "Avançado",
    "topics": [
      "intervalo [begin,end)",
      "iterador versus identidade",
      "size versus capacity",
      "realocação e invalidação",
      "retorno de erase e avanço",
      "remoções consecutivas",
      "erase-remove e tamanho lógico",
      "ordem dos elementos preservados",
      "custo de remoções repetidas",
      "views e tempo de vida"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/vector.modifiers",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-templates",
    "track": "cpp-completo",
    "title": "C++: templates, concepts e avaliação constante",
    "body": "Crie algoritmos genéricos com requisitos explícitos, entenda instanciação e diagnósticos de templates e use concepts para expressar capacidades. Explore dedução, overloads, constexpr, if constexpr, variádicos e type traits, mantendo a abstração proporcional às necessidades do código.",
    "level": "Avançado",
    "topics": [
      "function class templates",
      "deduction instantiation",
      "concepts requires",
      "constraints overloads",
      "if constexpr type_traits",
      "variadic templates folds",
      "constexpr consteval",
      "specialization ODR headers"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-memoria-posse",
    "track": "cpp-completo",
    "title": "C++: memória, posse e segurança de vida",
    "body": "Entenda duração de armazenamento, vida de objetos, ponteiros, referências e categorias de valor para evitar acessos pendentes. Use unique_ptr, shared_ptr, weak_ptr, span, string_view, optional e variant com contratos explícitos de posse, reconhecendo custos e condições de validade.",
    "level": "Avançado",
    "topics": [
      "storage duration lifetime",
      "pointers references nullptr",
      "unique_ptr shared_ptr weak_ptr",
      "ownership cycles",
      "span string_view dangling",
      "value categories move forwarding",
      "optional variant visit",
      "alignment allocation placement",
      "sanitizers UB"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-concorrencia-engenharia",
    "track": "cpp-completo",
    "title": "C++: concorrência, build e desempenho",
    "body": "Aprenda a organizar trabalho concorrente e medir desempenho sem comprometer correção. Estude threads, jthread, sincronização, atomics, futures e cancelamento, conectando o modelo de memória a testes, sanitizers, sistemas de build, unidades de tradução e escolhas de arquitetura.",
    "level": "Especialização",
    "topics": [
      "thread jthread stop_token",
      "mutex scoped_lock condition_variable",
      "atomics memory ordering",
      "data races deadlocks",
      "future async",
      "build headers CMake modules",
      "profiling benchmarks",
      "cache locality false sharing",
      "coroutines custom awaitables"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-semantica",
    "track": "javascript-completo",
    "title": "JavaScript: valores, coerção e escopo",
    "body": "Consolide o modelo de execução de JavaScript, distinguindo valores primitivos, referências a objetos, coerção e escopo. Estude operadores, números, strings Unicode, comparação, destructuring e closures para prever programas com precisão, inclusive nos casos em que a sintaxe parece simples mas o resultado surpreende.",
    "level": "Fundamentos",
    "topics": [
      "primitives objects typeof",
      "Number BigInt NaN",
      "Unicode strings",
      "coercion equality Object.is",
      "truthiness nullish",
      "let const var TDZ",
      "destructuring rest spread",
      "closures lexical scope"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-conversao-limites",
    "track": "javascript-completo",
    "title": "JavaScript: conversão explícita e números nos limites",
    "body": "Trate a entrada recebida antes de permitir que os operadores escolham uma conversão implícita. Esta aula explica concatenação, igualdade, números seguros, NaN e preservação de zero. Os problemas constroem uma quantidade inteira e um total em centavos com contratos que rejeitam dados ambíguos, sem depender de parseInt para validar um campo completo.",
    "level": "Fundamentos",
    "topics": [
      "coerção do operador mais",
      "Number e conversão explícita",
      "parseInt e prefixo válido",
      "NaN e Number.isNaN",
      "inteiros seguros",
      "zero e operador nullish",
      "BigInt e Number separados",
      "validação antes do cálculo"
    ],
    "language": "javascript",
    "source": "https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tonumber",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-funcoes-this",
    "track": "javascript-completo",
    "title": "JavaScript: funções, this e composição",
    "body": "Estude declarações, expressões, arrow functions, callbacks e closures como formas de criar e combinar comportamento. Entenda como this é escolhido por uma chamada, como bind, call e apply alteram esse contexto e como funções puras ajudam a testar regras sem efeitos externos.",
    "level": "Intermediário",
    "topics": [
      "declaration expression arrow",
      "parameters defaults rest",
      "this call apply bind",
      "lexical this",
      "higher-order functions",
      "closures callbacks",
      "pure functions composition",
      "recursion stack tail calls"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-closures-estado",
    "track": "javascript-completo",
    "title": "JavaScript: closures, identidade e estado de uma instância",
    "body": "Acompanhe os ambientes léxicos que uma função conserva e separe o estado de duas instâncias. Esta aula constrói um contador com contrato, compara captura de variável com cópia de valor e explica por que const não congela um objeto. Os problemas investigam callbacks em laços e snapshots independentes, com todas as saídas previstas antes da execução.",
    "level": "Fundamentos",
    "topics": [
      "escopo léxico",
      "closure e binding capturado",
      "fábrica e estado por instância",
      "const e objeto mutável",
      "identidade versus cópia",
      "let em laço",
      "var e ambiente compartilhado",
      "snapshot sem referência interna"
    ],
    "language": "javascript",
    "source": "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-function-definitions",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-objetos-modelos",
    "track": "javascript-completo",
    "title": "JavaScript: objetos, protótipos e classes",
    "body": "Entenda acesso a propriedades, identidade, descritores e cadeia de protótipos antes de usar classes. Explore encapsulamento com campos privados, composição, herança, getters, symbols, Proxy e Reflect, mantendo validação e políticas de dados distintas dos mecanismos da linguagem.",
    "level": "Avançado",
    "topics": [
      "property keys descriptors",
      "own versus inherited",
      "prototype chain",
      "classes constructors private fields",
      "getters setters",
      "composition inheritance super",
      "symbols",
      "Proxy Reflect",
      "prototype pollution boundaries"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-propriedades-prototipos",
    "track": "javascript-completo",
    "title": "JavaScript: propriedades, descritores e receptores de acesso",
    "body": "Distinga uma propriedade do próprio objeto de um valor encontrado no protótipo, investigue descritores e compreenda por que ler um campo pode executar código. Extraia configurações por um contrato explícito e acompanhe o receiver de getters e setters. Pratique com entradas herdadas, números nos limites, acessores e instâncias independentes; Proxy e congelamento profundo permanecem aprofundamentos futuros.",
    "level": "Avançado",
    "topics": [
      "propriedade própria versus herdada",
      "descritor de dados e acessor",
      "enumerabilidade e escolha de chaves",
      "writable configurable e escrita recusada",
      "getters e efeitos de leitura",
      "receiver na cadeia de protótipos",
      "estado próprio por instância",
      "cópia de valores versus descritores",
      "freeze raso e objetos aninhados",
      "fronteira com Proxy e dados externos"
    ],
    "language": "javascript",
    "source": "https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object.getownpropertydescriptor",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-colecoes-iteracao",
    "track": "javascript-completo",
    "title": "JavaScript: coleções, iteradores e memória",
    "body": "Escolha arrays, Map, Set e coleções fracas segundo o contrato, e use iteradores e geradores para processar sequências com controle de memória. Estude mutabilidade, ordenação, typed arrays, buffers, expressões regulares, internacionalização e gestão de recursos, respeitando as APIs disponíveis em cada runtime.",
    "level": "Avançado",
    "topics": [
      "arrays sparse map filter reduce sort",
      "Map Set identity",
      "WeakMap WeakSet GC",
      "iterators generators yield",
      "typed arrays ArrayBuffer DataView",
      "RegExp Unicode",
      "Intl formatting segmentation",
      "resource lifetime dispose",
      "memory leaks"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-assincrono",
    "track": "javascript-completo",
    "title": "JavaScript: promises, concorrência e cancelamento",
    "body": "Entenda event loop, microtasks, promises e async/await para coordenar trabalho sem perder erros ou atualizar uma interface com resultados antigos. Estude combinações, limites de concorrência, cancelamento, timeouts e idempotência, distinguindo tarefas de JavaScript de APIs oferecidas pelo ambiente.",
    "level": "Avançado",
    "topics": [
      "event loop jobs microtasks",
      "Promise states chaining",
      "async await rejection",
      "all allSettled race any",
      "bounded concurrency",
      "AbortController host APIs",
      "timeouts stale responses",
      "idempotency retry backoff"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-promessas-contratos",
    "track": "javascript-completo",
    "title": "JavaScript: promises, propagação de falhas e concorrência limitada",
    "body": "Entenda o que uma promise representa e como o fluxo muda quando uma tarefa falha. Esta aula compara sequência, concorrência, all e allSettled, sem confundir rejeição com cancelamento. Os problemas constroem recuperação com um valor definido e um grupo de trabalhadores com limite, usando microtarefas reproduzíveis no laboratório.",
    "level": "Avançado",
    "topics": [
      "promise pendente fulfilled rejected",
      "then retorna outra promise",
      "throw vira rejeição no callback",
      "await e propagação de erro",
      "all não cancela tarefas",
      "allSettled conserva resultados",
      "concorrência limitada por trabalhadores",
      "ordem de saída versus ordem de término"
    ],
    "language": "javascript",
    "source": "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.all",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "js-modulos-engenharia",
    "track": "javascript-completo",
    "title": "JavaScript: módulos, testes e arquitetura",
    "body": "Organize programas JavaScript em módulos e fronteiras, usando testes, validação e medição para evoluir com confiança. Estude imports, exports, dependências, ambientes, tratamento de erros, serialização, segurança e observação, relacionando ferramentas à correção dos fluxos completos.",
    "level": "Especialização",
    "topics": [
      "ES modules live bindings",
      "dynamic import top-level await",
      "cycles CommonJS hosts",
      "errors causes boundaries",
      "JSON structured clone",
      "unit integration e2e",
      "dependency injection",
      "performance profiling",
      "security DOM SQL boundaries"
    ],
    "language": "javascript",
    "source": "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-documentos",
    "track": "html-completo",
    "title": "HTML: documento, árvore e semântica",
    "body": "Aprenda como HTML descreve um documento e como o navegador transforma sua fonte em uma árvore DOM. Estude estrutura, metadados, elementos semânticos, atributos globais e regras de parsing para construir páginas que funcionam sem depender da aparência ou de scripts para transmitir seu significado.",
    "level": "Fundamentos",
    "topics": [
      "doctype html head body",
      "DOM parsing nesting",
      "lang charset viewport",
      "title meta link",
      "main header nav section article aside footer",
      "global attributes id class data",
      "boolean attributes",
      "void elements entities namespaces"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-arvore-semantica",
    "track": "html-completo",
    "title": "HTML: parser, árvore do documento e estrutura semântica",
    "body": "Leia HTML como uma descrição que o navegador transforma numa árvore, e não como uma sequência de caixas desenhadas. Esta aula investiga aninhamento, correções do parser, títulos, regiões e links internos. Os problemas pedem documentos completos e tabelas com relações claras, conferidos pela estrutura criada pelo navegador e pela navegação de teclado.",
    "level": "Fundamentos",
    "topics": [
      "fonte HTML e árvore DOM",
      "fechamento implícito de p",
      "elementos void",
      "doctype e modo de renderização",
      "lang charset e title",
      "regiões main nav article",
      "hierarquia de headings",
      "caption th e scope"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/parsing.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-texto-links",
    "track": "html-completo",
    "title": "HTML: texto, links, listas e tabelas",
    "body": "Estruture informação para leitura e navegação, usando títulos, parágrafos, ênfase, citações, código, listas e tabelas de dados. Aprenda URLs, fragmentos, caminhos e nomes acessíveis de links, preservando relações que continuam claras sem a disposição visual da página.",
    "level": "Fundamentos",
    "topics": [
      "headings paragraphs emphasis",
      "strong em mark small",
      "blockquote cite q",
      "pre code whitespace",
      "ol ul dl",
      "URLs relative absolute fragments",
      "a download target rel",
      "tables caption th scope"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-formularios",
    "track": "html-completo",
    "title": "HTML: formulários, validação e dados enviados",
    "body": "Construa formulários com controles nativos, rótulos, grupos e instruções compreensíveis. Entenda name, value, tipos de input, submissão, validação de restrições, FormData e acessibilidade, sem confundir validação do navegador com confiança nos dados recebidos por um sistema.",
    "level": "Intermediário",
    "topics": [
      "form action method",
      "label name value",
      "input types textarea select",
      "checkbox radio fieldset legend",
      "required min max step pattern",
      "autocomplete inputmode",
      "constraint validation",
      "FormData successful controls",
      "client server validation"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-dados-formulario",
    "track": "html-completo",
    "title": "HTML: controles enviados, validação e botão de submissão",
    "body": "Diferencie o que aparece no formulário do que realmente entra no conjunto de dados enviado. Esta aula compara name e id, disabled e readonly, caixas marcadas e desmarcadas e o botão que disparou a submissão. Os exemplos funcionam sem servidor e mostram FormData no próprio documento, preservando validação nativa e mensagens como texto.",
    "level": "Intermediário",
    "topics": [
      "name e id em papéis diferentes",
      "label e nome acessível",
      "disabled e readonly",
      "checkbox e ausência quando desmarcado",
      "nomes repetidos e getAll",
      "FormData e submitter",
      "validação nativa antes de submit",
      "botão type button versus submit"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-the-entry-list",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-midia",
    "track": "html-completo",
    "title": "HTML: imagens, mídia e conteúdo incorporado",
    "body": "Inclua imagens, áudio, vídeo, gráficos e documentos externos com alternativas e políticas claras. Estude alt, dimensões, imagens responsivas, captions, controles, SVG, canvas e sandbox, reconhecendo que uma mídia visível não garante informação acessível nem um recurso seguro.",
    "level": "Intermediário",
    "topics": [
      "img alt width height",
      "srcset sizes picture",
      "figure figcaption",
      "audio video source track",
      "captions transcripts autoplay",
      "SVG canvas alternatives",
      "iframe title sandbox permissions",
      "lazy loading performance"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-acessibilidade",
    "track": "html-completo",
    "title": "HTML: acessibilidade e interação nativa",
    "body": "Implemente interações que respeitam teclado, foco e nomes acessíveis, usando elementos nativos antes de criar widgets complexos. Estude botões, links, details, dialog, popover, live regions e ARIA, verificando o comportamento completo em vez de confiar apenas na presença de atributos.",
    "level": "Avançado",
    "topics": [
      "keyboard focus tabindex",
      "button versus link",
      "accessible names descriptions",
      "details summary",
      "dialog modal focus return",
      "popover support",
      "ARIA states relationships",
      "live regions",
      "progressive enhancement"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-dialogo-foco",
    "track": "html-completo",
    "title": "HTML: diálogo modal, foco e formas de encerramento",
    "body": "Construa um diálogo completo com nome acessível, foco inicial e retorno ao acionador. Diferencie show de showModal, submissão com method dialog, fechamento programático e cancelamento por Escape. Trate validação e alterações não salvas sem impedir que a pessoa consiga sair, e verifique as transições por teclado no navegador real.",
    "level": "Avançado",
    "topics": [
      "dialog e nome acessível",
      "show versus showModal",
      "modalidade e conteúdo inerte",
      "foco inicial e acionador",
      "form method dialog e returnValue",
      "cancel e close",
      "formnovalidate para cancelar",
      "alterações não salvas e saída explícita"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "html-plataforma",
    "track": "html-completo",
    "title": "HTML: DOM, componentes e integração da plataforma",
    "body": "Conecte documentos a comportamento usando DOM e eventos, preservando conteúdo seguro e melhoria progressiva. Estude templates, custom elements, Shadow DOM, armazenamento, políticas de origem, workers e APIs do navegador, mantendo clara a diferença entre HTML, JavaScript e capacidades do ambiente.",
    "level": "Especialização",
    "topics": [
      "DOM createElement textContent",
      "events propagation delegation",
      "template document fragments",
      "custom elements lifecycle",
      "Shadow DOM slots",
      "storage origin sandbox",
      "fetch workers host APIs",
      "CSP same-origin permissions",
      "SEO progressive enhancement"
    ],
    "language": "html",
    "source": "https://html.spec.whatwg.org/multipage/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-cascata",
    "track": "css-completo",
    "title": "CSS: seletores, cascata e valores",
    "body": "Aprenda a prever qual declaração CSS vence e por que um valor chega ao elemento. Estude seletores, herança, especificidade, ordem, camadas, custom properties e unidades, usando o painel de estilos como ferramenta de diagnóstico em vez de acumular !important a cada conflito.",
    "level": "Fundamentos",
    "topics": [
      "selectors combinators attributes",
      "pseudo classes elements",
      "cascade origin importance layers",
      "specificity source order",
      "inherit initial unset revert",
      "custom properties var fallback",
      "computed used values",
      "relative absolute units"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-cascata-camadas",
    "track": "css-completo",
    "title": "CSS: cascata por camadas e valores de custom properties",
    "body": "Descubra qual declaração vence antes de aumentar a especificidade de um seletor. Esta aula separa origem, importância, camadas, especificidade e ordem, e mostra quando var usa seu fallback. Os problemas incluem importância com ordem de camadas invertida e um valor inválido após substituição, conferidos por estilos computados no navegador.",
    "level": "Fundamentos",
    "topics": [
      "declaração aplicável e valor vencedor",
      "ordem de camadas normais",
      "regra normal sem camada",
      "ordem invertida de important",
      "especificidade dentro da etapa",
      "herança de color",
      "fallback de var",
      "inválido no valor computado"
    ],
    "language": "html",
    "source": "https://www.w3.org/TR/css-cascade-5/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-caixas",
    "track": "css-completo",
    "title": "CSS: caixas, fluxo e posicionamento",
    "body": "Entenda como conteúdo, padding, borda e margem formam caixas e como elas participam do fluxo. Estude box-sizing, display, dimensões intrínsecas, overflow, colapso de margens, posicionamento e stacking contexts para diagnosticar cortes e sobreposições sem depender de ajustes aleatórios.",
    "level": "Fundamentos",
    "topics": [
      "box model box-sizing",
      "block inline inline-block",
      "normal flow intrinsic sizing",
      "margin collapse",
      "overflow scroll clipping",
      "position relative absolute fixed sticky",
      "containing blocks",
      "stacking context z-index",
      "logical properties writing modes"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-caixas-intrinseco",
    "track": "css-completo",
    "title": "CSS: dimensões de caixa, conteúdo intrínseco e overflow",
    "body": "Calcule o espaço que uma caixa ocupa e investigue por que um texto comprido pode quebrar o layout. Esta aula compara content-box e border-box, limites de tamanho em Flexbox e rolagem dentro de um contêiner. Os exercícios medem caixas no navegador e tratam conteúdos adversos sem esconder o problema com overflow indiscriminado.",
    "level": "Fundamentos",
    "topics": [
      "content-box e dimensão externa",
      "border-box e espaço de conteúdo",
      "padding e border no cálculo",
      "tamanho mínimo automático de flex item",
      "min-inline-size zero",
      "overflow-wrap anywhere",
      "overflow e contêiner de rolagem",
      "sticky e referência de rolagem"
    ],
    "language": "html",
    "source": "https://www.w3.org/TR/css-sizing-3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-flex-grid",
    "track": "css-completo",
    "title": "CSS: Flexbox, Grid e alinhamento",
    "body": "Escolha Flexbox ou Grid pela relação entre itens e espaço, compreendendo eixos, tamanhos, distribuição e ordem. Estude tracks, fr, minmax, auto-fit, alinhamento e subgrid, preservando a sequência do documento e tratando o tamanho mínimo do conteúdo para evitar layouts frágeis.",
    "level": "Intermediário",
    "topics": [
      "flex axes wrap basis grow shrink",
      "alignment gap auto margins",
      "flex min-size",
      "grid tracks fr minmax",
      "auto-fit auto-fill",
      "explicit implicit placement",
      "grid areas subgrid",
      "source order accessibility"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-grid-trilhas",
    "track": "css-completo",
    "title": "CSS: trilhas de Grid, tamanho mínimo e ordem de leitura",
    "body": "Modele linhas, colunas e espaços de uma grade, calcule quantas trilhas cabem e diferencie auto-fill de auto-fit. Investigue conteúdo que força overflow, trilhas implícitas e a diferença entre posição visual, ordem do DOM e foco. Verifique o layout por medidas reais e pelo teclado, sem confundir uma disposição que parece correta com um contrato de leitura preservado.",
    "level": "Intermediário",
    "topics": [
      "grade bidimensional e linhas",
      "trilhas explícitas e implícitas",
      "fr e espaço disponível",
      "minmax zero e mínimo intrínseco",
      "auto-fill e auto-fit",
      "gap e contagem de trilhas",
      "auto-placement dense",
      "ordem DOM foco e visual"
    ],
    "language": "html",
    "source": "https://www.w3.org/TR/css-grid-1/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-responsivo",
    "track": "css-completo",
    "title": "CSS: responsividade, consultas e dimensões fluidas",
    "body": "Projete componentes que se adaptam ao espaço, texto e preferências do usuário. Aprenda media queries, container queries, clamp, unidades de viewport, imagens responsivas e estratégias de reflow, escolhendo pontos de mudança a partir do conteúdo em vez de uma lista fixa de aparelhos.",
    "level": "Avançado",
    "topics": [
      "media queries content breakpoints",
      "container queries inline-size",
      "clamp min max calc",
      "viewport svh lvh dvh",
      "reflow zoom text",
      "responsive images aspect-ratio",
      "prefers-color-scheme reduced-motion",
      "pointer hover capabilities"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-containers-contexto",
    "track": "css-completo",
    "title": "CSS: container queries, contexto e limites",
    "body": "Construa componentes que respondem ao espaço que realmente recebem. Investigue qual ancestral é consultado, o que muda ao nomeá-lo, por que o próprio elemento não responde à sua consulta e como validar os limites sem trocar a ordem de leitura. Compare regras condicionais, unidades cqi e uma base utilizável sem o aprimoramento.",
    "level": "Avançado",
    "topics": [
      "ancestral elegível e dimensão inline",
      "contêiner nomeado em contexto aninhado",
      "consulta não mede o próprio elemento",
      "limiares inclusivos e caixa de conteúdo",
      "containment e tamanho intrínseco",
      "unidades cqi e ancestral elegível",
      "fallback progressivo com supports",
      "ordem semântica e conteúdo longo"
    ],
    "language": "html",
    "source": "https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Containment/Container_queries",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-visual-movimento",
    "track": "css-completo",
    "title": "CSS: tipografia, cor e movimento",
    "body": "Trabalhe com apresentação visual sem perder legibilidade, contraste e controle do usuário. Estude tipografia, fontes, cores, fundos, gradientes, transformações, transições e animações, compreendendo custos de renderização e o uso de preferências para reduzir movimento desnecessário.",
    "level": "Avançado",
    "topics": [
      "font stacks web fonts loading",
      "line-height measure text",
      "color contrast modern color spaces",
      "background gradients borders shadows",
      "transforms transitions",
      "keyframes animation timing",
      "reduced motion",
      "render layout paint composite"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "css-arquitetura",
    "track": "css-completo",
    "title": "CSS: arquitetura, compatibilidade e depuração",
    "body": "Organize estilos para evoluir um produto sem conflitos crescentes, usando tokens, componentes, camadas e regras claras. Estude suporte de recursos, @supports, escopo, estratégias de fallback e testes de produção, relacionando manutenção, acessibilidade e desempenho à experiência que o usuário realmente percorre.",
    "level": "Especialização",
    "topics": [
      "tokens themes component APIs",
      "layers scope naming",
      "supports progressive enhancement",
      "compatibility fallback",
      "contain content-visibility",
      "logical properties internationalization",
      "DevTools computed layout",
      "visual regression states",
      "dead CSS maintenance"
    ],
    "language": "html",
    "source": "https://www.w3.org/Style/CSS/specs.en.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-tipos-controle",
    "track": "csharp-completo",
    "title": "C#: tipos, valores e controle de fluxo",
    "body": "Compreenda o papel de C# e do runtime .NET, escreva programas com contratos explícitos e diferencie tipos por valor e por referência. Estude números, texto, nullable, conversões, decisões, repetição e tratamento de erros, incluindo limites que a compilação não resolve automaticamente.",
    "level": "Fundamentos",
    "topics": [
      "dotnet project build runtime",
      "value reference types",
      "int long double decimal",
      "checked conversions",
      "string char Unicode",
      "nullable reference value types",
      "if switch pattern matching",
      "loops methods parameters",
      "exceptions contracts"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-decimal-limites",
    "track": "csharp-completo",
    "title": "C#: valores decimais, arredondamento e overflow",
    "body": "Calcule preços com uma política explícita de unidade, precisão e arredondamento. Esta aula compara decimal e double, mostra por que checked deve envolver a operação que pode estourar e usa uma cultura fixa nos exemplos. Os exercícios tratam desconto, limites de inteiros e ausência sem substituir erro por zero ou depender da configuração regional do computador.",
    "level": "Fundamentos",
    "topics": [
      "literal decimal com sufixo m",
      "decimal e double",
      "arredondamento com MidpointRounding",
      "cultura na apresentação",
      "checked no ponto da operação",
      "TryParse e contrato de formato",
      "nullable e ausência",
      "limite numérico antes de converter"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-metodos-parametros",
    "track": "csharp-completo",
    "title": "C#: métodos, parâmetros e estado compartilhado",
    "body": "Leia uma assinatura de método como um contrato sobre valores, referências e falhas. Você vai comparar alteração de objeto com troca da referência local, usar out no padrão Try e escrever uma função que valida antes de modificar estado. Os problemas praticam resultado independente e classificação de entrada sem assumir que toda passagem por valor isola um objeto mutável.",
    "level": "Fundamentos",
    "topics": [
      "passagem por valor",
      "cópia de referência de classe",
      "ref para trocar a variável",
      "out e padrão Try",
      "validação antes da mutação",
      "array copiado versus compartilhado",
      "retorno e efeito observável",
      "exceção como parte do contrato"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-colecoes-linq",
    "track": "csharp-completo",
    "title": "C#: genéricos, coleções e LINQ",
    "body": "Escolha coleções e use genéricos para preservar contratos, depois transforme dados com LINQ entendendo avaliação adiada e materialização. Estude IEnumerable, listas, dicionários, conjuntos, agrupamento, ordenação e IQueryable, reconhecendo quando uma expressão vira trabalho local ou uma consulta de outro provedor.",
    "level": "Intermediário",
    "topics": [
      "List Dictionary HashSet",
      "generic constraints variance",
      "IEnumerable IEnumerator",
      "LINQ Where Select OrderBy GroupBy",
      "deferred execution materialization",
      "First Single Any",
      "IQueryable providers",
      "complexity multiple enumeration"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-objetos-contratos",
    "track": "csharp-completo",
    "title": "C#: objetos, interfaces, records e padrões",
    "body": "Modele regras com encapsulamento e interfaces, usando composição, records, herança e pattern matching conforme o contrato. Entenda igualdade, imutabilidade, delegates e eventos para criar componentes testáveis sem hierarquias artificiais ou estado interno exposto.",
    "level": "Avançado",
    "topics": [
      "classes structs records",
      "constructors properties init required",
      "interfaces composition inheritance",
      "virtual override abstract sealed",
      "value equality record copying",
      "pattern matching switch",
      "delegates lambdas events",
      "operator overload contracts"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-assincrono-recursos",
    "track": "csharp-completo",
    "title": "C#: async, cancelamento e recursos",
    "body": "Organize operações assíncronas com Task, await e cancelamento cooperativo, mantendo propagação de falhas e liberação de recursos. Estude composição, limites, IDisposable, IAsyncDisposable, streams assíncronos e o risco de bloquear uma operação assíncrona com Result ou Wait.",
    "level": "Avançado",
    "topics": [
      "Task async await",
      "Task.WhenAll WhenAny",
      "CancellationToken cooperative",
      "timeouts bounded concurrency",
      "IDisposable using",
      "IAsyncDisposable await using",
      "IAsyncEnumerable await foreach",
      "async void contexts",
      "deadlocks Result Wait"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-iteradores-descarte",
    "track": "csharp-completo",
    "title": "C#: iteradores, execução adiada e descarte de recursos",
    "body": "Entenda quando uma sequência executa seu código, como MoveNext suspende e retoma um iterador, por que uma nova enumeração pode repetir efeitos e quando recursos são descartados. Separe a validação imediata da produção adiada, escolha conscientemente entre uma coleção viva e um snapshot, e prove a limpeza mesmo quando o consumidor para antes do fim.",
    "level": "Avançado",
    "topics": [
      "chamada de iterador e execução adiada",
      "MoveNext Current e suspensão",
      "IEnumerable e nova enumeração",
      "yield em try finally",
      "Dispose no encerramento do foreach",
      "validação no momento da chamada",
      "LINQ reenumeração e materialização",
      "captura de coleção mutável"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/yield",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-runtime-avancado",
    "track": "csharp-completo",
    "title": "C#: runtime, memória e recursos avançados",
    "body": "Estude recursos avançados a partir de um problema medido: boxing, structs, spans, memória, delegates, reflection, attributes, source generators e interoperabilidade. Relacione esses mecanismos a custos e contratos de vida, evitando trocar clareza por uma otimização sem evidência.",
    "level": "Avançado",
    "topics": [
      "GC allocations boxing",
      "struct readonly ref struct",
      "Span ReadOnlySpan Memory",
      "stackalloc lifetime",
      "generics constraints",
      "reflection attributes",
      "source generators trimming AOT",
      "unsafe pointers interop",
      "profiling benchmarking"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cs-engenharia",
    "track": "csharp-completo",
    "title": "C#: testes, pacotes e arquitetura .NET",
    "body": "Evolua exemplos em soluções .NET reproduzíveis, com contratos, testes, dependências e publicação verificadas. Estude organização, injeção de dependências, APIs, persistência e observação, mantendo regras de domínio separadas de frameworks e tratando compatibilidade como parte do produto.",
    "level": "Especialização",
    "topics": [
      "solutions projects references NuGet",
      "unit integration end-to-end tests",
      "dependency injection lifetimes",
      "ASP.NET middleware APIs",
      "EF Core transactions migrations",
      "logging configuration secrets",
      "publish trimming AOT",
      "architecture domain adapters",
      "versioning compatibility"
    ],
    "language": "csharp",
    "source": "https://learn.microsoft.com/pt-br/dotnet/csharp/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-modelagem-completa",
    "track": "sql-completo",
    "title": "SQL: modelo relacional, tipos e integridade",
    "body": "Modele dados antes de escrever consultas, distinguindo entidades, relações, chaves e restrições. Aprenda DDL, tipos, NULL e normalização com exemplos PostgreSQL, definindo regras de integridade no banco em vez de depender somente da aplicação para evitar estados inválidos.",
    "level": "Fundamentos",
    "topics": [
      "relations rows columns keys",
      "CREATE ALTER DROP schema",
      "primary foreign unique keys",
      "NOT NULL CHECK DEFAULT",
      "NULL three-valued logic",
      "numeric text boolean dates",
      "normalization dependencies",
      "INSERT UPDATE DELETE RETURNING",
      "PostgreSQL dialect"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-null-logica",
    "track": "sql-completo",
    "title": "SQL: NULL, lógica de três valores e dados ausentes",
    "body": "Escreva consultas que distinguem valor zero, valor ausente e comparação desconhecida. Esta aula usa PostgreSQL para explicar WHERE, CHECK, IS NULL, IS DISTINCT FROM, agregações e o risco de NOT IN com NULL. Todos os exemplos criam dados temporários e desfazem a transação, com verificações executadas sobre o resultado real.",
    "level": "Fundamentos",
    "topics": [
      "NULL como ausência de valor",
      "comparação com resultado unknown",
      "WHERE aceita apenas true",
      "IS NULL e IS NOT NULL",
      "IS DISTINCT FROM",
      "CHECK e NOT NULL",
      "count estrela versus count coluna",
      "NOT IN com NULL e NOT EXISTS"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/functions-comparison.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-consultas-joins",
    "track": "sql-completo",
    "title": "SQL: consultas, joins e composição",
    "body": "Construa consultas entendendo cardinalidade, filtros e a ordem lógica das operações. Estude joins internos e externos, subconsultas, EXISTS, operações de conjunto, CTEs e paginação, evitando duplicações acidentais e o erro de transformar um LEFT JOIN em INNER JOIN por um filtro mal colocado.",
    "level": "Intermediário",
    "topics": [
      "SELECT FROM WHERE order logic",
      "INNER LEFT RIGHT FULL CROSS JOIN",
      "join cardinality aliases",
      "EXISTS NOT EXISTS correlated",
      "UNION ALL INTERSECT EXCEPT",
      "CTEs composition",
      "ORDER BY LIMIT keyset pagination",
      "LATERAL",
      "parameterized queries"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-joins-cardinalidade",
    "track": "sql-completo",
    "title": "SQL: cardinalidade de joins e agregação sem duplicar totais",
    "body": "Preveja quantas linhas uma junção pode produzir e escolha a granularidade do resultado antes de somar. Esta aula investiga LEFT JOIN, filtros em ON ou WHERE, count em linhas estendidas e multiplicação de relações um-para-muitos. Os problemas usam dados temporários com clientes sem pedido e pedidos com vários itens e pagamentos.",
    "level": "Intermediário",
    "topics": [
      "granularidade antes da consulta",
      "cardinalidade um para muitos",
      "LEFT JOIN e linha estendida",
      "filtro em ON versus WHERE",
      "count da chave relacionada",
      "agregação antes do join",
      "fanout entre duas coleções",
      "EXISTS para testar presença"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/queries-table-expressions.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-agregacoes-janelas",
    "track": "sql-completo",
    "title": "SQL: agregações, janelas e análise",
    "body": "Produza relatórios com agregação e funções de janela sem perder a granularidade necessária. Estude GROUP BY, HAVING, COUNT, FILTER, ranking, acumulados, LAG, LEAD e frames, distinguindo agrupamento de análise por linha e explicando o efeito de empates e valores ausentes.",
    "level": "Avançado",
    "topics": [
      "GROUP BY HAVING",
      "count sum avg NULL",
      "aggregate FILTER distinct",
      "window PARTITION ORDER",
      "row_number rank dense_rank",
      "lag lead",
      "ROWS RANGE frames",
      "running totals",
      "grouping sets rollup"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-transacoes",
    "track": "sql-completo",
    "title": "SQL: transações, MVCC e concorrência",
    "body": "Defina operações atômicas e compreenda o que outras sessões podem observar durante uma transação. Estude commit, rollback, savepoints, MVCC, isolamento, locks, deadlocks e repetição de falhas, evitando tratar uma sequência de consultas independentes como uma operação indivisível.",
    "level": "Avançado",
    "topics": [
      "ACID BEGIN COMMIT ROLLBACK",
      "savepoints",
      "MVCC snapshots",
      "read committed repeatable read serializable",
      "lost updates write skew",
      "SELECT FOR UPDATE",
      "deadlocks ordering",
      "retry idempotency",
      "constraints concurrency"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-isolamento-sessoes",
    "track": "sql-completo",
    "title": "PostgreSQL: transações, snapshots e conflitos entre sessões",
    "body": "Observe o mesmo dado por conexões diferentes e explique o que cada transação pode enxergar. Compare Read Committed e Repeatable Read com um cronograma explícito, reproduza SQLSTATE 40001 e reinicie a transação inteira com dados atuais. Separe atomicidade, restrições e isolamento, sem tratar uma sequência executada em uma única conexão como prova de concorrência.",
    "level": "Avançado",
    "topics": [
      "atomicidade BEGIN COMMIT ROLLBACK",
      "Read Committed e snapshot por comando",
      "Repeatable Read e snapshot da transação",
      "sessões separadas e cronograma observável",
      "atualização concorrente e SQLSTATE 40001",
      "repetição da transação inteira",
      "conexão encerrada e rollback pendente",
      "restrições de dados e isolamento"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/transaction-iso.html",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-indices-planos",
    "track": "sql-completo",
    "title": "SQL: índices, planos e otimização",
    "body": "Aprenda a investigar consultas com EXPLAIN e dados representativos, escolhendo índices pelo padrão de acesso. Estude B-tree, índices compostos, parciais e de expressão, estatísticas, scans, joins físicos e custos de escrita, evitando otimizações que apenas funcionam em uma tabela minúscula.",
    "level": "Especialização",
    "topics": [
      "EXPLAIN ANALYZE BUFFERS",
      "statistics ANALYZE estimates",
      "B-tree composite order",
      "partial expression covering indexes",
      "GIN GiST BRIN",
      "sequential index bitmap scans",
      "join strategies",
      "sargability",
      "write costs maintenance"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "sql-esquema-avancado",
    "track": "sql-completo",
    "title": "SQL: views, recursão, JSON e evolução",
    "body": "Componha estruturas e rotinas avançadas sem perder integridade ou compatibilidade. Estude views, materialização, CTEs recursivas, JSONB, funções, triggers, particionamento, permissões e migrations, definindo fontes de verdade e estratégias de atualização para cada recurso.",
    "level": "Especialização",
    "topics": [
      "views materialized refresh",
      "recursive CTE termination cycles",
      "JSONB operators indexes",
      "functions procedures triggers",
      "generated identity columns",
      "partitioning pruning",
      "roles grants least privilege",
      "schema migrations compatibility",
      "backup restore verification"
    ],
    "language": "sql",
    "source": "https://www.postgresql.org/docs/current/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  }
];
const loaders:Record<string,()=>Promise<{default:DeepCourse}>>={"python-completo":()=>import('./python'),"typescript-completo":()=>import('./typescript'),"cpp-completo":()=>import('./cpp'),"javascript-completo":()=>import('./javascript'),"html-completo":()=>import('./html'),"css-completo":()=>import('./css'),"csharp-completo":()=>import('./csharp'),"sql-completo":()=>import('./sql')};
const pending=new Map<string,Promise<DeepCourse>>();
export async function resolveExpandedLesson(id:string):Promise<Lesson|undefined>{
 const metadata=expandedLessons.find(l=>l.id===id);if(!metadata)return;
 let promise=pending.get(metadata.track);
 if(!promise){promise=loaders[metadata.track]().then(module=>module.default);pending.set(metadata.track,promise);promise.catch(()=>pending.delete(metadata.track));}
 const course=await promise,entry=course.lessons.find(l=>l.id===id);
 return entry?materialize(course,entry):undefined;
}
