import type {Course,Lesson} from '../curriculum';
import {materialize,type DeepCourse} from './types';
export const expandedCourses:Course[]=[
  {
    "id": "python-completo",
    "title": "Python · do zero ao avançado",
    "description": "Tipos, coleções, funções, objetos, biblioteca padrão, concorrência e engenharia de projetos.",
    "icon": "file-code-2",
    "lessonIds": [
      "py-fundamentos",
      "py-colecoes-funcoes",
      "py-objetos-protocolos",
      "py-biblioteca-dados",
      "py-concorrencia",
      "py-engenharia"
    ]
  },
  {
    "id": "typescript-completo",
    "title": "TypeScript · do zero ao avançado",
    "description": "JavaScript tipado, narrowing, contratos, genéricos, tipos avançados e integração com dados reais.",
    "icon": "braces",
    "lessonIds": [
      "ts-fundamentos",
      "ts-contratos",
      "ts-genericos",
      "ts-tipos-avancados",
      "ts-modulos-configuracao",
      "ts-fronteiras-qualidade"
    ]
  },
  {
    "id": "cpp-completo",
    "title": "C++ · do zero ao avançado",
    "description": "Compilação, tipos, funções, RAII, STL, templates, memória, concorrência e desempenho.",
    "icon": "file-code-2",
    "lessonIds": [
      "cpp-fundamentos",
      "cpp-classes-raii",
      "cpp-stl-algoritmos",
      "cpp-templates",
      "cpp-memoria-posse",
      "cpp-concorrencia-engenharia"
    ]
  }
];
export const expandedLessons:Lesson[]=[
  {
    "id": "py-fundamentos",
    "track": "python-completo",
    "title": "Python: execução, tipos e controle",
    "body": "Construa seu primeiro programa Python entendendo a execução do arquivo, a indentação e a relação entre nomes e objetos. Estude números, strings, booleanos, conversões, entrada e saída, decisões, repetição e os casos de limite que distinguem um programa previsível de um exemplo que só funciona com uma entrada.",
    "level": "Fundamentos",
    "topics": [
      "interpretador e REPL",
      "indentação",
      "int float bool None",
      "str e Unicode",
      "conversões e entrada",
      "if elif else",
      "for range while",
      "break continue else",
      "comparação e identidade"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-colecoes-funcoes",
    "track": "python-completo",
    "title": "Python: coleções, funções e iteração",
    "body": "Aprenda a escolher list, tuple, dict e set pelo contrato dos dados, escrever funções com parâmetros claros e percorrer coleções sem modificar acidentalmente seus elementos. Conecte fatiamento, comprehensions, desempacotamento, escopo, closures, iteradores e geradores a problemas de transformação e agregação.",
    "level": "Intermediário",
    "topics": [
      "list tuple dict set",
      "mutabilidade e cópia",
      "slicing e desempacotamento",
      "comprehensions",
      "parâmetros posicionais e nomeados",
      "args kwargs",
      "escopo LEGB closures",
      "iteradores e yield",
      "complexidade"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-objetos-protocolos",
    "track": "python-completo",
    "title": "Python: classes, protocolos e metaprogramação",
    "body": "Modele objetos por responsabilidades e contratos, usando classes, dataclasses, propriedades e composição. Entenda o sistema de atributos, métodos especiais, herança, super, protocolos, decoradores e context managers para criar APIs previsíveis, sem recorrer a mecanismos avançados quando uma função simples resolve o problema.",
    "level": "Avançado",
    "topics": [
      "classes instâncias self",
      "dataclasses",
      "herança composição MRO super",
      "property descritores",
      "dunder repr eq hash",
      "duck typing protocolos",
      "decoradores functools.wraps",
      "context managers",
      "slots metaclasses"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-biblioteca-dados",
    "track": "python-completo",
    "title": "Python: arquivos, exceções e biblioteca padrão",
    "body": "Aprenda a trabalhar com recursos reais usando pathlib, arquivos Unicode, JSON, CSV, datas, expressões regulares e coleções especializadas. Estabeleça fronteiras de validação, trate exceções específicas e escreva arquivos com uma estratégia que não deixe resultados parciais silenciosamente.",
    "level": "Intermediário",
    "topics": [
      "pathlib arquivos encoding",
      "with e exceções",
      "JSON CSV validação",
      "datetime zoneinfo",
      "decimal fractions",
      "collections itertools functools",
      "re Unicode",
      "logging argparse",
      "os subprocess segurança"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-concorrencia",
    "track": "python-completo",
    "title": "Python: concorrência, async e paralelismo",
    "body": "Distinga concorrência de paralelismo e escolha entre asyncio, threads e processos pelo tipo de trabalho. Estude corrotinas, tarefas, cancelamento, limites, filas, sincronização, tratamento de falhas e o impacto do runtime, evitando supor que escrever async torna uma operação bloqueante automaticamente assíncrona.",
    "level": "Avançado",
    "topics": [
      "concorrência versus paralelismo",
      "async await corrotinas",
      "TaskGroup cancelamento",
      "timeouts semáforos filas",
      "threads locks",
      "ProcessPoolExecutor",
      "GIL builds free-threaded",
      "backpressure",
      "falhas e recursos"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "py-engenharia",
    "track": "python-completo",
    "title": "Python: tipagem, testes, pacotes e desempenho",
    "body": "Transforme scripts em projetos reproduzíveis, com ambientes isolados, módulos bem delimitados, anotação de tipos, testes úteis e medição de desempenho. Aprenda a documentar contratos e distribuir pacotes, relacionando ferramentas de engenharia às falhas que elas realmente conseguem detectar.",
    "level": "Especialização",
    "topics": [
      "módulos imports __main__",
      "venv pip pyproject.toml",
      "typing Protocol Generic",
      "testes unittest mocks",
      "propriedades casos de borda",
      "profiling timeit tracemalloc",
      "algoritmos complexidade",
      "distribuição wheels",
      "documentação e evolução"
    ],
    "language": "python",
    "source": "https://docs.python.org/3/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-fundamentos",
    "track": "typescript-completo",
    "title": "TypeScript: tipos, inferência e execução",
    "body": "Entenda o que TypeScript verifica antes da execução e o que permanece responsabilidade do JavaScript. Aprenda inferência, tipos primitivos, arrays, tuplas, literal types, uniões, null e undefined, distinguindo erros do compilador de validação dos dados que chegam durante a execução.",
    "level": "Fundamentos",
    "topics": [
      "tsc e apagamento de tipos",
      "inferência",
      "string number boolean",
      "arrays readonly tuples",
      "literal types unions",
      "strictNullChecks",
      "unknown versus any",
      "type assertions satisfies"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-contratos",
    "track": "typescript-completo",
    "title": "TypeScript: objetos, narrowing e uniões discriminadas",
    "body": "Descreva modelos com type e interface, compreenda tipagem estrutural e refine valores por controle de fluxo. Use uniões discriminadas para representar estados possíveis e impossíveis, mantendo decisões exaustivas e evitando objetos cheios de propriedades opcionais cuja combinação não tem significado.",
    "level": "Intermediário",
    "topics": [
      "type interface tipagem estrutural",
      "optional readonly",
      "excess property checks",
      "typeof in instanceof",
      "type predicates assertions",
      "discriminated unions",
      "never exhaustiveness",
      "intersections index signatures"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-genericos",
    "track": "typescript-completo",
    "title": "TypeScript: genéricos, coleções e variância",
    "body": "Use genéricos para preservar relações entre tipos de entrada e saída, imponha constraints proporcionais ao que a função realmente usa e componha funções sem apagar informações com any. Explore keyof, indexed access, overloads, parâmetros padrão, callbacks e os cuidados de variância em coleções mutáveis.",
    "level": "Avançado",
    "topics": [
      "generic functions interfaces",
      "constraints extends",
      "keyof indexed access",
      "defaults inference",
      "overloads",
      "callbacks variance",
      "readonly collections",
      "generic classes factories"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-tipos-avancados",
    "track": "typescript-completo",
    "title": "TypeScript: transformação e programação de tipos",
    "body": "Explore mapped types, conditional types, infer e template literal types como ferramentas para derivar contratos de uma fonte comum. Entenda distribuição sobre uniões, utilitários e limites de legibilidade, evitando tornar o sistema de tipos um programa complexo que a equipe não consegue manter.",
    "level": "Avançado",
    "topics": [
      "mapped types modifiers",
      "Pick Omit Partial Required Readonly",
      "Record Exclude Extract",
      "conditional types distribution",
      "infer ReturnType Parameters Awaited",
      "template literal types",
      "key remapping",
      "recursive types limits"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-modulos-configuracao",
    "track": "typescript-completo",
    "title": "TypeScript: módulos, configuração e declarações",
    "body": "Configure TypeScript de acordo com o ambiente onde o JavaScript será executado. Aprenda target, lib, module, moduleResolution, strict, arquivos de declaração e organização de bibliotecas, distinguindo suporte de sintaxe, disponibilidade de APIs e resolução real de arquivos.",
    "level": "Especialização",
    "topics": [
      "tsconfig strict",
      "target lib module",
      "NodeNext bundler resolution",
      "ESM CommonJS",
      "import type verbatimModuleSyntax",
      "declaration d.ts",
      "ambient declarations",
      "project references",
      "source maps packaging"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "ts-fronteiras-qualidade",
    "track": "typescript-completo",
    "title": "TypeScript: validação, assíncrono e qualidade",
    "body": "Conecte contratos estáticos a dados recebidos por JSON, formulários e APIs, usando validação explícita e resultados discriminados. Explore promises, cancelamento, testes de tipos e execução, arquitetura de fronteiras e migração gradual de JavaScript sem esconder problemas com casts e any.",
    "level": "Especialização",
    "topics": [
      "JSON unknown validation",
      "Result discriminated unions",
      "Promise async errors",
      "AbortController",
      "static versus runtime tests",
      "ts-expect-error",
      "gradual migration checkJs JSDoc",
      "domain DTO boundaries",
      "security and serialization"
    ],
    "language": "typescript",
    "source": "https://www.typescriptlang.org/docs/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-fundamentos",
    "track": "cpp-completo",
    "title": "C++: compilação, tipos e controle",
    "body": "Aprenda a transformar arquivos C++ em um programa executável, compreender diagnósticos de compilação e estabelecer contratos de tipos e entrada. Estude inicialização, conversões, expressões, decisões, repetição e funções, reconhecendo desde o início os limites dos números e o perigo de comportamento indefinido.",
    "level": "Fundamentos",
    "topics": [
      "compilação ligação main",
      "headers namespaces",
      "tipos fundamentais auto",
      "inicialização narrowing",
      "signed unsigned overflow",
      "if switch loops",
      "funções parâmetros retorno",
      "const constexpr",
      "entrada e streams"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-classes-raii",
    "track": "cpp-completo",
    "title": "C++: classes, RAII e semântica de valor",
    "body": "Projete classes que estabelecem invariantes na construção e liberam recursos automaticamente. Aprenda encapsulamento, construtores, destrutores, cópia, movimento, rule of zero, composição e polimorfismo, distinguindo objetos que representam valores daqueles que controlam a posse de um recurso.",
    "level": "Intermediário",
    "topics": [
      "struct class encapsulamento",
      "constructors invariants",
      "RAII destructors",
      "rule of zero five",
      "copy move semantics",
      "composition inheritance",
      "virtual destructor slicing",
      "exceptions guarantees",
      "explicit const methods"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-stl-algoritmos",
    "track": "cpp-completo",
    "title": "C++: STL, iteradores, algoritmos e ranges",
    "body": "Escolha contêineres pela forma de acesso, conheça invalidação de iteradores e substitua laços frágeis por algoritmos com contratos claros. Estude vector, array, map, unordered_map, set, lambdas, comparadores, ranges e complexidade para transformar dados preservando segurança e previsibilidade.",
    "level": "Intermediário",
    "topics": [
      "vector array deque list",
      "map set unordered_map",
      "iterator categories invalidation",
      "algorithms sort find accumulate",
      "lambdas captures",
      "comparators strict weak ordering",
      "ranges views lifetime",
      "complexity"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-templates",
    "track": "cpp-completo",
    "title": "C++: templates, concepts e avaliação constante",
    "body": "Crie algoritmos genéricos com requisitos explícitos, entenda instanciação e diagnósticos de templates e use concepts para expressar capacidades. Explore dedução, overloads, constexpr, if constexpr, variádicos e type traits, mantendo a abstração proporcional às necessidades do código.",
    "level": "Avançado",
    "topics": [
      "function class templates",
      "deduction instantiation",
      "concepts requires",
      "constraints overloads",
      "if constexpr type_traits",
      "variadic templates folds",
      "constexpr consteval",
      "specialization ODR headers"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-memoria-posse",
    "track": "cpp-completo",
    "title": "C++: memória, posse e segurança de vida",
    "body": "Entenda duração de armazenamento, vida de objetos, ponteiros, referências e categorias de valor para evitar acessos pendentes. Use unique_ptr, shared_ptr, weak_ptr, span, string_view, optional e variant com contratos explícitos de posse, reconhecendo custos e condições de validade.",
    "level": "Avançado",
    "topics": [
      "storage duration lifetime",
      "pointers references nullptr",
      "unique_ptr shared_ptr weak_ptr",
      "ownership cycles",
      "span string_view dangling",
      "value categories move forwarding",
      "optional variant visit",
      "alignment allocation placement",
      "sanitizers UB"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  },
  {
    "id": "cpp-concorrencia-engenharia",
    "track": "cpp-completo",
    "title": "C++: concorrência, build e desempenho",
    "body": "Aprenda a organizar trabalho concorrente e medir desempenho sem comprometer correção. Estude threads, jthread, sincronização, atomics, futures e cancelamento, conectando o modelo de memória a testes, sanitizers, sistemas de build, unidades de tradução e escolhas de arquitetura.",
    "level": "Especialização",
    "topics": [
      "thread jthread stop_token",
      "mutex scoped_lock condition_variable",
      "atomics memory ordering",
      "data races deadlocks",
      "future async",
      "build headers CMake modules",
      "profiling benchmarks",
      "cache locality false sharing",
      "coroutines custom awaitables"
    ],
    "language": "cpp",
    "source": "https://eel.is/c++draft/",
    "capitulos": [],
    "code": "",
    "exercise": "",
    "solution": "",
    "error": "",
    "question": "",
    "options": [],
    "correct": 0
  }
];
const loaders:Record<string,()=>Promise<{default:DeepCourse}>>={"python-completo":()=>import('./python'),"typescript-completo":()=>import('./typescript'),"cpp-completo":()=>import('./cpp')};
const pending=new Map<string,Promise<DeepCourse>>();
export async function resolveExpandedLesson(id:string):Promise<Lesson|undefined>{
 const metadata=expandedLessons.find(l=>l.id===id);if(!metadata)return;
 let promise=pending.get(metadata.track);
 if(!promise){promise=loaders[metadata.track]().then(module=>module.default);pending.set(metadata.track,promise);promise.catch(()=>pending.delete(metadata.track));}
 const course=await promise,entry=course.lessons.find(l=>l.id===id);
 return entry?materialize(course,entry):undefined;
}
