import { progress,saveProgress,snapshot,escapeHtml as esc } from './state';
import { execute } from './execution/runner';
type Options={icon:(name:string)=>string;toast:(message:string)=>void;icons:()=>void;download:(name:string,content:string,type:string)=>void};
export function mountLaboratory(main:HTMLElement,projectId:string|undefined,options:Options):()=>void {
 const {icon,toast,icons,download}=options;const project=progress.projects.find(p=>p.id===projectId);let language=project?.language||'html',disposed=false,version=0;
 let editor:ReturnType<typeof import('./editor')['createEditor']>|undefined,execution:ReturnType<typeof execute>|undefined,controller:AbortController|undefined,remoteId:string|undefined,saveTimer:ReturnType<typeof setTimeout>|undefined;
 const drafts:Record<string,string>={html:progress.drafts['lab-html']??'<h1>Uma ideia começa aqui.</h1><p>Meu primeiro projeto.</p><button onclick="this.textContent=\'Você fez acontecer!\'">Experimente</button>',javascript:progress.drafts['lab-js']??'console.log("Olá, mundo!");',python:progress.drafts['lab-python']??'print("Olá, mundo!")',csharp:progress.drafts['lab-csharp']??'System.Console.WriteLine("Olá, mundo!");',cpp:progress.drafts['lab-cpp']??'#include <iostream>\nint main(){std::cout << "Olá, mundo!";}',sql:progress.drafts['lab-sql']??'SELECT 1 AS descoberta;',text:progress.drafts['lab-text']??''};if(project)drafts[language]=project.code;
 main.innerHTML=`<section class="page lab-page"><p class="eyebrow">LIBERDADE PARA EXPERIMENTAR</p><h1>Seu laboratório.</h1><p class="lead">${project?esc(project.title):'Uma ideia, um experimento, uma descoberta.'} Código salvo somente neste navegador.</p><div class="lab-toolbar"><label>Linguagem <select id="lab-language">${[['html','HTML + CSS + JavaScript'],['javascript','JavaScript isolado'],['python','Python · executor externo'],['csharp','C# · executor externo'],['cpp','C++ · executor externo'],['sql','SQL · escrever e exportar'],['text','Anotações · exportar']].map(([id,title])=>`<option value="${id}" ${language===id?'selected':''}>${title}</option>`).join('')}</select></label><div><button id="save-project" class="button subtle">${icon('check')} Salvar projeto</button><button id="export" class="button subtle">${icon('download')} Exportar</button><button id="lab-stop" class="button subtle">${icon('square')} Parar</button><button id="lab-run" class="button primary" disabled>${icon('play')} Executar</button></div></div><div class="lab-layout"><div id="lab-editor" class="editor"></div><section class="preview-panel"><h2>Seu resultado</h2><iframe id="preview" title="Resultado isolado do seu projeto" sandbox="allow-scripts" referrerpolicy="no-referrer"></iframe><pre id="lab-console" aria-live="polite" hidden></pre></section></div><p class="lab-note" id="lab-note"></p></section>`;
 const iframe=main.querySelector<HTMLIFrameElement>('#preview')!,consoleEl=main.querySelector<HTMLElement>('#lab-console')!,button=main.querySelector<HTMLButtonElement>('#lab-run')!;
 const persist=()=>{if(!editor)return;const code=editor.getValue().slice(0,30000);drafts[language]=code;progress.drafts[language==='javascript'?'lab-js':'lab-'+language]=code;if(project){project.code=code;project.language=language;project.updatedAt=new Date().toISOString();}saveProgress();};
 const stop=()=>{version++;execution?.cancel();execution=undefined;controller?.abort();controller=undefined;if(remoteId){void fetch('/api/executions/'+remoteId,{method:'DELETE',keepalive:true}).catch(()=>{});remoteId=undefined;}iframe.removeAttribute('srcdoc');iframe.src='about:blank';button.disabled=false;};
 const message=(text:string)=>{iframe.hidden=true;consoleEl.hidden=false;consoleEl.textContent=text;};
 const note=()=>{main.querySelector('#lab-note')!.textContent=language==='html'?'Preview isolado, sem rede ou localStorage. Execute apenas códigos conhecidos: scripts de página não têm o limite de CPU do JavaScript isolado. Para armazenamento e módulos, exporte e sirva por HTTP.':language==='javascript'?'JavaScript em worker descartável: 4 MiB de memória do interpretador, limite de tempo e saída. Sem DOM, rede ou temporizadores.':language==='sql'?'SQL pode ser escrito e exportado. Use uma base descartável no dialeto indicado na aula. A expansão usa PostgreSQL e os exemplos originais podem usar SQLite; esta bancada não contém um motor SQL.':language==='text'?'Anotações e roteiros podem ser editados e exportados; não são programas executáveis.':'Executar envia este código ao servidor .NET/Judge0 configurado, sem conta. Nenhum código é enviado antes de você acionar Executar. O SDK .NET local é necessário para projetos ASP.NET completos.';};
 const run=async()=>{if(!editor||disposed)return;stop();const revision=version;persist();const code=editor.getValue();if(code.length>30000){message('Limite de 30.000 caracteres. Divida o projeto em arquivos.');return;}if(language==='html'){iframe.hidden=false;consoleEl.hidden=true;const policy="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; connect-src 'none'; form-action 'none'; base-uri 'none';";const markup=/<html[\s>]/i.test(code)?code:'<!doctype html><html lang="pt-BR"><head></head><body>'+code+'</body></html>';const doc=new DOMParser().parseFromString(markup,'text/html');const meta=doc.createElement('meta');meta.httpEquiv='Content-Security-Policy';meta.content=policy;doc.head.prepend(meta);iframe.srcdoc='<!doctype html>'+doc.documentElement.outerHTML;return;}if(language==='sql'||language==='text'){message('Use Exportar para continuar no ambiente indicado pela aula.');return;}button.disabled=true;message('Executando…');try{if(language==='javascript'){const job=execute(code,'laboratorio');execution=job;const result=await job.result;if(disposed||revision!==version)return;message(result.error||result.logs.join('\n')||'O programa terminou sem mensagens. Use console.log() para observar os valores.');snapshot('lab-js',code);}else{controller=new AbortController();const signal=controller.signal;const timeout=setTimeout(()=>controller?.abort(),35000);try{const response=await fetch('/api/executions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language,code}),signal});if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Servidor de execução indisponível. HTML e JavaScript funcionam no navegador.');let job=await response.json();if(!response.ok)throw new Error(job.error||'Executor indisponível.');remoteId=job.id;for(let n=0;n<32&&['queued','running'].includes(job.status);n++){await new Promise<void>((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Cancelado','AbortError'));};const timer=setTimeout(()=>{signal.removeEventListener('abort',abort);resolve();},800);signal.addEventListener('abort',abort,{once:true});});const poll=await fetch('/api/executions/'+remoteId,{signal});if(!poll.ok)throw new Error('Resultado expirado ou executor indisponível.');job=await poll.json();}if(disposed||revision!==version)return;message(job.output||job.error||'A execução não terminou no prazo.');remoteId=undefined;}finally{clearTimeout(timeout);}}}catch(error){if(!disposed&&revision===version)message(error instanceof Error&&error.name==='AbortError'?'Execução interrompida por tempo limite.':String(error));}finally{if(!disposed&&revision===version){execution=undefined;button.disabled=false;}}};
 main.querySelector('#lab-stop')!.addEventListener('click',()=>{stop();message('Execução encerrada. Seu código continua na bancada.');});button.addEventListener('click',()=>void run());
 main.querySelector('#export')!.addEventListener('click',()=>{if(!editor)return;const extension:Record<string,string>={html:'html',javascript:'js',python:'py',csharp:'cs',cpp:'cpp',sql:'sql',text:'txt'};download('projeto.'+extension[language],editor.getValue(),'text/plain');});
 main.querySelector('#save-project')!.addEventListener('click',()=>{if(!editor)return;persist();if(project){toast('Projeto salvo neste navegador.');return;}if(progress.projects.length>=12){toast('Limite de 12 projetos. Exporte e remova um projeto antes de criar outro.');return;}const id=crypto.randomUUID();progress.projects.push({id,title:'Meu projeto '+(progress.projects.length+1),code:editor.getValue().slice(0,30000),language,updatedAt:new Date().toISOString()});saveProgress();location.hash='/laboratorio/'+id;toast('Projeto salvo separadamente.');});
 main.querySelector('#lab-language')!.addEventListener('change',async e=>{persist();stop();language=(e.target as HTMLSelectElement).value;const monaco=await import('monaco-editor/esm/vs/editor/editor.api');if(disposed||!editor)return;monaco.editor.setModelLanguage(editor.getModel()!,language==='text'?'plaintext':language);editor.setValue(drafts[language]||'');message('Bancada pronta. Execute quando quiser.');note();});
 void import('./editor').then(module=>{if(disposed)return;editor=module.createEditor(main.querySelector('#lab-editor')!,drafts[language],language,true);button.disabled=false;editor.onDidChangeModelContent(()=>{clearTimeout(saveTimer);saveTimer=setTimeout(persist,500);});note();if(!project&&language==='html'&&!progress.drafts['lab-html'])void run();else message('Seu código está salvo. Clique em Executar para iniciar.');}).catch(()=>{if(!disposed)message('Não foi possível carregar o editor. Recarregue a página.');});icons();
 return()=>{persist();disposed=true;clearTimeout(saveTimer);stop();editor?.dispose();iframe.remove();};
}
