import {courses,lessons} from './content/curriculum';
import {mountLaboratory} from './laboratory';
import { AmbientAudio } from './environment/audio';
import { createIcons, ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Boxes, Blocks, Braces, Castle, Check, ChevronRight, Circle, CircleCheck, CircleDot, CloudRain, CloudSun, Compass, Database, Download, FileCode2, Flag, FlaskConical, Hammer, History, House, Info, LampDesk, Layers, Leaf, LibraryBig, Lightbulb, ListChecks, LocateFixed, Maximize2, Network, NotebookPen, PanelsTopLeft, Play, RotateCcw, Route, ScanSearch, Search, ShieldCheck, Sparkles, Sprout, Square, Swords, Terminal, TowerControl, TreePine, Trees, Upload, UserRound, Volume2, VolumeX, Wind, X } from 'lucide';
const icons={ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Boxes,Blocks,Braces,Castle,Check,ChevronRight,Circle,CircleCheck,CircleDot,CloudRain,CloudSun,Compass,Database,Download,FileCode2,Flag,FlaskConical,Hammer,History,House,Info,LampDesk,Layers,Leaf,LibraryBig,Lightbulb,ListChecks,LocateFixed,Maximize2,Network,NotebookPen,PanelsTopLeft,Play,RotateCcw,Route,ScanSearch,Search,ShieldCheck,Sparkles,Sprout,Square,Swords,Terminal,TowerControl,TreePine,Trees,Upload,UserRound,Volume2,VolumeX,Wind,X};
import { missions, articles } from './content/missions';
import { progress, saveProgress, snapshot, recordResult, replaceProgress, prepareBackup, escapeHtml as esc } from './state';
import { defaultEnvironment, WeatherService, cities } from './environment/weather';
import { execute } from './execution/runner';
import type { EnvironmentState, RunResult } from './types';
import './style.css';

const icon=(name:string,cls='')=>`<i data-lucide="${name}" class="${cls}" aria-hidden="true"></i>`;
const app=document.querySelector<HTMLDivElement>('#app')!;
let world:import('./environment/world').LivingWorld|undefined;
let environment:EnvironmentState={...defaultEnvironment};
let cleanup=()=>{};
const ambientAudio=new AmbientAudio();
let soundEnabled=false;
let ambientVolume=0;
let flashesEnabled=false;
const weather=new WeatherService(data=>{environment=data;world?.setEnvironment(data);updateWeather();});

let toastTimer:ReturnType<typeof setTimeout>;
const nav=[['home','Início','house'],['aprender','Aprender','book-open'],['projetos','Projetos','blocks'],['laboratorio','Laboratório','flask-conical'],['biblioteca','Biblioteca','library-big'],['perfil','Perfil','user-round']];
const totalXp=()=>missions.filter(m=>progress.completed.includes(m.id)).reduce((a,m)=>a+m.xp,0);
const nextMission=()=>missions.find(m=>!progress.completed.includes(m.id))||missions[0];
app.innerHTML=`<div id="world" class="world" aria-hidden="true"></div><div class="room" aria-hidden="true"></div><div class="vignette" aria-hidden="true"></div>
 <header class="topbar"><a class="brand" href="#/home" aria-label="CODELAB início">C O D E L A B<span>IDEIAS EM APLICAÇÕES REAIS</span></a><div class="header-actions"><button class="search-button" id="search">${icon('search')}<span>Buscar lição, erro, projeto...</span><kbd>Ctrl K</kbd></button><button class="icon-button" id="environment" title="Configurar ambiente" aria-label="Configurar ambiente">${icon('cloud-sun')}</button><button class="icon-button" id="sound" title="Ativar som ambiente" aria-label="Ativar som ambiente" aria-pressed="false">${icon('volume-x')}</button><a href="#/perfil" class="profile-mini" aria-label="Abrir meu perfil"><span class="avatar">${icon('sprout')}</span><span><b id="mini-name">${esc(progress.name)}</b><small id="mini-level">Nível ${1+Math.floor(totalXp()/250)}</small><span class="tiny-progress"><span style="width:${totalXp()%250/2.5}%"></span></span></span></a></div></header>
 <nav class="sidebar" aria-label="Navegação principal">${nav.map(([id,label,i])=>`<a href="#/${id}" data-nav="${id}" title="${label}">${icon(i)}<span>${label}</span></a>`).join('')}<div class="sidebar-quote">“Disciplina hoje.<br>Liberdade amanhã.”<span></span></div><button class="environment-status" id="weather-status">${icon('wind')}<span>Um mundo vivo<small>Configurar ambiente</small></span></button></nav>
 <main id="main" tabindex="-1"></main><div id="toast" role="status" class="toast"></div><dialog id="dialog" aria-labelledby="dialog-title"></dialog>`;
const main=document.querySelector<HTMLElement>('#main')!;
const dialog=document.querySelector<HTMLDialogElement>('#dialog')!;
function refreshIcons(){createIcons({icons,attrs:{'stroke-width':1.5}});}
function toast(message:string){const el=document.querySelector('#toast')!;el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);}
function modal(title:string,content:string){dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-button close-dialog" aria-label="Fechar">${icon('x')}</button></div>${content}`;dialog.querySelector('.close-dialog')?.addEventListener('click',()=>dialog.close());if(!dialog.open)dialog.showModal();refreshIcons();}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function currentRoute(){return location.hash.slice(2)|| (location.pathname.startsWith('/conceitos/')?'artigo/'+location.pathname.split('/')[2]:'home');}
function go(route:string){location.hash='/'+route;}
function route(){cleanup();cleanup=()=>{};const [page,id]=currentRoute().split('/');document.body.dataset.page=page;world?.setActive(page==='home');document.querySelectorAll('[data-nav]').forEach(el=>{if(el.getAttribute('data-nav')===page)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});document.title=`${page==='home'?'Seu código transforma o mundo':nav.find(n=>n[0]===page)?.[1]||missions.find(m=>m.id===id)?.title||'Aprender fazendo'} — CODELAB`;main.innerHTML='';
 if(page==='home')home();else if(page==='aprender')learn();else if(page==='missao')void mission(id);else if(page==='laboratorio')cleanup=mountLaboratory(main,id,{icon,toast,icons:refreshIcons,download});else if(page==='aula')lesson(id);else if(page==='leitura')lesson(id,true);else if(page==='trilha')coursePage(id);else if(page==='projetos')projects();else if(page==='biblioteca')library();else if(page==='perfil')profile();else if(page==='artigo')article(id);else main.innerHTML=`<section class="page"><p class="eyebrow">404 · CAMINHO NÃO ENCONTRADO</p><h1>Esta ilha ainda não existe.</h1><a class="button primary" href="#/home">Voltar para casa</a></section>`;refreshIcons();main.scrollTop=0;
}
function home(){const next=nextMission(),done=progress.completed.length,pct=Math.round(done/missions.length*100);main.innerHTML=`<section class="home-view" aria-label="Sua casa no CODELAB"><div class="welcome"><p class="eyebrow">SEU LUGAR PARA CRIAR</p><h1>Seu código pode ir<br>mais longe do que<br>você imagina<span>.</span></h1><p>Um pequeno passo hoje.<br>Um mundo de possibilidades amanhã.</p><div class="welcome-rule"></div></div>
 <aside class="journey"><div class="section-label">SUA JORNADA ${icon('sparkles')}</div><div class="journey-progress"><div class="progress-ring" style="--progress:${pct}%"><span>${pct}<small>%</small></span></div><div><small>Trilha atual</small><h2>Fundamentos</h2><p>${done} de ${missions.length} missões</p></div></div><a class="button primary continue" href="#/missao/${next.id}">${done?'Continuar missão':'Acender a primeira luz'} ${icon('arrow-right')}</a><div class="up-next"><span>Seus próximos passos</span>${missions.slice(0,4).map((m,i)=>`<a href="#/missao/${m.id}" class="next-item ${progress.completed.includes(m.id)?'complete':''}">${icon(progress.completed.includes(m.id)?'circle-check':i===done?'circle-dot':'circle')}<span>${m.concept}</span>${i===done?icon('chevron-right'):''}</a>`).join('')}</div><div class="journey-footer">${icon('leaf')} Cada descoberta conta.</div></aside>
 <div class="atlas"><div class="atlas-heading"><span>O MUNDO ESTÁ À SUA ESPERA</span><h2>Escolha seu próximo destino.</h2></div><div class="destinations"><a href="#/aprender" class="destination active"><span class="destination-art">${icon('sprout')}</span><span>Fundamentos</span><small>O começo de tudo</small><span class="destination-state">${done?`${done}/8 descobertas`:'Comece por aqui'} ${icon('arrow-up-right')}</span></a><a href="#/laboratorio" class="destination"><span class="destination-art">${icon('panels-top-left')}</span><span>Front-end</span><small>Dê forma às suas ideias</small><span class="destination-state">Laboratório livre ${icon('arrow-up-right')}</span></a><a href="#/biblioteca" class="destination"><span class="destination-art">${icon('braces')}</span><span>Conhecimento</span><small>Conecte as peças</small><span class="destination-state">Explore os conceitos ${icon('arrow-up-right')}</span></a><a href="#/projetos" class="destination"><span class="destination-art">${icon('castle')}</span><span>Projetos reais</span><small>Construa o seu mundo</small><span class="destination-state">Da ideia à aplicação ${icon('arrow-up-right')}</span></a></div></div>
 <footer class="home-dock"><a href="#/aprender">${icon('compass')}<span><b>Explorar</b><small>Aprenda praticando</small></span></a><a href="#/missao/debug">${icon('swords')}<span><b>Desafios</b><small>Investigue. Resolva. Evolua.</small></span></a><a href="#/projetos">${icon('blocks')}<span><b>Projetos</b><small>Suas ideias, de verdade</small></span></a><a href="#/biblioteca">${icon('library-big')}<span><b>Biblioteca</b><small>Uma descoberta por vez</small></span></a><p>UM PROGRAMA<br>PODE MUDAR<br>TUDO.</p></footer></section>`;}
function learn(){main.innerHTML=`<section class="page"><p class="eyebrow">EXPLORE NO SEU RITMO</p><h1>Todo grande projeto<br>começa com uma descoberta.</h1><p class="lead">Escreva, execute e veja o mundo responder. Sua jornada começa nos fundamentos.</p><div class="section-title"><h2>Fundamentos da programação</h2><span>${progress.completed.length} / ${missions.length} concluídas</span></div><div class="mission-list">${missions.map((m,i)=>`<a href="#/missao/${m.id}" class="mission-row"><span class="mission-number ${progress.completed.includes(m.id)?'done':''}">${progress.completed.includes(m.id)?icon('check'):String(i+1).padStart(2,'0')}</span><span><small>${m.concept}</small><h3>${m.title}</h3><p>${m.summary}</p></span><span class="mission-meta">${m.minutes} min <b>+${m.xp} XP</b></span>${icon('arrow-up-right')}</a>`).join('')}</div><div class="section-title"><h2>Seu horizonte de aprendizado</h2></div><div class="trail-grid">${courses.map(c=>`<a href="#/trilha/${c.id}" class="trail">${icon(c.icon)}<h3>${c.title}</h3><p>${c.description}</p><small>${c.lessonIds.filter(id=>progress.lessons.includes(id)).length}/${c.lessonIds.length} aulas concluídas ${icon('arrow-right')}</small></a>`).join('')}</div></section>`;}
async function mission(id:string){const m=missions.find(x=>x.id===id);if(!m){go('aprender');return;}let disposed=false;let editor:ReturnType<typeof import('./editor')['createEditor']>|undefined;let execution:ReturnType<typeof execute>|undefined;let hint=progress.hints[id]||0;let saveTimer:ReturnType<typeof setTimeout>;let fontSize=15;cleanup=()=>{disposed=true;};
 main.innerHTML=`<section class="mission-page"><div class="mission-top"><a href="#/aprender" class="back">${icon('arrow-left')}<span>Fundamentos</span></a><span class="eyebrow">MISSÃO ${missions.indexOf(m)+1} DE ${missions.length}</span><button id="focus" class="button subtle">${icon('maximize-2')} Modo foco</button></div><div class="mission-title"><div><p class="eyebrow">${m.concept}</p><h1>${m.title}</h1></div><span class="reward">${icon('sparkles')} +${m.xp} XP</span></div><div class="mission-layout"><div class="instructions"><h2>Antes de começar</h2><p>${m.explanation}</p><div class="objective"><span>${icon('flag')} SUA MISSÃO</span><p>${m.objective}</p></div><button class="button subtle" id="hint">${icon('lightbulb')} Preciso de uma pista <small>${Math.min(hint,5)}/5</small></button><div id="hint-content" class="hint-content" aria-live="polite"></div><a class="reference" href="${m.reference}" target="_blank" rel="noopener">Consultar a referência MDN ${icon('arrow-up-right')}</a></div><div class="code-workspace"><div class="editor-bar"><span>${icon('file-code-2')} missao.js</span><div><button class="icon-button" id="font-size" aria-label="Aumentar fonte">A+</button><button class="icon-button" id="history" aria-label="Histórico de código">${icon('history')}</button><button class="icon-button" id="reset-code" aria-label="Restaurar código inicial">${icon('rotate-ccw')}</button></div></div><div id="editor" class="editor"><p class="editor-loading">Preparando sua bancada…</p></div><div class="run-bar"><span id="save-state">Salvo neste dispositivo</span><button class="button primary" id="run" disabled>${icon('play')} Executar <kbd>Ctrl ↵</kbd></button></div><div id="result" class="result" aria-live="polite"><span class="quiet">Execute para ver o que seu código faz.</span></div></div><div class="mission-world"><div class="world-caption"><span>SEU CÓDIGO GANHA VIDA</span>${icon('sparkles')}</div><div id="effect" class="effect"><div class="lantern">${icon(id==='ponte'?'route':id==='jardim'||id==='debug'?'trees':id==='inventario'?'boxes':id==='farol'?'tower-control':'lamp-desk')}</div><span>Aguardando sua primeira instrução.</span></div><div class="test-panel"><h2>O que vamos observar</h2><ul id="tests">${m.tests.map(t=>`<li>${icon('circle')} ${t}</li>`).join('')}</ul></div><div class="mission-phases"><span class="current">Entender</span><span>Escrever</span><span>Executar</span><span>Ver</span></div></div></div></section>`;
 const module=await import('./editor');if(disposed||currentRoute()!==`missao/${id}`)return;
 document.querySelector('#editor')!.innerHTML='';editor=module.createEditor(document.querySelector('#editor')!,progress.drafts[id]??m.starter,'javascript',progress.completed.length>=3);
 const runButton=document.querySelector<HTMLButtonElement>('#run')!;runButton.disabled=false;
 const run=async()=>{if(!editor)return;if(execution){execution.cancel();return;}const code=editor.getValue();snapshot(id,code);execution=execute(code,id);runButton.innerHTML=`${icon('square')} Cancelar`;refreshIcons();document.querySelector('#result')!.innerHTML='<span class="running">O mundo está ouvindo seu código…</span>';const result=await execution.result;execution=undefined;if(disposed)return;runButton.innerHTML=`${icon('play')} Executar <kbd>Ctrl ↵</kbd>`;recordResult(id,result.passed);showResult(result,m.id);refreshIcons();};
 runButton.addEventListener('click',run);const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();void run();}};window.addEventListener('keydown',key);
 editor.onDidChangeModelContent(()=>{const value=editor!.getValue();clearTimeout(saveTimer);document.querySelector('#save-state')!.textContent='Salvando…';saveTimer=setTimeout(()=>{progress.drafts[id]=value.slice(0,30000);saveProgress();if(!disposed)document.querySelector('#save-state')!.textContent='Salvo neste dispositivo';},500);});
 document.querySelector('#hint')!.addEventListener('click',()=>{hint=Math.min(hint+1,5);progress.hints[id]=hint;saveProgress();document.querySelector('#hint-content')!.innerHTML=`<small>PISTA ${hint} DE 5${hint===5?' · SOLUÇÃO':''}</small><pre>${esc(m.hints[hint-1])}</pre>`;document.querySelector('#hint small')!.textContent=`${hint}/5`;});
 document.querySelector('#focus')!.addEventListener('click',()=>{document.querySelector('.mission-page')!.classList.toggle('focused');});
 document.querySelector('#font-size')!.addEventListener('click',()=>{fontSize=fontSize>=23?15:fontSize+2;editor!.updateOptions({fontSize});});
 document.querySelector('#reset-code')!.addEventListener('click',()=>{snapshot(id,editor!.getValue());editor!.setValue(m.starter);toast('Código inicial restaurado. A versão anterior está no histórico.');});
 document.querySelector('#history')!.addEventListener('click',()=>{const versions=progress.history[id]||[];modal('Seu histórico de descobertas',versions.length?`<p>Selecione uma versão para restaurar. Seu código atual também será guardado.</p><div class="history-list">${versions.map((v,i)=>`<button data-version="${i}" class="history-item"><time>${new Date(v.date).toLocaleString('pt-BR')}</time><pre>${esc(v.code.slice(0,200))}</pre></button>`).reverse().join('')}</div>`:'<p>Execute seu código para guardar a primeira versão.</p>');dialog.querySelectorAll<HTMLElement>('[data-version]').forEach(button=>button.addEventListener('click',()=>{const code=versions[Number(button.dataset.version)].code;snapshot(id,editor!.getValue());editor!.setValue(code);dialog.close();}));});
 cleanup=()=>{disposed=true;clearTimeout(saveTimer);if(editor){progress.drafts[id]=editor.getValue().slice(0,30000);saveProgress();editor.dispose();}execution?.cancel();window.removeEventListener('keydown',key);};refreshIcons();
}
function showResult(result:RunResult,id:string){const m=missions.find(x=>x.id===id)!;const el=document.querySelector('#result')!;el.innerHTML=`<div class="result-heading ${result.passed?'success':'needs-work'}">${icon(result.passed?'circle-check':'scan-search')}<b>${result.passed?'Você fez o mundo responder.':result.error?'Vamos investigar juntos.':'Seu código rodou. Vamos observar.'}</b><small>${result.duration} ms</small></div>${result.error?`<pre>${esc(result.error)}</pre>`:!result.passed?'<p>Compare os testes abaixo com o resultado esperado. Uma pista pode ajudar a escolher seu próximo passo.</p>':`<p>Conceito praticado: ${m.concept}. ${progress.hints[id]?'Experimente resolver novamente sem pistas para fortalecer sua autonomia.':'Você chegou à solução por conta própria.'}</p>`}${result.logs.length?`<details open><summary>Console · ${result.logs.length} mensagem(ns)</summary><pre>${esc(result.logs.join('\n'))}</pre></details>`:''}${result.passed?`<a class="button primary" href="#/${missions.indexOf(m)<missions.length-1?'missao/'+missions[missions.indexOf(m)+1].id:'projetos'}">${missions.indexOf(m)<missions.length-1?'Próxima descoberta':'Construir um projeto'} ${icon('arrow-right')}</a>`:''}`;
 document.querySelector('#tests')!.innerHTML=(result.tests.length?result.tests:m.tests.map(label=>({label,passed:false}))).map(t=>`<li class="${t.passed?'passed':'pending'}">${icon(t.passed?'circle-check':'circle')} ${esc(t.label)}</li>`).join('');const effect=document.querySelector('#effect')!;const trees=result.actions.filter(a=>a.type==='tree').length;const message=result.actions.find(a=>a.type==='message');const energy=result.actions.find(a=>a.type==='energy'||a.type==='beacon');const items=result.actions.find(a=>a.type==='items');effect.classList.toggle('activated',result.actions.length>0);effect.innerHTML=`<div class="lantern ${result.passed?'lit':''}">${trees?Array.from({length:Math.min(trees,12)},()=>icon('tree-pine')).join(''):icon(id==='ponte'?'route':id==='farol'?'tower-control':id==='inventario'?'boxes':'lamp-desk')}</div><span>${message?esc(message.value):energy?`${esc(energy.value)} de energia`:items?esc(JSON.stringify(items.value)):trees?`${trees} árvores ganharam vida.`:result.actions.some(a=>a.type==='bridge')?'A ponte está aberta.':result.actions.some(a=>a.type==='light')?'Uma ideia acaba de acender.':'O mundo aguarda sua próxima tentativa.'}</span>`;refreshIcons();}

function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

const diaryStarter=`<h1>Meu diário de ideias</h1><form><label for="ideia">Nova ideia</label><input id="ideia" required maxlength="200"><button>Guardar</button></form><ul></ul><script>document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const campo=document.querySelector('input'),texto=campo.value.trim();if(!texto)return;const item=document.createElement('li');item.textContent=texto;document.querySelector('ul').append(item);campo.value='';});</script>`;
const tasksStarter=`<h1>Pequenos passos</h1><form><label for="tarefa">Nova tarefa</label><input id="tarefa" required maxlength="120"><button>Adicionar</button></form><ul></ul><output aria-live="polite">0 pendentes</output><script>const lista=document.querySelector('ul');function contar(){document.querySelector('output').textContent=lista.querySelectorAll('input:not(:checked)').length+' pendentes';}document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const campo=document.querySelector('#tarefa');if(!campo.value.trim())return;const li=document.createElement('li'),label=document.createElement('label'),check=document.createElement('input'),remover=document.createElement('button');check.type='checkbox';check.onchange=contar;label.append(check,document.createTextNode(campo.value.trim()));remover.textContent='Remover';remover.onclick=()=>{li.remove();contar();};li.append(label,remover);lista.append(li);campo.value='';contar();});</script>`;
function coursePage(id:string){const c=courses.find(c=>c.id===id);if(!c){go('aprender');return;}main.innerHTML=`<section class="page"><a class="back" href="#/aprender">${icon('arrow-left')} Todas as trilhas</a><p class="eyebrow">TRILHA · ${c.lessonIds.length} AULAS</p><h1>${c.title}</h1><p class="lead">${c.description}</p><div class="mission-list">${c.lessonIds.map((id,i)=>{const l=lessons.find(l=>l.id===id)!;return `<a href="#/aula/${id}" class="mission-row"><span class="mission-number">${progress.lessons.includes(id)?icon('check'):i+1}</span><span><h2>${l.title}</h2><p>${l.body.slice(0,135)}…</p></span>${icon('arrow-right')}</a>`;}).join('')}</div></section>`;}
function lesson(id:string,readingOnly=false){
 if(id==='valores'&&!readingOnly){let active=true;let dispose=()=>{};cleanup=()=>{active=false;dispose();};void Promise.all([import('./learning/engine'),import('./learning/valores')]).then(([engine,content])=>{if(!active)return;const l=lessons.find(l=>l.id===id)!;dispose=engine.mountLesson(main,content.valores,l.title,'#/trilha/'+l.track);}).catch(()=>{if(active)lesson(id,true);});return;}
 const l=lessons.find(l=>l.id===id);if(!l){go('aprender');return;}
 const c=courses.find(c=>c.id===l.track)!,index=c.lessonIds.indexOf(id),next=c.lessonIds[index+1];
 const textoProfundo=l.capitulos.flatMap(cap=>[...cap.paragrafos,...(cap.pontos??[])]).join(' ');
 const minutos=Math.max(8,Math.ceil(textoProfundo.split(/\s+/).filter(Boolean).length/180));
 const mapa=l.capitulos.map((cap,i)=>`<a href="#aula-${cap.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(cap.titulo)}</a>`).join('');
 const capitulos=l.capitulos.map((cap,i)=>{const paragrafos=cap.paragrafos.map(p=>`<p>${esc(p)}</p>`).join('');const pontos=cap.pontos?.length?`<ol class="lesson-points">${cap.pontos.map(p=>`<li>${esc(p)}</li>`).join('')}</ol>`:'';const codigo=cap.codigo?(cap.id==='solucao'?`<details class="lesson-solution deep-solution"><summary>Mostrar a solução de referência</summary><pre class="example-code"><code>${esc(cap.codigo)}</code></pre><p>Feche a solução e tente reconstruí-la sem olhar. Se conseguir explicar por que cada decisão existe, você está usando o gabarito como estudo, não como cópia.</p></details>`:`<pre class="example-code"><code>${esc(cap.codigo)}</code></pre>`):'';const bancada=cap.id==='codigo'?`<button class="button subtle" id="practice-lesson">${icon('terminal')} Abrir este exemplo em uma nova bancada</button>`:'';return `<section class="lesson-chapter" id="aula-${cap.id}"><div class="lesson-chapter-head"><span>${String(i+1).padStart(2,'0')}</span><div><p class="eyebrow">${esc(cap.subtitulo)}</p><h2>${esc(cap.titulo)}</h2></div></div><div class="lesson-chapter-body">${paragrafos}${pontos}${codigo}${bancada}</div></section>`;}).join('');
 main.innerHTML=`<article class="page reading deep-reading"><a class="back" href="#/trilha/${c.id}">${icon('arrow-left')} ${c.title}</a><p class="eyebrow">AULA ${index+1} DE ${c.lessonIds.length} · ESTUDO PROFUNDO</p><h1>${l.title}</h1><p class="lesson-intro">Esta aula foi construída para você compreender o assunto até conseguir explicar, modificar, testar e depurar por conta própria. Não leia correndo: faça as previsões e os experimentos.</p><div class="lesson-meta"><span>${l.capitulos.length} capítulos</span><span>≈ ${minutos} min de estudo ativo</span><span>exemplo + prática + projeto</span></div><nav class="lesson-map" aria-label="Mapa desta aula"><p>MAPA DA AULA</p>${mapa}</nav>${capitulos}<section class="lesson-final-check"><p class="eyebrow">VERIFICAÇÃO FINAL</p><h2>Antes de marcar como concluída</h2><p>Responda sem voltar ao texto. Se errar, não tente decorar a alternativa correta: descubra qual parte do seu modelo mental ainda está incompleta.</p><form id="lesson-check" class="lesson-check"><fieldset><legend>${esc(l.question)}</legend>${l.options.map((o,i)=>`<label><input type="radio" name="answer" value="${i}" required> <span>${esc(o)}</span></label>`).join('')}</fieldset><button class="button primary">Conferir resposta</button><p id="lesson-feedback" role="status">${progress.lessons.includes(id)?'Aula já concluída. Você pode revisar quando quiser.':''}</p></form></section><div class="reading-nav"><a href="#/${index?'aula/'+c.lessonIds[index-1]:'trilha/'+c.id}">${icon('arrow-left')} Voltar</a><a href="#/${next?'aula/'+next:'aprender'}">${next?'Próxima aula':'Explorar outra trilha'} ${icon('arrow-right')}</a></div><p class="source">Conteúdo e exercícios originais do CODELAB. <a href="${l.source}" target="_blank" rel="noopener">Consultar documentação técnica</a>.</p></article>`;
 main.querySelector('#lesson-check')!.addEventListener('submit',e=>{e.preventDefault();if(id==='valores'&&readingOnly){go('aula/'+id);return;}const answer=Number(new FormData(e.target as HTMLFormElement).get('answer'));const feedback=main.querySelector('#lesson-feedback')!;if(answer!==l.correct){feedback.textContent='Ainda não. Volte ao capítulo relacionado, refaça a previsão e explique a alternativa com suas próprias palavras antes de tentar novamente.';return;}if(!progress.lessons.includes(id))progress.lessons.push(id);saveProgress();feedback.textContent='Resposta correta. A aula foi concluída, mas o domínio real vem quando você consegue reconstruir e adaptar o conceito sem consultar o exemplo.';});
 main.querySelectorAll<HTMLAnchorElement>('.lesson-map a').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();main.querySelector(link.getAttribute('href')!)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}));
 main.querySelector('#practice-lesson')?.addEventListener('click',()=>{if(progress.projects.length>=12){toast('Limite de 12 bancadas salvas. Exporte e remova um projeto.');return;}const projectId=crypto.randomUUID();progress.projects.push({id:projectId,title:l.title,language:l.language,code:l.code,updatedAt:new Date().toISOString()});saveProgress();go('laboratorio/'+projectId);});
}

function projects(){main.innerHTML=`<section class="page"><p class="eyebrow">DA IDEIA AO QUE EXISTE</p><h1>Construa algo seu.</h1><p class="lead">Use o que descobriu para criar uma aplicação. Planeje, experimente e exporte seus arquivos.</p><div class="project-grid"><article class="project"><div class="project-cover">${icon('notebook-pen')}<span>01</span></div><small>HTML · CSS · DOM</small><h2>Meu diário de ideias</h2><p>Crie uma página pessoal com suas ideias. Adicione título, categorias, formulário e uma lista de notas.</p><ul><li>Uma estrutura semântica</li><li>Um visual que tenha a sua cara</li><li>Um formulário que acrescenta notas</li><li>Dados salvos com localStorage no projeto exportado</li></ul><button class="button primary project-start" data-project="diario">Abrir minha bancada ${icon('arrow-right')}</button></article><article class="project"><div class="project-cover second">${icon('list-checks')}<span>02</span></div><small>HTML · CSS · JAVASCRIPT</small><h2>Pequenos passos</h2><p>Construa um organizador de tarefas com inclusão, conclusão, remoção e contagem de tarefas pendentes.</p><ul><li>Um campo e um botão para adicionar</li><li>Um estado para cada tarefa</li><li>Eventos para concluir e remover</li><li>Um contador que acompanha a lista</li></ul><button class="button primary project-start" data-project="tarefas">Começar a construir ${icon('arrow-right')}</button></article></div><div class="callout">${icon('info')}<p>Cada projeto tem sua própria bancada e é salvo localmente. Exporte uma cópia para backup. O preview não permite armazenamento; teste localStorage no arquivo exportado servido por HTTP.</p></div></section>`;document.querySelectorAll<HTMLElement>('.project-start').forEach(b=>b.addEventListener('click',()=>{if(progress.projects.length>=12){toast('Limite de 12 projetos. Exporte e remova um antes de continuar.');return;}const kind=b.dataset.project!,id=crypto.randomUUID();progress.projects.push({id,title:kind==='diario'?'Meu diário de ideias':'Pequenos passos',language:'html',code:kind==='diario'?diaryStarter:tasksStarter,updatedAt:new Date().toISOString()});saveProgress();go('laboratorio/'+id);}));
 const saved=document.createElement('div');saved.className='page';saved.innerHTML='<h2>Meus projetos neste dispositivo</h2>'+ (progress.projects.length?progress.projects.map(p=>`<article class="saved-project"><a href="#/laboratorio/${p.id}"><h3>${esc(p.title)}</h3><small>${esc(p.language)} · ${esc(p.updatedAt.slice(0,10))}</small></a><button class="button subtle" data-rename="${p.id}">Renomear</button><button class="button subtle" data-delete="${p.id}">Remover</button></article>`).join(''):'<p>Comece um projeto acima ou salve sua bancada no laboratório.</p>');main.append(saved);saved.querySelectorAll<HTMLElement>('[data-rename]').forEach(b=>b.addEventListener('click',()=>{const p=progress.projects.find(p=>p.id===b.dataset.rename)!;modal('Nome do projeto',`<label class="field">Nome<input id="project-name" maxlength="60" value="${esc(p.title)}"></label><button class="button primary" id="confirm-name">Salvar nome</button>`);dialog.querySelector('#confirm-name')!.addEventListener('click',()=>{p.title=dialog.querySelector<HTMLInputElement>('#project-name')!.value.trim().slice(0,60)||p.title;saveProgress();dialog.close();route();});}));saved.querySelectorAll<HTMLElement>('[data-delete]').forEach(b=>b.addEventListener('click',()=>{modal('Remover projeto local?','<p>Exporte uma cópia antes se quiser guardar este código.</p><button class="button primary" id="confirm-delete">Remover projeto</button>');dialog.querySelector('#confirm-delete')!.addEventListener('click',()=>{progress.projects=progress.projects.filter(p=>p.id!==b.dataset.delete);saveProgress();dialog.close();route();});}));}
function library(){main.innerHTML=`<section class="page"><p class="eyebrow">CONHECIMENTO QUE ABRE CAMINHOS</p><h1>Sua biblioteca.</h1><p class="lead">Respostas diretas, exemplos pequenos e um lugar para colocar cada ideia em prática.</p><p><a class="button primary" href="#/aprender">Explorar as 12 trilhas · 60 aulas</a></p><div class="article-grid">${articles.map(a=>`<a href="/conceitos/${a.slug}/" class="article-card" data-article="${a.slug}">${icon('book-open')}<h2>${a.title}</h2><p>${a.lead}</p><span>Ler e experimentar ${icon('arrow-up-right')}</span></a>`).join('')}</div><div class="editorial"><h2>Como o conteúdo é produzido</h2><p>As explicações e missões desta edição são originais do CODELAB. Os exemplos são pequenos e verificáveis; a documentação MDN acompanha cada conceito como referência técnica. Os desafios são testados com entradas diferentes das exibidas.</p><p>As 12 trilhas reúnem 60 aulas com exemplos, exercícios e verificações de aprendizado. As oito missões iniciais possuem avaliação automática de código. Aulas de rede, banco e servidor indicam o ambiente necessário para praticar.</p><a href="https://github.com/renancodando/CodeLab" target="_blank" rel="noopener">Sobre o projeto no GitHub ${icon('arrow-up-right')}</a></div></section>`;bindArticles();}
function bindArticles(){document.querySelectorAll<HTMLElement>('[data-article]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go('artigo/'+a.dataset.article);}));}
function article(slug:string){const a=articles.find(x=>x.slug===slug);if(!a){go('biblioteca');return;}main.innerHTML=`<article class="page reading"><a class="back" href="#/biblioteca">${icon('arrow-left')} Biblioteca</a><p class="eyebrow">JAVASCRIPT · CONCEITO</p><h1>${a.title}</h1><p class="lead">${a.lead}</p><h2>Entenda a ideia</h2><p>${a.body}</p><pre class="example-code"><code>${esc(a.code)}</code></pre><h2>Um erro comum</h2><p>${a.error}</p><a class="button primary" href="#/missao/${a.mission}">Faça o mundo responder ${icon('arrow-right')}</a><h2>Continue explorando</h2><div class="related">${articles.filter(x=>x.slug!==slug).map(x=>`<a href="#/artigo/${x.slug}">${x.title} ${icon('arrow-up-right')}</a>`).join('')}</div><p class="source">Referência técnica: <a href="${a.source}" target="_blank" rel="noopener">MDN Web Docs</a>. Texto educacional original do CODELAB.</p></article>`;}
function profile(){const xp=totalXp();main.innerHTML=`<section class="page"><p class="eyebrow">CADA PASSO CONTA</p><h1>Sua jornada, ${esc(progress.name)}.</h1><p class="lead">Seu progresso está salvo somente neste navegador, sem conta. Exporte uma cópia para levar a outro dispositivo.</p><div class="stats"><div><b>${xp}</b><span>XP conquistados</span></div><div><b>${progress.completed.length}</b><span>missões concluídas</span></div><div><b>${progress.lessons.length}</b><span>aulas concluídas</span></div><div><b>${1+Math.floor(xp/250)}</b><span>nível de explorador</span></div></div><div class="profile-form"><label>Como podemos chamar você?<input id="profile-name" maxlength="40" value="${esc(progress.name)}"></label><button class="button primary" id="save-name">Salvar nome</button><button class="button subtle" id="export-progress">${icon('download')} Exportar jornada</button><label class="button subtle import-label">${icon('upload')} Importar jornada<input id="import-progress" type="file" accept="application/json" hidden></label></div><div class="section-title"><h2>Seu mapa de domínio</h2></div><div class="mastery">${missions.map(m=>`<div><span>${m.concept}</span><b>${progress.completed.includes(m.id)?progress.hints[m.id]?'Compreendido':'Praticado sem pistas':progress.attempts[m.id]?'Praticando':'Novo'}</b><a href="#/missao/${m.id}">${progress.review[m.id]&&new Date(progress.review[m.id])<=new Date()?'Revisar agora':'Praticar'} ${icon('arrow-right')}</a></div>`).join('')}</div><div class="mastery">${Object.keys(progress.lessonSessions).filter(id=>lessons.some(l=>l.id===id)).map(id=>`<div><span>${esc(lessons.find(l=>l.id===id)!.title)}</span><b>${progress.lessonSessions[id].completedAt?'Prática concluída':'Em prática'}</b><a href="#/aula/${id}">${progress.review['aula-'+id]&&new Date(progress.review['aula-'+id])<=new Date()?'Revisar agora':'Continuar prática'}</a></div>`).join('')}</div><section class="account"><h2>Seus dados ficam com você</h2><p>Não há login, cadastro ou sincronização. Limpar os dados do navegador apaga sua jornada. Use Exportar e Importar para fazer backups.</p></section></section>`;
 document.querySelector('#save-name')!.addEventListener('click',()=>{progress.name=(document.querySelector<HTMLInputElement>('#profile-name')!.value.trim()||'Explorador');saveProgress();toast('Nome salvo.');route();});document.querySelector('#export-progress')!.addEventListener('click',()=>download('codelab-jornada.json',JSON.stringify(progress,null,2),'application/json'));
 document.querySelector('#import-progress')!.addEventListener('change',async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>2e6){toast('Esse arquivo é grande demais.');return;}try{const data=JSON.parse(await file.text());const validated=prepareBackup(data);modal('Restaurar esta jornada?',`<p>O arquivo tem ${Array.isArray(data.completed)?data.completed.length:0} missões concluídas. A jornada atual será substituída. Exporte uma cópia antes se quiser preservá-la.</p><button id="confirm-import" class="button primary">Restaurar jornada</button>`);document.querySelector('#confirm-import')!.addEventListener('click',()=>{replaceProgress(validated);dialog.close();route();toast('Jornada restaurada.');});}catch(error){toast(error instanceof Error?error.message:'Não reconheci esse arquivo de jornada.');}});
}

function search(){modal('Encontre sua próxima descoberta',`<label class="search-input">${icon('search')}<input id="search-query" placeholder="Variáveis, loops, um erro…" autocomplete="off"></label><div id="search-results"></div>`);const input=document.querySelector<HTMLInputElement>('#search-query')!;const update=()=>{const q=input.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const all=[...lessons.map(l=>({title:l.title,description:courses.find(c=>c.id===l.track)!.title+' '+l.body.slice(0,120),searchText:l.capitulos.flatMap(cap=>[cap.titulo,cap.subtitulo,...cap.paragrafos,...(cap.pontos??[])]).join(' '),route:'aula/'+l.id})),...missions.map(m=>({title:m.title,description:m.concept+' '+m.summary,route:'missao/'+m.id})),...articles.map(a=>({title:a.title,description:a.lead,route:'artigo/'+a.slug})),{title:'Laboratório',description:'Escrever e executar código livre',route:'laboratorio'},{title:'Configurar ambiente',description:'Clima, localização e som',route:'ambiente'}].filter(x=>(x.title+' '+x.description+' '+('searchText' in x?String(x.searchText):'')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q));document.querySelector('#search-results')!.innerHTML=all.length?all.map(x=>`<button class="search-result" data-route="${x.route}"><span><b>${x.title}</b><small>${x.description}</small></span>${icon('arrow-up-right')}</button>`).join(''):'<p>Nenhuma descoberta encontrada. Experimente “variáveis” ou “loops”.</p>';dialog.querySelectorAll<HTMLElement>('[data-route]').forEach(b=>b.addEventListener('click',()=>{dialog.close();if(b.dataset.route==='ambiente')settings();else go(b.dataset.route!);}));refreshIcons();};input.addEventListener('input',update);input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();dialog.querySelector<HTMLButtonElement>('.search-result')?.focus();}if(e.key==='Enter')dialog.querySelector<HTMLButtonElement>('.search-result')?.click();});update();input.focus();}
function settings(){modal('Um mundo no seu ritmo',`<p>Use seu clima e horário para transformar o mundo do CODELAB. A posição do Sol e da Lua é calculada no navegador.</p><label class="field">Escolha uma cidade<select id="city">${cities.map(c=>`<option value="${c.name}" ${environment.city.startsWith(c.name)?'selected':''}>${c.name}</option>`).join('')}</select></label><button class="button primary" id="apply-city">Sincronizar com esta cidade</button><div class="divider"></div><h3>Sincronizar ambiente com meu local</h3><p>Ao permitir, sua localização aproximada será enviada à Open-Meteo para consultar o clima. Coordenadas não são guardadas no perfil.</p><button class="button subtle" id="geolocate">${icon('locate-fixed')} Usar minha localização</button><p id="weather-message" role="status">${environment.source==='default'?'Condições ilustrativas para a localização selecionada.':`${esc(environment.city)} · ${Math.round(environment.temperature)} °C · vento ${Math.round(environment.wind)} km/h`}</p><label class="field"><span><input id="flashes" type="checkbox" ${flashesEnabled?'checked':''}> Permitir clarões suaves de tempestade</span></label><label class="field">Volume ambiente<input id="volume" type="range" min="0" max="100" value="${Math.round(ambientVolume*100)}"></label><p class="small">Movimento reduzido acompanha a preferência do seu sistema. <a href="https://open-meteo.com/" target="_blank" rel="noopener">Dados meteorológicos: Open-Meteo</a>.</p>`);
 const apply=async(lat:number,lon:number,name:string)=>{const msg=document.querySelector('#weather-message')!;msg.textContent='Consultando o clima…';try{await weather.select(lat,lon,name);msg.textContent=environment.source==='default'?'Sem dados recentes: ambiente neutro ilustrativo.':environment.source==='cached'?'Sem conexão: última condição conhecida, por até duas horas.':'Ambiente sincronizado. Atualização automática a cada cinco minutos.';}catch{msg.textContent='Não foi possível consultar o clima. O mundo continua com as condições anteriores.';}};
 document.querySelector('#flashes')!.addEventListener('change',e=>{flashesEnabled=(e.target as HTMLInputElement).checked;world?.setFlashes(flashesEnabled);});
 document.querySelector('#apply-city')!.addEventListener('click',()=>{const city=cities.find(c=>c.name===document.querySelector<HTMLSelectElement>('#city')!.value)!;void apply(city.lat,city.lon,city.name);});document.querySelector('#geolocate')!.addEventListener('click',()=>{if(!navigator.geolocation){toast('Localização indisponível. Escolha uma cidade.');return;}document.querySelector('#weather-message')!.textContent='Aguardando sua permissão…';navigator.geolocation.getCurrentPosition(p=>void apply(p.coords.latitude,p.coords.longitude,'Seu local'),()=>{document.querySelector('#weather-message')!.textContent='Sem acesso à localização. Você pode escolher uma cidade acima.';},{enableHighAccuracy:false,timeout:12000,maximumAge:600000});});document.querySelector('#volume')!.addEventListener('input',e=>{const value=Number((e.target as HTMLInputElement).value)/100;void setAudio(value);});}
function updateWeather(){document.querySelector('#weather-status')!.innerHTML=`${icon(environment.rain>0?'cloud-rain': 'wind')}<span>${environment.source==='default'?'Um mundo vivo':'Ambiente sincronizado'}<small>${esc(environment.source==='default'?'Condições ilustrativas':environment.city)}${environment.source==='cached'?' · offline':''}</small></span>`;refreshIcons();}
async function setAudio(volume:number){await ambientAudio.setVolume(volume);ambientVolume=volume;soundEnabled=volume>0;document.querySelector('#sound')!.setAttribute('aria-pressed',String(soundEnabled));document.querySelector('#sound')!.setAttribute('aria-label',soundEnabled?'Desativar som ambiente':'Ativar som ambiente');document.querySelector('#sound')!.innerHTML=icon(soundEnabled?'volume-2':'volume-x');refreshIcons();}
document.querySelector('#search')!.addEventListener('click',search);document.querySelector('#environment')!.addEventListener('click',settings);document.querySelector('#weather-status')!.addEventListener('click',settings);document.querySelector('#sound')!.addEventListener('click',()=>void setAudio(soundEnabled?0:.25));window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search();}});window.addEventListener('hashchange',route);window.addEventListener('storageerror',()=>toast('O navegador não conseguiu salvar. Exporte uma cópia da jornada no perfil.'));window.addEventListener('offline',()=>toast('Você está offline. Suas descobertas continuam salvas neste dispositivo.'));window.addEventListener('progresschange',()=>{document.querySelector('#mini-name')!.textContent=progress.name;document.querySelector('#mini-level')!.textContent=`Nível ${1+Math.floor(totalXp()/250)}`;});
route();refreshIcons();
void import('./environment/world').then(({LivingWorld})=>{try{world=new LivingWorld(document.querySelector('#world')!,frame=>ambientAudio.step(frame),event=>ambientAudio.thunder(event));world.setEnvironment(environment);world.setActive(currentRoute()==='home');}catch{document.querySelector('#world')!.classList.add('no-webgl');toast('O modo gráfico simplificado está ativo. Todas as missões continuam disponíveis.');}});
window.addEventListener("pagehide",event=>{if(!event.persisted){weather.dispose();world?.dispose();ambientAudio.dispose();cleanup();}});
