import {describe,it,expect} from 'vitest';
import {answerFor,canAdvance,createSession,currentIndex,isComplete,mastery,move,normalizeSessions,recordAnswer,checkAnswer} from '../../src/learning/session';
import {valores} from '../../src/learning/valores';
import {evaluate} from '../../src/execution/evaluate';
describe('aula em passos',()=>{
 it('só avança em avaliação respondida corretamente e permite voltar',()=>{const session=createSession(valores);expect(move(session,valores,1)).toBe(true);expect(move(session,valores,1)).toBe(false);const step=valores.steps[1];recordAnswer(answerFor(session,step),false);expect(canAdvance(session,step)).toBe(false);recordAnswer(answerFor(session,step),true);expect(move(session,valores,1)).toBe(true);expect(move(session,valores,-1)).toBe(true);expect(currentIndex(session,valores)).toBe(1);expect(isComplete(session,valores)).toBe(false);});
 it('não inventa domínio antes de prática e distingue solução de independência',()=>{const session=createSession(valores);expect(mastery(session,valores).every(s=>s.score===null)).toBe(true);const step=valores.steps.find(s=>s.capability==='producao')!;const answer=answerFor(session,step);answer.assisted=true;recordAnswer(answer,true);expect(mastery(session,valores).find(s=>s.capability==='producao')!.score).toBe(20);expect(answer.firstTry).toBe(false);});
 it('pistas e falhas reduzem a evidência de autonomia',()=>{const session=createSession(valores);const step=valores.steps[1],answer=answerFor(session,step);recordAnswer(answer,false);answer.hints=1;recordAnswer(answer,true);expect(mastery(session,valores)[0].score).toBe(65);expect(answer.attempts).toBe(2);});
 it('reconhece respostas vazias e fornece feedback da alternativa escolhida',()=>{const step=valores.steps[1];expect(checkAnswer(step,'').passed).toBe(false);expect(checkAnswer(step,'0').feedback).toContain('nome');expect(checkAnswer(step,String(step.correct)).passed).toBe(true);});
 it('restaura sessões sem chaves perigosas nem dados ilimitados',()=>{const normalized=normalizeSessions(JSON.parse('{"__proto__":{},"constructor":{},"valores":{"revision":1,"currentStep":"produzir-texto","answers":{"__proto__":{},"constructor":{},"produzir-texto":{"value":"const nome = 1","attempts":2,"hints":1,"passed":true,"assisted":false,"firstTry":false}}}}'));expect(Object.keys(normalized)).toEqual(['valores']);expect(Object.keys(normalized.valores.answers)).toEqual(['produzir-texto']);expect(normalized.valores.currentStep).toBe('produzir-texto');});
 it('tem 25 passos próprios, seis capacidades e IDs únicos',()=>{expect(valores.steps).toHaveLength(25);expect(new Set(valores.steps.map(s=>s.id)).size).toBe(25);expect(new Set(valores.steps.flatMap(s=>s.capability?[s.capability]:[])).size).toBe(6);});
 for(const step of valores.steps.filter(s=>s.type==='code'))it('executa solução real: '+step.id,async()=>{expect(step.checks!.length).toBeGreaterThan(0);const result=await evaluate(step.solution!,'aula',step.checks);expect(result.error).toBeUndefined();expect(result.passed).toBe(true);});
 it('recusa orçamento fixo que falha para novas entradas',async()=>{const step=valores.steps.at(-1)!;const result=await evaluate('function saldoAposCompra(){return 64;}','aula',step.checks);expect(result.passed).toBe(false);expect(result.tests.filter(t=>!t.passed).length).toBe(3);});
 it('não aprova uma avaliação sem verificações',async()=>{expect((await evaluate('let energia = 100;','aula')).passed).toBe(false);});
});
